### ISSUE TITLE
General Project Discussion

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#1]
This issue page is for general discussion of this fork.

**Comment by morphicschris** [comment]
Just committed a version with my 1.6.4 files int he 1.7.10 Forge project.

**Comment by EternalBlueFlame** [comment]
Beautiful, I didn't have to do a thing for that, so it seems to be working as intended.
I'm looking forward to getting to getting this setup on my end and doing some debugging tomorrow, well technically later today, haha.
A nice distraction from my other git project that drives me nuts.

**Comment by morphicschris** [comment]
Haha. Yeah, looking forward to getting it all working again and playing around with it. I've got a week or so to do what I can on it but then I'm away for 10 days until I can next take a look at it.

**Comment by morphicschris** [comment]
Here are the most common errors I can see so far when I build:

`Cannot find symbol ChatMessageComponent`
This seems to have become `net.minecraft.util.ChatComponentText`.

`Cannot find symbol IconRegister`
Now `IIconRegister`.

`Cannot find symbol Icon`
Now `IIcon`.

`Cannot find symbol ForgeDirection`
This moved from namespace `net.minecraftforge.common.ForgeDirection` to `net.minecraftforge.common.util.ForgeDirection`.

`Cannot find symbol EnumArmorMaterial`
I think this has now become `net.minecraft.item.ItemArmor.ArmorMaterial`.

There's a lot of stuff about Packets, Players, and the INetworkManager which seem to be because of the change in the networking code (if I remember right, 1.7 is when singleplayer mode actually became a self-hosted server?). Not sure how to tackle these just yet.

I also found the following post which may be useful:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/1438034-upgrading-from-1-6-2-to-1-7-2-things-that-you-must

**Comment by EternalBlueFlame** [comment]
Thanks, that should help both of us.

Minecraft has been a selfhosted server in single player for a good while now, but what happened in 1.7 was that then entire networking system was changed over to [netty](http://netty.io/) this made it more obvious that single player is self-hosted multiplayer due to the extra initialization time that was the tradeoff for better performance.
We're lucky the forge API only changed as much as it did (Although it would be worth the effort to change more if the networking worked as well as KCauldron).
Space Engineers is going through a similar networking transition and they basically have to remake the majority of the game, I'm terrified of what that will do to their mods. Networking code is messy.

This all being said I have no idea on the packet and network manager stuff for now, but I would advise to leave that stuff for last, because other things we change/fix could change what we will have to do when fixing the networking.
It's also the hardest task so its best left for after we have a bit more experience with the API from fixing other stuff.

One thing that may also help is that most of the errors (9.5 out of 10 I'd assume) we will encounter are related to 1.7.2, because most mod devs went there before 1.7.10, so most of the "why doesn't this work?" being asked will be towards 1.7.2.
1.7.10 was only a bugfix and the addition of Realms, which shouldn't effect mods much, if at all.

**Comment by EternalBlueFlame** [comment]
Seems to import to InteliJ quite easily just by importing the Build.gradle.
Manually adding the Forge API is where i'm stuck.
It notes that I need C:\Users\(USER)\.gradle\caches\minecraft\net\minecraftforge\forge\1.7.10-10.13.4.1616-1.7.10\start
And i need Gradle :forgeBin:1.7.10-10.13.4.1616-1.7.10

Google search is being anything but helpful right now, but you dont seem to be having the same issue, so mine giving me a walkthrough?

When we get it noted how all this works we should probably note it in the readme.md....
While I wait for your reply I'll double over the information so I can be sure just how/what we are allowed to change the readme.md.

**Comment by EternalBlueFlame** [comment]
GOT IT WORKING.
I had to manually define the location of the JDK, and manually redirect the forge bin to the forge bin jar.
In a moment here I will upload the new README.md with the instructions and a number of changes.

**Comment by morphicschris** [comment]
Awesome, glad you got it working on your machine. With the dependencies, you've probably seen but I added a "dependencies" folder in the root. This contains the .jar files for Buildcraft, IC2, etc. I've just tried moving those files into the /lib folder to see if that fixes it for you, as I think maybe it's using hard-coded paths to the dependencies at the moment which won't match up on your machine. My hope is that it uses relative paths for things in the /lib folder. Try getting latest now to see if it's sorted it out.

Here's what I did just in case it hasn't fixed it.

In IntelliJ, load up the Traincraft project then go to File -> Project Structure... then select the Modules tab, and in the list on the right (probably at the very bottom) should be the added references to the .jar files. If they're there, edit them to point them to the correct file in the dependencies folder. If not, on the right click the plus button then select "JAR or directories...". You have to add each one individually, then in the list make sure they're ticked.

**Comment by EternalBlueFlame** [comment]
Yeah I tried the lib folder and it didn't help any, but adding them as dependencies did the trick.
Now I can actually get into some real debugging.

**Comment by morphicschris** [comment]
No worries. Worked out that I'd accidentally committed to the master branch rather than the 1,7 one, so I've reverted the changes there.

**Comment by EternalBlueFlame** [comment]
Yeah I had a feeling that might happen, the downfall of refactoring things.
Better early on than after it gets really complicated, haha.
I'll have to grab the latest source so I'm on the same page, at least I know what I'm doing now.

**Comment by morphicschris** [comment]
I've just gone through and fixed all the Icon, IconRegister, and ChatComponentMessage symbol errors. Pushed to github if you want to grab latest. Hopefully that should reduce the error count a bit.

**Comment by EternalBlueFlame** [comment]
I'd say so. Unfortunately somehow it has become 5AM here again...
Looks like my real contributions will be delayed once more. At least there's nothing to hold me back later today.

**Comment by EternalBlueFlame** [comment]
Going through scripts one by one and fixing errors, I can't help but think that rebuilding this from scratch might not be such a bad idea.

The entire mod is significantly more complex than it needs to be, the same result could be obtained by making custom minecarts with inventories/tanks/seats etc, that use the train graphic.
Alongside the extra ores, GUI, items, recipes, and custom crafting tables.
Kinda similar to Steve's Carts V2.

My honest opinion now would be, perhaps we should get this mod working, and then start again from scratch.
If this mod works in 1.7 we can use it kind of like a syllabus for various things when re-designing it, especially GUI and fluid/inventory management.

What are your thoughts?

**Comment by morphicschris** [comment]
I haven't had a proper chance to look through the code yet and work out how it all hangs together, just been working on fixing errors at the moment. But your suggestion does make sense, and it's not far from the original plan we had anyway which was to get it working first then start making changes. It's just that now we'll essentially be making and replicating those changes in a new, fresh mod rather than working in the existing one. I assume we'd still target this at 1.7 at first?

From looking at the code, do you have a rough idea how much effort will be involved in getting the networking code back up and running? That's the only thing that worries me at the moment, as it seems pretty integral to the mod and looks to have changed quite a bit between versions.

**Comment by EternalBlueFlame** [comment]
yeah, 1.7 would come first, mainly because all the mods we would want to interact with (railcraft, buildcraft, biomes o' plenty, ic2, etc) are all available and most stable in 1.7, unlike 1.9 and 1.8.
Plus the syllabus code from this mod would be 1.7.10.

as for the networking, i havn't gotten there yet, i've only fixed SteamTrain.java, Locomotive.java, EntityRollingStock.java and LiquidManager.java.
working on TCRail.java now.

**Comment by morphicschris** [comment]
Ok cool. I'm just setting up the environment on my home PC to start looking through it all here.

**Comment by EternalBlueFlame** [comment]
alright, sounds good.

**Comment by morphicschris** [comment]
Before when you said you had to manually redirect the forge binary, how did you do that? I think I have the same problem here.

**Comment by EternalBlueFlame** [comment]
file>project structure
moudles tab
there's gonna be one that errors out called :ForgeBin: or something along that line.
replace it with a reference to
C:\Users\USER.gradle\caches\minecraft\net\minecraftforge\forge\1.7.10-10.13.4.1614-1.7.10\forgeBin-1.7.10-10.13.4.1614-1.7.10.jar

**Comment by morphicschris** [comment]
Thanks. Managed to get it to work by running the following on the command line:

`gradlew setupDecompWorkspace --refresh-dependencies`

EDIT: I probably didn't need to edit the modules as the account name on my home PC is the same as on my laptop.

**Comment by EternalBlueFlame** [comment]
good to hear that worked for you. didn't help me when i had the issue. haha.

**Comment by EternalBlueFlame** [comment]
Okay scratch that I got the EntityRolling stock working, IDE lied to me.
there's a bunch of errors here because of how the world objects have changed, i think its intended to be processed in individual chunks now...?
I have no idea how to go about fixing this.

**Comment by EternalBlueFlame** [comment]
Alright, uploaded the work I finished, a lot of the fixes can probably be re-used for a lot of other things, and all the changes are noted in the update comment so it will be easy to search through if we gotta fix the same issue somewhere else.
scratch that, let me resolve some sync conflicts.

**Comment by EternalBlueFlame** [comment]
There we go. There was a merge request when I tried to upload, which fixed a bunch of code, but also broke some code I fixed, so I added the merge request along with a fix for what of my changes it broke.

The request was from Origin/ so I'm not sure who or where it came from, but any help is great.

Okay, so apparently github's client likes to put <<<<< and >>>> as if they are comments when a commit conflicts.
thats just gross.

**Comment by EternalBlueFlame** [comment]
Just did a bit deeper check on errors, for the moment there are 842 errors over 33 classes.
And guessing by the changes we've made thus far, they were just under 1100.

I guess this can serve as a bit of a mark in the progress.

You said you had about a week to work on this project, am I remembering that correctly?
If so I need to get a lot more serious with working on this project than I originally intended to be....
I guess things are gonna get interesting, haha.

**Comment by morphicschris** [comment]
Ok sounds like we're making good progress at least. Yeah I've got next week to work on it then I'm off to Peru for 10 days. Can pick up where I left off though when I get back.

**Comment by morphicschris** [comment]
Been reading some of the basics of forge modding today. It's all very well me working through errors but I'm getting to the point now where a bit more understanding is needed, so I've started a new mod and been working through some tutorials. Seems pretty straightforward so far.

**Comment by EternalBlueFlame** [comment]
I was thinking of doing the same to be fully honest.
At least a small mod that creates a new minecart which can be fueled by coal and still sat in.
That would be all stock features, so it should easy to implement, and a great starting point.

To go beyond that we'll need railcraft, or buildcraft, so I was thinking of making the mod an add-on to one of them, instead of having to have a secondary version of railcraft in the source like traincraft does.

On a side note I found a way to obsolete 
import net.minecraft.network.packet.Packet3Chat;

you just replace
PacketDispatcher.sendPacketToPlayer(new Packet3Chat(new ChatComponentText(String, Player);

with
FMLCommonHandler.instance().getMinecraftServerInstance().getConfigurationManager().sendChatMsg(string)

Handeling that now in AbstractTrains.java

**Comment by morphicschris** [comment]
Awesome, sounds like we're thinking along the same lines. Maybe we can work on test projects each and then compare what we've got when we've got the basics down? It definitely feels like the majority of content is just an extension of railcraft with some custom models.

**Comment by EternalBlueFlame** [comment]
I think that's a reasonable idea.
And I agree about how much feels like it's built off railcraft. I admit there's a significantly huge portion of non-railcraft code, but everything is just so heavily reliant on an inbuilt railcraft API.

I'll open a new git project on my page later today for what I'm building.

And I'm thinking maybe we do our own graphics, so we can fully separate from traincraft with it, since we have to rebuild everything anyway, I can look into if we can commission razzleberryfox(decocraft) for some train graphics, or if she just wants to join the project.
I mostly mention her because I know she has talent.

I will admit though, this port is great practice.

**Comment by morphicschris** [comment]
Cool, that would be great. The decocraft stuff is pretty fantastic so if she'd be willing to help out in any way that would be awesome. Do you see this as becoming a separate project to Traincraft, or a continuation, or some sort of "spritutal sequel"? I only ask because the licencing bit for Traincraft touches on it. I'd love it if we did get the endorsement of the original author(s) though.

**Comment by EternalBlueFlame** [comment]
If we wanna nab the endorsement of Spitfire and/or MrBrutal it would have to be a spiritual sequel. re-using graphics and whatnot where we can, and we'll be bound to the license and name of Traincraft.

Alternatively if we made our own as a totally separate project we wouldn't be bound to anything, but the support of Spitfire and/or MrBrutal is very questionable in this circumstance.

personally I'm open for either option. The latter is more open, but the former is easier (and would probably look more honorable).

**Comment by EternalBlueFlame** [comment]
second note on the port code, while working on LinkHandeler.java
entityplayer.addChatMessage(string)
can be replaced with entityplayer.addChatMessage(new ChatComponentText(string))

**Comment by morphicschris** [comment]
Ah cool, I thought I'd caught all the chat message calls but I must have missed some.

**Comment by EternalBlueFlame** [comment]
Well i was roughly 800 errors short the first time i manually did an error count, so who knows.
If nothing else, at least they are easy fixes.
//edit
i say that and then open KeyHandlerClient.
............ I'm just gonna leave this one for later

**Comment by morphicschris** [comment]
I'm just looking through other mods to see how they've structured things and if there's any with something similar to what we want to achieve.

https://github.com/agaricusb/ForgeMod/wiki/List-of-Open-Source-Forge-Mods

**Comment by EternalBlueFlame** [comment]
Well buildcraft and railcraft handle liquids, fuels and GUI similar to how we want to do that.
Steve's carts handles the carts very similar to what we'll probably have to do (their GUI is atrocious however).
Tinker's Construct (now you know why I don't call Traincraft "TC") handles crafting tables in a similar fashion to how we would want to, vaguely.

all aside from how Traincraft does things.

The main thing is that the mod revolves around minecarts/trains.
the only ones that do that are Traincraft, Railcraft, Steve's carts, and SUPER old versions of Rails of War.
Of course this doesn't count mods that haven't exactly gone public yet.

**Comment by EternalBlueFlame** [comment]
oh sweet, its probably bad practice, but you can still get block ID's via Block.getIdFromBlock(Block)
Okay here's a big fix.
BlockFluid is now BlockLiquid.
found that while working in TileWaterWheel

Nearing roughly 200 errors fixed, when i hit that point I'm gonna commit and call it a day on this port, then see about getting some work in on a rebuild from scratch.

**Comment by EternalBlueFlame** [comment]
Okay here's a big fix.
BlockFluid is now BlockLiquid.
found that while working in TikeWaterWheel

**Comment by EternalBlueFlame** [comment]
Nearing roughly 200 errors fixed, when i hit that point I'm gonna commit and call it a day on this port, then see about getting some work in on a rebuild from scratch.

**Comment by morphicschris** [comment]
Ok. Thanks for all the hard work. I'll grab a copy in the morning and have a look through.

**Comment by EternalBlueFlame** [comment]
No problem, you've been giving it some good effort too, so thanks to you as well.
The progress I've made by now is a bit over 200 errors fixed, I think. So I'll upload my progress now.

**Comment by EternalBlueFlame** [comment]
Okay so from the research I have been doing, you have to either find a way to extend EntityMinecart and ItemMinecart, or just remake them entirely.
Traincraft seems to use scr.train/common/AbstractTrains.java as the EntityMinecart, and then further extend it via EntityRollingStock, which then goes into Locomotive, then the respective train type, and then the actual train.

And of course the loving community that is minecraft forums (from what I can find), beyond what I just stated, have nothing helpful to say besides "shut up and learn java"
Because that's incredibly helpful....

Really the only thing I have learned is the default classes for minecarts are a bit poorly designed, and shouldn't even work in the first place, nor do they like being extended.
insult to injury GitHub wont let me have another repository on the desktop app, for no reason.
Not that I got any further than setting up a new mod base from forge src and copying the two previously stated classes.

**Comment by EternalBlueFlame** [comment]
Okay well good news and bad news.
Good news: I managed to fix all the errors I know how to fix. And a few fixes that are "this should probably work" fixes, which will have to be dealt with during the "it compiles, lets see if it works" phase.

The bad news: there's still roughly 350 errors remaining, mostly related to networking, and config files. And I had to take off yesterday due to power loss, so this update is a day later than I wanted it to be.

Any progress on your end?

**Comment by morphicschris** [comment]
Afraid I didn't get much time over the weekend to take a look at it because of family stuff, other than to play around a bit more with starting a new mod. I should have a chance again tonight though once work is out of the way.

Awesome news on fixing the errors, that's still a huge leap forward. I'll grab latest and see if I can work through the config file stuff.

**Comment by EternalBlueFlame** [comment]
between my other projects I've been dabbling with this one, since I'm in over my head at this point, basically nothing has worked or even sent me in the right direction until I ran across this, a tutorial for networking in 1.7.2 and later
[https://github.com/coolAlias/Tutorial-Demo/tree/master/src/main/java/tutorial/network](https://github.com/coolAlias/Tutorial-Demo/tree/master/src/main/java/tutorial/network)
As a heads up, I just found this, and have yet to read more than enough to understand it should work, or at least point us in the right direction.

And if it's any extra help, here's the 1.6.4 version of the tutorial so things can be compared [https://github.com/coolAlias/Forge_Tutorials/blob/master/IExtendedEntityPropertiesTutorial.java](https://github.com/coolAlias/Forge_Tutorials/blob/master/IExtendedEntityPropertiesTutorial.java)

As a side note I also figured out that the Player variables that error out are actually supposed to be EntityPlayer

Thought I'd give you a heads up, I'll work on it some tomorrow but you're welcome to jump ahead of me.

**Comment by morphicschris** [comment]
Ok cool, I'll have a read through those. I haven't had as much time as I'd hoped to look at the code this week because of preparations for going away, but hopefully things will be a bit quieter when I get back and I'll be able to look at it all bit more thoroughly.

**Comment by EternalBlueFlame** [comment]
That's understandable. And best of luck.
I'll try and accomplish what I can.

//edit
this tutorial gives A LOT of relevant information on the networking stuff.
I think all we really need to do in relation to packets is make our own Packet250CustomPayload class, and everything else, for the most part, should easily just fall into place.
http://www.minecraftforum.net/forums/mapping-and-modding/mapping-and-modding-tutorials/1571567-forge-1-6-4-1-8-eventhandler-and

Another thing is that a rewrite may not even be necessary after this port works, it looks really bad, but in reality, cleaning this up is mostly just refactoring and removing redundancies/unused features.
Not to mention the way the mod is managing this stuff is just about the only way to do it because of how minecarts and fluids are dealt with.

Later today I'll upload my changes thus far, now that I've learned some more, I've been trying to go deeper into the more complex code and fix what I can.
I should have at least 50 errors fixed by the end of the day, a couple hundred if I can get a custom Packet250CustomPayload class working.
No promises here, haha.

**Comment by EternalBlueFlame** [comment]
Well, I fixed the config stuff. and basically everything but the packets and the tick handler.
Uploaded the changes to git so you can grab em if you want em.

**Comment by EternalBlueFlame** [comment]
Okay, well I went on a little hiatus. Again. haha.
At any rate I managed to make the custom packet to replace the old one, so that should fix a lot of errors and make it easier, but the networking is by no means on its feet again.
Also managed to fix a few hundred other errors, more of the same stuff.

At this point I think there are just so many errors that Intelij can't even begin to report them all.
From the errors it shows there are still 492 errors.
The last check I did there was roughly 350, and I know my changes didn't cause more errors.

Either way it's something since I'm still stumped on the whole custom minecart thing, which would be needed for a total rework.

**Comment by morphicschris** [comment]
Hey. I'm back in the country again so once I'm back into the swing of things I'll try and grab your latest code and start thinking about what to work on next.

**Comment by EternalBlueFlame** [comment]
Awesome, hope you had a pleasant trip.
You've got a good pick of errors available to mow through, of various difficulties.
The major issues currently seem to be related to the networking still, and villages.

And of course there's always the rewrite, if you can figure out how to get minecarts working.

Also I did some research, upgrading from 1.7 to 1.9 later down the road shouldn't be very difficult at all. Most all the functions are the same but the imports have different URI's. Tedious but easy.

**Comment by EternalBlueFlame** [comment]
Assuming you haven't worked on it already, or are planning to, I'll tackle the village related errors tomorrow while I finally have some free time.
They are all generally related, and unreasonably numerous, so that will be a really good chunk of problems out of the way. No idea how to fix them yet, but I'll figure it out when I'm knee deep, haha.
That strategy has worked thus far.

**Comment by morphicschris** [comment]
Yeah sadly not, work and family life has been taking up most of my time at the moment. But I haven't forgotten about this project lol. Just trying to find a good chunk of time I can dedicate to actually getting into the code and fixing problems.

**Comment by EternalBlueFlame** [comment]
Yeah I know that feeling, have a little bit of that myself going on, along with other projects.
Lately it feels like I only get a day a week to tackle this thing.

//edit
I think I'll try and tackle more than the villages today. Most of these errors are just that the class had the wrong extend and that it used ID's instead of blocks. A lot less difficult than I had anticipated.
Fixed the first part, the ID's part is just tedious.

before it was like;
Block.planks.BlockID
Item.emerald.ItemID
now it's;
Block.getBlockById(5)
Item.getItemById(388)
or alternatively;
Block.getBlockByName("planks")
no Item version for this.

//edit 2
Okay just uploaded the changes, managed to fix most (if not all) village related problems, a good chunk of the tick related issues, and got, what I think may be, a good start to fixing the network related stuff.
InteliJ is only reporting 203 errors now.

**Comment by EternalBlueFlame** [comment]
Fixed a large number of errors. The stuff that's left is getting well out of my skill level, and I'm having a difficult time finding documentation to explain how these changes are supposed to work. Or even just what to change/remove.

**Comment by ejelinek** [comment]
I apologize for not being more involved, its life. I was looking at what we've got here and what we've got for 1.9. I had some success over the weekend building my environment on yet another machine. I've got some changes I want to push for the build file and the traincraft class. My question is this, how are you guys handling the situation where an entire paradigm has changed? e.g. ITickHandler

**Comment by EternalBlueFlame** [comment]
Hey, better late than never. I'm frigging ecstatic to see any help at all.
Right now, for the tick stuff, we are trying to move it all partially over to forge subscribe where we can.
this link has a good way for compensating where forge subscribe doesn't quite work, which has also been used.
http://www.minecraftforum.net/forums/mapping-and-modding/mapping-and-modding-tutorials/1571567-forge-1-6-4-1-8-eventhandler-and

the system where the entire networking has changed, i made the replacement packet class, but it has not gone far past that..... The networking's current state is out of my league here.

Now if I can be fully honest here, as long as it works, I really don't care at this stage. Because we can't really test new/better methods till it's actually working in the first place.

I also try to leave detailed comments on my changes with the push comments, so you get a generally good idea what we're doing without having to read all the code, I hope that will be helpful to a degree with getting caught up.

Also, when you go to push, if it's for the 1.7 port, be sure to upload it to the 1.7 branch, it would be very bad to try and push stuff for this to the main 1.9 branch, haha. (I'm probably over-explaining, sorry)

**Comment by EternalBlueFlame** [comment]
@morphicschris and @ejelinek I have made a group chat thing for the project, might be better than using this forum-esk thing.
[https://discord.gg/0zzHVjy4UIrSyExM](https://discord.gg/0zzHVjy4UIrSyExM)
Let me know your thoughts.
Theres channels on it for the 1.9 project as well, which I will leave to catnizp's digression.

**Comment by Cronosus** [comment]
nice you try it rewrite.
i have today little idea: are you planning for future compatibility with Zora no Densha?
nice mod too.

**Comment by EternalBlueFlame** [comment]
it is planned, we are even working with the dev from Zora no Densha.
