### ISSUE TITLE
crashes without buildcraft.

### ISSUE THREAD

**Issue by JrdBrd** [EternalBlueFlame/Traincraft-5#100]
I don't know if anyone else is getting this, but whenever I sprint with the mod installed it crashes ans gives me an error that mentions that the wrench from Buildcraft API can not be found.

[Crash Error](https://github.com/EternalBlueFlame/Traincraft-5/files/431550/crashlog.txt)

**Comment by JrdBrd** [comment]
Never mind, it seems like the issue is not with sprinting, but just with random crashes I guess.

**Comment by EternalBlueFlame** [comment]
still errors with the wrench and not having buildcraft. thought this was fixed dangit.

**Comment by MggMuggins** [comment]
Happened to me when I tried to right-click a rail. Probably not helpful, but a fix would be nice.

**Comment by JrdBrd** [comment]
I do believe i found the issue, it exists on line 134 of train/common/blocks/BlockTCRail.java, the code is as such:

`if (player != null && player.inventory != null && player.inventory.getCurrentItem() != null && (player.inventory.getCurrentItem().getItem() instanceof IToolWrench) && ((TileTCRail) te).getType() != null && ((TileTCRail) te).getType().equals(ItemTCRail.TrackTypes.SMALL_STRAIGHT.getLabel())) {

And the code references some sort of wrench that i'm guessing does not exist. I'm no coding expert, but I think I know enough to figure this one out.`

**Comment by 31trainman** [comment]
That looks to be registering any wrench it can find but I could be wrong.

**Comment by EternalBlueFlame** [comment]
"instanceof IToolWrench"
WHY DID I KEEP MISSING THIS????????????

**Comment by Elik39** [comment]
MggMuggins the same thing with me I can't place a train without it crashing.
