### ISSUE TITLE
Old TC issue thread

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#101]
lehjr brought this page up in the forum, I want to copy it here for future reference, will be good to use for double checking bugs and for a list of new features.
[https://bitbucket.org/spitfire4466/traincraft/issues?status=new&status=open](https://bitbucket.org/spitfire4466/traincraft/issues?status=new&status=open)
//EDIT, changed link to open issues, to narrow the list significantly.

**Comment by MarkenJaden** [comment]
Please! Do not fix these bugs! All people want to play Traincraft and want to update their TC Servers! Please release Traincraft!

**Comment by NitroxydeX** [comment]
This one still happens: https://bitbucket.org/spitfire4466/traincraft/issues/109/tc-420-server-track-switches-buggy
Happens only to the first Train that passes it.

**Comment by EternalBlueFlame** [comment]
@NitroxydeX that issue is likely due to the train not setting it back when passing it, should be a generally easy fix if we find where it switches it in the first place.

**Comment by 31trainman** [comment]
Does this guy have a screw loose or something? Leaving unfixed bugs in causes stuff to break then players yell at the mod authors etc saying you broke my world when in reality it's the players fault for rushing the mod authors to release. Just be patient and wait till the mod is stable.

**Comment by EternalBlueFlame** [comment]
it seems all these issues have been fixed already, aside from the one you mentioned nitro.
