### ISSUE TITLE
Slope speed limit 

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#103]
Speeds on TC slope is limited to 64km/h due to some sort of mathematical glitch where, randomly, speeds above 64 will either fully reverse the train's movement, or stop it completely, without derailing.

The bug has been masked since 1.6.4 so it's at least useable, but should be tended to eventually.

**Comment by MggMuggins** [comment]
All of the agreement here. What would be the reason for the mathematical glitch (is it possible to find out)?

**Comment by NitroxydeX** [comment]
@MggMuggins It should be possible to find out ^^

**Comment by NitroxydeX** [comment]
This bug is likely caused by EntityRollingStock

**Comment by FirEmerald** [comment]
I think the easiest possible fix can be found by looking at how the player can walk up stairs, and implementing a similar system on the trains, since this is likely caused by the train 'hitting' the collision box of the slope rail.

**Comment by NitroxydeX** [comment]
@FirEmerald well. This Bug is only caused by our EntityRollingStock API. The bogies don't make problems. ^^

**Comment by FirEmerald** [comment]
@NitroxydeX and what do you mean by that? I don't know the exact difference between a Bogie and the RollingStock itself

**Comment by EternalBlueFlame** [comment]
@FirEmerald i already tested the hitboxes, it seems like a hitbox issue, I agree that far.... But nothing is actually colliding, and if it was a hitbox issue the bogies would have it too since they keep the same Y offset, not just the EntityRollingstock base...
I wanna say it's something with rail detection, but I can't be sure.

**Comment by NitroxydeX** [comment]
Yes. And to add this: Bogie and RollingStock using the same code to move on the Slopes. Thats the weird thing. But something seems to forces the RollingStock to stop

**Comment by FirEmerald** [comment]
@EternalBlueFlame @NitroxydeX are they the same size length-wise? if not that's whats probably killing it

**Comment by EternalBlueFlame** [comment]
@NitroxydeX actually it is slightly different, bogie code is more optimized, but I tried carrying it from one to the other, and the reverse, but that fixed nothing.

@FirEmerald yeah the sizes are the same.

**Comment by EternalBlueFlame** [comment]
Another thing as well is if it was a collision it would derail at least partially. and it does not...

**Comment by FirEmerald** [comment]
I don't think it would derail being a straight-on collision (no sideways momentum whatsoever)

**Comment by FirEmerald** [comment]
why don't you look at write accesses to motionX?

**Comment by FirEmerald** [comment]
also might I ask what is an example of a Bogie?

**Comment by EternalBlueFlame** [comment]
No, there's code to derail with straight on collisions. We've had to rework it numerious times.

Also traced write access to MotionX, even did live debug printouts, nothing was incorrect... There seems to be something that just ends up being 0 somewhere, and it only happens when moving at speeds over 64, mind you the speed of 72 is a block.

Also if you look at Locomotive.java's variables you'd quickly find EntityBogie.

**Comment by FirEmerald** [comment]
I asked for what an example of a bogie is, not where to find one. I'm not exactly running modern hardware here, it takes a little while to download & open files. and I have trouble moving around git sources.

**Comment by EternalBlueFlame** [comment]
its the not back hitbox of a train.

**Comment by FirEmerald** [comment]
I'm trying a fix out now, but I need to get 1614 forge? do I REALLY need that high of a version to run this?

**Comment by NitroxydeX** [comment]
@FirEmerald we are developing with it and it's a requirement later. so yeah. you need it ^^

**Comment by FirEmerald** [comment]
what's different in 1614 vs 1558 that you require?

**Comment by EternalBlueFlame** [comment]
1.7.10 forge is basically done with, so the latest version is the best because it's likely the last, or close enough. It's not good to use outdated API's, glitches and security holes are prone to happen.

Not to mention when coding, if everyone is on different versions, API calls could be different, which will create errors that don't actually exist.

**Comment by FirEmerald** [comment]
I prefer 1558 as its stated as recommended, I think it still works in this version. You should probably back-test with 1558 just to see if it will work before release, instead of outright forcing people to use 1614.

**Comment by FirEmerald** [comment]
Also I can't seem to open the inventory of the high-speed zero edition train

**Comment by FirEmerald** [comment]
yeah the keybind is ignored

**Comment by FirEmerald** [comment]
always uses 'R'

**Comment by FirEmerald** [comment]
Also I cannot power it with a RF battery or IC2 battery

**Comment by FirEmerald** [comment]
will post that as an actual issue later

**Comment by NitroxydeX** [comment]
@FirEmerald well yes. WE REMOVED IC2 Support. :D

**Comment by NitroxydeX** [comment]
@FirEmerald since you are not reading anything or watching for hints: READ IT http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287038-traincraft-4-2-1?page=168#c3463

**Comment by FirEmerald** [comment]
but the RF source did not work. That was the issue. I didn't mean to put the IC2 part in there, sorry.

**Comment by NitroxydeX** [comment]
@FirEmerald yeah it's because I think we didn't added support for any RF source yet in the electric locos

**Comment by EternalBlueFlame** [comment]
IC2 support was removed because for one their API is trash, and for two, even they plan to move to RF in 1.9.

Powering the electric locomotive with an RF source however, try redstone dust. that's the only implemented item for powering it since IC2 managed the rest.

Also, i thought the inventory was always the R key...? you can change it in the config. like every other mod.

**Comment by FirEmerald** [comment]
I did change it in the config; However, it did NOT affect which key I needed to press. As for RF items, IEnergyContainerItem anyone? it's what I used.

**Comment by FirEmerald** [comment]
Sorry if I seema bit rude right now, I found out I'm not working tomorrow and with only getting 8 hours a week right now that's a big deal

**Comment by FirEmerald** [comment]
Ok so I managed to get above 64 on the slope, but it still kept banging it down to 64 despite the removal of
if (Math.abs(motionX) > 0.3) {motionX = Math.copySign(0.3, motionX);}
if (Math.abs(motionZ) > 0.3) {motionZ = Math.copySign(0.3, motionZ);}
is there another place I need to comment out?

**Comment by EternalBlueFlame** [comment]
Interesting, that is an issue to look into. There might be something with the control variables not being used from config....
You are compiling it with the correct version of forge right? if not that could cause some issues.

As for IEnergyContainerItem, that is not now, nor was it ever how the code was designed, that part would need a total redesign because its built to check items specifically, not containers.
I do agree that would be the best option though.

The part you mentioned was correct but you have to do it in bogies and the rollingstock.

**Comment by FirEmerald** [comment]
IEnergyContainerItem IS implemented on an item. I can add it if you want. As for the keybindings, I can also help with that as my removed port had no issues there.

**Comment by NitroxydeX** [comment]
@FirEmerald we have no issues with keybinding?! :D

**Comment by FirEmerald** [comment]
You obviously do have an issue with keybinding if the keybind for 'inventory' does not affect the key you press to open the inventory

**Comment by EternalBlueFlame** [comment]
No, i mean its not implemented in the slot manager of the electric locomotive. At least not as far as I know.
You can add it in if you like.

**Comment by EternalBlueFlame** [comment]
gonna test the keybind issue myself... im curious..
//EDIT: yeah, the keybind setting in the config isn't carrying over into the actual game... likely an event handler issue.

**Comment by FirEmerald** [comment]
I may have fixed the slope issue, one last test to run.

**Comment by FirEmerald** [comment]
it will have a slight downside.

**Comment by EternalBlueFlame** [comment]
which would be?

**Comment by FirEmerald** [comment]
I don't think it works quite yet
the downside is it might make the train go over blocks while going up slopes
I think that's a fair tradeoff.

**Comment by FirEmerald** [comment]
my main issue right now is it still stops when the back wheels are about to leave the slope going up or enter the slope going down.

**Comment by EternalBlueFlame** [comment]
that's always been the issue, it can climb just fine but stalls or reverses at the end, that's why it was limited to 64 in the first place. Nitro seems to have almost fixed it as of a few moments ago.

**Comment by FirEmerald** [comment]
well thats odd
the original traincraft, if you disabled the speed limit on slopes, randomly stops anywhere on the slope, not just the top.

**Comment by FirEmerald** [comment]
also, good job nitro

**Comment by FirEmerald** [comment]
yeah my fix doesn't actually do anything :|

**Comment by FirEmerald** [comment]
on to adding RF support to electric trains

**Comment by NitroxydeX** [comment]
Closed via cd532817ab7e4885a3246922342daecad217bb7e
