### ISSUE TITLE
Distill GUI not rendering Amount of Liquid correct & Can't Input/Output on any Sides

### ISSUE THREAD

**Issue by NitroxydeX** [EternalBlueFlame/Traincraft-5#106]
Everythings mentioned in the Title.

This one is for @canitzp

**Comment by NitroxydeX** [comment]
Distill Gui still buggy. @canitzp.

**Comment by canitzp** [comment]
i have tested it. what is wrong?

**Comment by NitroxydeX** [comment]
@canitzp the scala for diesel is always filled.

**Comment by canitzp** [comment]
If you mean the tank display, it's working fine for me

**Comment by NitroxydeX** [comment]
You need to open the Gui Once again otherwise it's not get updated. Well. Was like this in 1.6 too

**Comment by canitzp** [comment]
i fixed exactly this problem with my pull request
