### ISSUE TITLE
[Suggestion with code] RF items for electric train

### ISSUE THREAD

**Issue by FirEmerald** [EternalBlueFlame/Traincraft-5#109]
also, how do I submit the file(s) after adding this to my downloaded source files?

**Comment by NitroxydeX** [comment]
Well. If you know how to use github you should be able to submit it :D
RF-API is already in the code. just fork this git clone to your IDE and do the changes. push to your fork and submit pull request.

**Comment by FirEmerald** [comment]
The problem is I don't know how to use github, only stuff I've done on here is upload a couple source repositories and make some comments and stuff. I don't know how to fork or submit a pull request. I'll go look that up.

**Comment by FirEmerald** [comment]
Also it's only one file. Can I fork just the one file?

**Comment by EternalBlueFlame** [comment]
I think he more so means using RF containers with the electric loco in place of/alongside redstone.

also you gotta make a private fork of the project, make your changes to it, then do a pull request to this branch.
Remember you can google this stuff.

**Comment by NitroxydeX** [comment]
Top right of this git here is a "fork" button. This clones the WHOLE git to your user account. This you need to import in your IDE. Do your changes, commit them to your fork and then hit "Pull Request" on your Fork - directly under the commits-display near to the branch-choice.

**Comment by FirEmerald** [comment]
I did say I was going to look it up, just wanted to be sure I could just do a one-file fork before going throught the trouble of re-downloading all the files after the commit

**Comment by FirEmerald** [comment]
Okay I submitted the request.
