### ISSUE TITLE
Config only half works

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#111]
This was mentioned by FirEmerald but I can confirm, changing key used in config does not actually change key used in game. Inventory (R) as an example.

**Comment by lehjr** [comment]
Looks like there are places where hard coded values for keys are being used instead of variables. For instance: https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/Locomotive.java#L337-L369

**Comment by NitroxydeX** [comment]
The whole thing is outdated. This needs a total rewrite for keys

**Comment by lehjr** [comment]
This is what Modular Powersuits uses for the normal keybinding (the odd GUI style keybinding is something I'll probably get rid of in 1.10.2): https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/scala/net/machinemuse/powersuits/control/KeybindKeyHandler.java

**Comment by FirEmerald** [comment]
I have fixed this issue, once the fork is merged this can be closed.
