### ISSUE TITLE
Texture for TrainCraft / Navrch textur pro TrainCraft

### ISSUE THREAD

**Issue by Kofola45cz** [EternalBlueFlame/Traincraft-5#128]
Ahoj/Hello
Vím ze mnoho váš má rad TrainCraft a tak mě napadlo udělat par novich bloku pro TrainCraft.
Pochopim když nektere se vám nebudou líbyt.
Udělal jsem:
- mozna lepší Petruelum ktery by zapadly líp mezi stone
  (takže v jeskyni byto mohlo vypadat lip a nebylo to jak jíny blok ktery vypada jako kdyby tam nepatříl)
  Brown Coal - takže Hněde Uhlí - ktery co já vím u nekterych Locomotiv se používalo a tak jsem vytvoříl Brown Coal pro Traincraft.
  Gravel Black / šterk černí - pokusil jsem se udělat ale zátym se natom pracuje šterk ktery už pod koleji dlouho leži a ktery je řeba špínavy od Disel nafty.
  Redstone Lamp ruzní barev podle semaforu - někdy se snát muze hodit do zdi, nastrop, podlahu ... atd. proště aby bylo mozni je dát tam kam RailCraft semafory nejdou dát. (proště světelne upozornění)

Tito textury jsou ano nic moc ale jen sem se pokusil příspět a omlouvam se zato když tam budou pravopisné chybi, I am Can´t English.
-nevědel jsem kam tento navrch mám dát tak jsem ho dál jsem, takže pardon.

Obrazky/textury:
![brown coal block](https://cloud.githubusercontent.com/assets/22054484/18314997/ace76c50-7515-11e6-91d6-0cc77ad79607.png)
![brown coal ore](https://cloud.githubusercontent.com/assets/22054484/18314996/ace4a178-7515-11e6-9086-84b78ecb4746.png)
![brown coal](https://cloud.githubusercontent.com/assets/22054484/18314998/ace907cc-7515-11e6-988e-e4e956c985c6.png)
![gravel black](https://cloud.githubusercontent.com/assets/22054484/18314995/ace36506-7515-11e6-84e5-6640a5de58a8.png)
![oranselampoff](https://cloud.githubusercontent.com/assets/22054484/18314999/acf006f8-7515-11e6-8807-e852fb8e5af0.png)
![oranselampon](https://cloud.githubusercontent.com/assets/22054484/18315003/ad1495ae-7515-11e6-8126-f210ba74c77e.png)
![petruelum](https://cloud.githubusercontent.com/assets/22054484/18315004/ad15837e-7515-11e6-8bd5-f76b8cc0fd97.png)
![startlampoff](https://cloud.githubusercontent.com/assets/22054484/18315001/ad0529ac-7515-11e6-998f-98d0f1dc43dc.png)
![startlampon](https://cloud.githubusercontent.com/assets/22054484/18315005/ad184258-7515-11e6-8aeb-148aa0424933.png)
![stoplampoff](https://cloud.githubusercontent.com/assets/22054484/18315000/ad03de12-7515-11e6-8843-8e3c5c92da45.png)
![stoplampon](https://cloud.githubusercontent.com/assets/22054484/18315002/ad0eeece-7515-11e6-8b88-85cd62b9c41f.png)
![yelowlampoff](https://cloud.githubusercontent.com/assets/22054484/18315007/ad4324b4-7515-11e6-9452-fbf54e1584bf.png)
![yelowlampon](https://cloud.githubusercontent.com/assets/22054484/18315006/ad38b592-7515-11e6-95cc-9b170a9d90e5.png)

**Comment by Cronosus** [comment]
Translate:
I know many of you like traincraft, then i have an idea to create some new blocks for Traincraft.
I will understand if you do not like some of them.
i create:
- maybe better Petroleum which fit better between stone (in caves may looks better and not like another one block which not belongs here).
- brown coal - which as i know, was used on some Loco and then i create Brown Coal for Traincraft.
- Black Gravel -  i tried to make but i am still working on it. Gravel which is old and which is filthy from Diesel etc.
- redstone Lamp of some colors of traffic light - sometime can be used to walls, ceilings, or floor... etc..  just to be possible place them to places where cannot be placed traffic lights. (just lightning notice)

these textures are not good, but i just tried to contribute and sorry for misspellings. i not speech English
-i don't know where i can post this suggestion, then i post it here, sorry.

//ETERNAL EDIT: fixed the bullet points and added some transitions to make it easier to read.

**Comment by Kofola45cz** [comment]
ok Cron

2016-09-07 17:10 GMT+02:00 CronosusCZ <notifications@github.com>:
