### ISSUE TITLE
Grain Hopper is uncraftable!

### ISSUE THREAD

**Issue by MacTirom** [EternalBlueFlame/Traincraft-5#130]
The Waggon Grain Hopper can not be craft!

No crafting recipe and nothing in the TC Guide book.

You can only get this waggon in creative mode or with NotEnoughitems...

**Comment by amerem3** [comment]
Fixed

**Comment by EternalBlueFlame** [comment]
should be fixed as of [https://github.com/EternalBlueFlame/Traincraft-5/commit/e22ad575426e3ee4ee1a4547cf66a51cb7c008ed](https://github.com/EternalBlueFlame/Traincraft-5/commit/e22ad575426e3ee4ee1a4547cf66a51cb7c008ed)
