### ISSUE TITLE
Player Placement In Engines on New Track

### ISSUE THREAD

**Issue by MggMuggins** [EternalBlueFlame/Traincraft-5#133]
This is a persisting bug that has occurred since I first played TC (1.6.4) that has not been fixed yet. These screenshots were taken with the new Release.
Basically, the player position in engines on new tracks is too high. The positions were coded for Vanilla track, and hasn't been adjusted for the new TC track. Here are some pics:
SD40 sitting on Vanilla track. This is the most pronounced case, but the bug holds true for all engines. Some aren't easily noticeable.
![old](https://cloud.githubusercontent.com/assets/16041213/18333098/c303636a-7531-11e6-827b-355fa70886a8.png)
SD40 sitting on TC track. It is incredibly difficult to see.
![new](https://cloud.githubusercontent.com/assets/16041213/18333123/f6d3dcd8-7531-11e6-829e-ac6a91b8d8d8.png)

**Comment by NitroxydeX** [comment]
Well the offset is not made for vanilla tracks. It's just random false.. if we reduce it you are too low on vanilla tracks. we need to redo offset for vanilla tracks first. HS Loco is fine on TC Rails but not on Vanilla

**Comment by MggMuggins** [comment]
Would that be possible?

**Comment by EternalBlueFlame** [comment]
It would be possible, we would need to change the riderOffset Override dependent on if you are on normal rails or TC rails. The extra work is that the offsets tend to be different depending on the train, so we'll have to make compensations dependent on the train, or rework the calculation on every individual train (and potentially rollingstock), as an example, like nitro said, the high speed train has different offsets from most others.

//EDIT: after some correction to my thought from Nitro, it may be easier to just change the base Y-offsets directly, assuming that doesn't end up breaking things.

**Comment by NitroxydeX** [comment]
To really get this to a good state we need to redo half of the things we do for our and Vanilla rails. The Hitbox heights are different for both rails.

**Comment by NitroxydeX** [comment]
I fixed this now in 76c7733bf7abfd947eb84f735abcbc2e5ea0dc34 

MC-Rails and TC Rails have now the same height so there isn't this annoying going up/down when changing between MC and TC Rails anymore. I changed the seat-positions for Trains where it was needed too.
