### ISSUE TITLE
Refueling Diesel Engines only uses half Fuel

### ISSUE THREAD

**Issue by MggMuggins** [EternalBlueFlame/Traincraft-5#134]
Or something like that. I'm not sure what exactly is going on with this bug, but when refueling diesel engines (I think they all behave like this, could use more testing), the train consumes twice as many gas cans as it uses. The following image was taken in an SD70 in the latest release.
![a few missing](https://cloud.githubusercontent.com/assets/16041213/18333185/8206b4ec-7532-11e6-907b-bb53def45dc4.png)
18+23 doesn't make 64, does it? I started with a stack of 64 full cans, and after fueling, this was the result.
Also, sorry about multiple issues, but you know how it goes.

**Comment by amerem3** [comment]
did you have the engine running while fueling it?

**Comment by MggMuggins** [comment]
Hmm, I don't remember. I think it does it regardless, but let me check. I'll test all the deisels while I'm at it.

**Comment by amerem3** [comment]
ok that would really help us out

**Comment by MggMuggins** [comment]
It does it on all Diesel Locomotives regardless of whether or not the Engine is running. All of the parking brakes were off.

**Comment by amerem3** [comment]
ok thanks we are looking into it
