### ISSUE TITLE
placing ore carts on small stright tracks causes world corruption 

### ISSUE THREAD

**Issue by infinus5** [EternalBlueFlame/Traincraft-5#135]
[crash report.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/460630/crash.report.txt)

like the title says, when placed on small straight tracks game crashes

**Comment by amerem3** [comment]
there is no ore cart what is the one you are trying to place?

**Comment by EternalBlueFlame** [comment]
`java.lang.NoSuchMethodError: mods.railcraft.api.tracks.RailTools.isRailBlockAt(Lnet/minecraft/world/IBlockAccess;III)Z
    at train.common.api.EntityRollingStock.func_70071_h_(EntityRollingStock.java:885)
    at train.common.api.Freight.func_70071_h_(Freight.java:135)`

Strange error, this shouldn't happen under any circumstance since this function should be fine client and server side... Yet the result is that the function does not exist, are you absolutely certain there is no outside modification? Like a conflicting mod? Or did you try to compile it yourself?

Also, what cart exactly do you refer to?

**Comment by Czarified** [comment]
From the stacktrace:
`-- Entity being ticked --
Details:
    Entity Type: tc.Freight Minecart Yellow (train.common.entity.rollingStock.EntityFreightMinetrain)
    Entity ID: 145557
    Entity Name: freightMinetrain
    Entity's Exact location: -39.50, 12.15, -960.50
    Entity's Block location: World: (-40,12,-961), Chunk: (at 8,0,15 in -3,-61; contains blocks -48,0,-976 to -33,255,-961), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
    Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)`

So I would guess that's the yellow minecart to match the yellow electric mining locomotive, no?

**Comment by amerem3** [comment]
These carts don't cause crashes on the small straight track for me

**Comment by lehjr** [comment]
As far as I can tell, the issue in the first comment is an API mismatch issue. Traincraft is using version RC API 2.3.0 where `mods.railcraft.api.tracks.RailTools.isRailBlockAt` is finally added, but Railcraft doesn't use that version until 9.11.0.0. So I would set that as a minimum version.

**Comment by infinus5** [comment]
sorry it took so long to get back to you guys, when I did my install I used a copy of one of my modpacks by mistake thinking it was a fresh install. When I placed the yellow ore cart (the little one meant to be used with the cart hauler the game crashed and the world became completely corrupted. I cant even get the world to open in MCedit. I believe Railcraft might have something to do with it but I am not a programmer and can only just understand what crash reports are talking about. sorry if this is no help.

**Comment by lehjr** [comment]
@infinus5 the original bug report was showing a crash related to your Railcraft version being outdated and incompatible. Have you tried updating your Railcraft version to at least 9.11.0.0? You might be able to open the world that way in Minecraft itself.

**Comment by NitroxydeX** [comment]
We removed this Railcraft-API dependency. We can do this check on our own API too. Fixed with fc1e00576196339a05af34a5fdcae54a381bd3c3
