### ISSUE TITLE
TrainCraft - bug, train and wagon?

### ISSUE THREAD

**Issue by Kofola45cz** [EternalBlueFlame/Traincraft-5#143]
Czech:
Jak viditě v čtverci 1. takle vypada vlak a vagon když jsou na kolejich, vlak má dvá ,,hitboxe,, ale vagon má jeden ,,hitbox,, - co má pak příčínu tu ze se muzou do sebe bugnout, jak je ukazano v 2.
Tender ktery je máli, má taky jen jeden ,,hitbox,, a nebuguje se (ukazano ve 3.)
Tak mě napadlo, ti vagony ktery jsou velky jak vlak jestlý by nešlo udělat jím dva ,,hitboxy,,?
(I am English, I am Czech, Přeloženo v Google Překladači)

English:
How do you see the first square Takle looks train and wagon when they are on rails, the train has two ,,HITBOX,, but the wagon has one ,,Hitbox,, - what are the causes that they can do themselves bugnout as shown in second
Tender Mali who has also only one ,,Hitbox,, and the nebuguje (shown in 3.)
So I thought, those cars that are large as the train if he could not make it two ,,HITBOX,,?
(I am can´t English, I am Czech, translated in Google Translate)

Link Foto: https://cloud.githubusercontent.com/assets/22054484/18393629/77e9f61a-76b6-11e6-84b9-ef075aa3ee26.png

**Comment by NitroxydeX** [comment]
@Kofola45cz it's because we don't push away other carts when they hit the Train-Hitboxes. But we need two hitboxes to make a turn look good when going over turns. That's why ALL Trains got two hitboxes. Some of the Trains had 3,4,5,6 hitboxes which was not really good.
