### ISSUE TITLE
Cauldron 1.7.10

### ISSUE THREAD

**Issue by Untold-StoryTV** [EternalBlueFlame/Traincraft-5#144]
## Its not working on my Cauldron 1.7.10 Server

Missing Mods:
##         Forge : [10.13.4.1614,)

Really sad story.

**Comment by MggMuggins** [comment]
Update your forge to that version then. Also don't expect Cauldron to work with this or any forge mod either. At least not smoothly.

**Comment by NitroxydeX** [comment]
This is not our problem. Use a real Forge-Server instead. Cauldron is highly not supported. Don't expect other ports like CKauldron/Thermos to work too with our Mod. Use them on your own risk.

**Comment by EternalBlueFlame** [comment]
"Missing Mods:
Forge : [10.13.4.1614,)"

Literally telling you that you need to update your cauldron to a version that uses forge 10.13.4.1614.
I can't facepalm hard enough.

Also, what @NitroxydeX said, even with the correct version, there's a lot of bugs on it that will not appear on real forge.

**Comment by Untold-StoryTV** [comment]
I switched to KCauldron on same day and solved the problem. I thought that Cauldron dont have a version which support "Forge : [10.13.4.1614,)". Now the mod works fine, don't found any bugs at the moment.
