### ISSUE TITLE
small error in build.gradle

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#145]
you need to add these 2 lines to build.gradle source so that Gradle will compile without a warning or error. 
sourceCompatibility = 1.8
targetCompatibility = 1.8

**Comment by EternalBlueFlame** [comment]
Actually this branch of TC uses java 7+, it may even work with 6. So that shouldn't be necessary.
The 1.10.2 may be a different story.
