### ISSUE TITLE
TrackBuilder placing & digging problems when going downwards

### ISSUE THREAD

**Issue by Quackers29** [EternalBlueFlame/Traincraft-5#156]
If a trackbuilder is told to go down to a certain level, once it reaches that level it misses out one block place. If it is air then the trackbuilder falls off the track.

This was tested on Traincraft-4.3.0_003, on a multiplayer server.

![2016-09-13_20 25 14](https://cloud.githubusercontent.com/assets/11053436/18488348/e05efd20-79f0-11e6-8375-de971c547b53.png)

![2016-09-13_20 25 23](https://cloud.githubusercontent.com/assets/11053436/18488353/e405bef0-79f0-11e6-8f1c-82cdc9bd3bca.png)

**Comment by Quackers29** [comment]
An improvement would also be to change the requested height (when spawning the track builder) to be the same as the current height. For some reason it is always 1 block higher then its current height (when spawned)

**Comment by Quackers29** [comment]
Further issues, when underground and told to decrease in height, the trackbuilder only manages 1 block decrease and then gets stuck:
![2016-09-13_20 45 06](https://cloud.githubusercontent.com/assets/11053436/18488864/2ac31796-79f3-11e6-866f-74929d6f17b7.png)
![2016-09-13_20 45 28](https://cloud.githubusercontent.com/assets/11053436/18488877/343d3b80-79f3-11e6-927d-99ceeef19f2a.png)

**Comment by EternalBlueFlame** [comment]
T̶h̶i̶s̶ ̶3̶r̶d̶ ̶i̶s̶s̶u̶e̶ ̶i̶s̶ ̶r̶e̶l̶a̶t̶e̶d̶ ̶t̶o̶ ̶y̶o̶u̶r̶ ̶f̶i̶r̶s̶t̶ ̶i̶s̶s̶u̶e̶ ̶i̶n̶ ̶t̶h̶e̶ ̶t̶h̶r̶e̶a̶d̶,̶ ̶a̶c̶t̶u̶a̶l̶l̶y̶ ̶i̶t̶ ̶I̶S̶ ̶t̶h̶e̶ ̶f̶i̶r̶s̶t̶ ̶i̶s̶s̶u̶e̶.̶
I stand corrected by Nitro once again, its a combination of the first issue and a hitbox issue.

**Comment by NitroxydeX** [comment]
- [x] Fixed wrong placement of blocks
- [x] Fixed PlannedHeight when placing TrackBuilder
- [x] Fixed Cart stuck in tunnel (easy)
- [x] Fixed Cart remove wrong blocks when going downwards in tunnel
