### ISSUE TITLE
Buggy Slopes

### ISSUE THREAD

**Issue by Minecarftmano9** [EternalBlueFlame/Traincraft-5#157]
I have no knowledge of coding or how anything works so I'm gonna try to explain this as best as i can.  So I was testing stuff out on single player and found a few bugs with the slopes.  

1.When you're going up any of the slopes on the last few blocks towards the top you level out.  Like you will go flat even though your supposed to be going up. (i tested this on all the slopes facing all directions)
http://imgur.com/a/bOY4n
2.When switching between the medium slope and the small slope you will get stuck. It is weird though because, it will happen on the second slope after the change of slope so like this.  Some times you will even bounce backwards if your going up it at any speed!  Most likely because you hit the block. (Also keep in mind i made a big hill using all the slopes when this happened but they only got stuck on the 1x6 slope)  http://imgur.com/a/32M1U
If any more info is needed message me back i can also get more screen shots if needed! :)

~Mano

**Comment by EternalBlueFlame** [comment]
1. Can't be fixed due to design.
2. I believe was dealt with already in revision 4 which isn't ready for release quite yet. Nitro would know more on this one.

**Comment by NitroxydeX** [comment]
This is something we save for the rewrite. The way we detect the Positions on slopes is not really good atm. We need to change the whole system to get rid of these funny bugs.

**Comment by Minecarftmano9** [comment]
Ah ok i under stand, but my problem is not really with the dipping into the slope its when the train/ train cars hit the block under it and bounce back at a high speed. This has only happened with the 1x6 slope so far but i haven't tested it fully to know for sure. Thank you for the time for reading my post I wish you guys good luck with the rewrite!  :) ~Mano
