### ISSUE TITLE
 Minidump error with TC 003

### ISSUE THREAD

**Issue by detjensrobert** [EternalBlueFlame/Traincraft-5#161]
Straight forge works, but adding TC causes a minidump error everytime I try to launch. No other mods are running, just Forge and TC-003.

Pastebin of error file: http://pastebin.com/W6hiwkbg

Thanks
-Bagels
(is this the correct spot to post errors or is the forum thread better?)

**Comment by MggMuggins** [comment]
I sometimes get a similar error on Linux, but I don't think I've had it happen with TC or nearly this frequently. Probably a different problem.

**Comment by EternalBlueFlame** [comment]
This seems to be some sort of permissions issue, as if the OS isn't allowing java to access your D drive, maybe try lowering UAC restrictions or running it as admin, that may fix the issue.

It's very unlikely this is a TC specific issue, let us know if you find anything else out.

and yes, this would be the correct spot for posting errors.
