### ISSUE TITLE
Diesel/Refined Fuel energy output in Buildcraft Combustion engine.

### ISSUE THREAD

**Issue by achman741** [EternalBlueFlame/Traincraft-5#164]
The energy output of Diesel and Refined fuel in a combustion engine is 3 RT/t and 6 RF/t respectively, shouldn't it be 30 RF/t and 60 RF/t, based on what I remember in old traincraft it output energy in  MJ not RF and 1 MJ is equal to 10 RF, so shouldn't the energy output be higher?

**Comment by NitroxydeX** [comment]
Yes. You're absolutely right. This is our mistake. We just ported the old values and never thought about that Buildcraft changed from its MJ to RF. Thanks for the hint!
