### ISSUE TITLE
Crash on load with Traincraft and Railcraft (Bevo Tech Pack)

### ISSUE THREAD

**Issue by TheDeinonychus** [EternalBlueFlame/Traincraft-5#165]
When trying to add Traincraft to my copy of the Bevo Tech Pack, Minecraft would always crash when trying to load the mods. 
I posted my crash log to the BTP forums, and one of their staff members told me it was an issue with Traincraft, and that is was a problem the mod authors should be told about. 
Here is a pastebin of my most recent crash log. Hopefully you can fix the issue soon. 
http://pastebin.com/3E6wbbxm

**Comment by NitroxydeX** [comment]
Hey @TheDeinonychus can you tell us what you did that this crash happend?

**Comment by TheDeinonychus** [comment]
Downloaded the latest version of Traincraft (tried with all three versions of 4.3.0), dropped the file into the Mods folder, launched Mincraft, and then it crashed during the loading process. Nothing more to it than that, didn't even get to the title menu. Didn't mess with any of the pack's other mods or settings.

**Comment by NitroxydeX** [comment]
Which version of BTP you are using?

**Comment by canitzp** [comment]
can you ask if BTP changes anything with railcraft or their configs?

**Comment by TheDeinonychus** [comment]
I'm using Bevo Tech Pack Reborn release 1.0
I'll ask if Bevo changes anything with railcraft or it's configs, and get back to you soon as I know something.

**Comment by NitroxydeX** [comment]
I've tested the pack myself. Traincraft loads fine in it. Please make sure to clear your environment before upgrading from an old BTP version

**Comment by TheDeinonychus** [comment]
Please define 'clear your environment' I didn't upgrade from an old BTP version, so I wouldn't think it would be any lingering mods or configs from a previous version.

**Comment by NitroxydeX** [comment]
then I don't know. It worked fine for me.

**Comment by TheDeinonychus** [comment]
Ok, if I was paranoid, I'd think someone was screwing with me. Created a new instance of BTP, completely untouched, didn't launch the game yet. Dropped the Traincraft file into the mod folder, and it loaded fine. 
Unless Traincraft just doesn't play well with being added to a mod pack after first run, I've no idea what would be different from the two installs.

**Comment by NitroxydeX** [comment]
Traincraft works fine when adding it later. It was like that some Railcraft-Parts weren't loaded correct.

**Comment by NitroxydeX** [comment]
@TheDeinonychus could you report this to the Modpack authors? https://github.com/simeonradivoev/MatterOverdrive/issues/581

**Comment by TheDeinonychus** [comment]
Ok, after hammering at my configs and such for a few hours, I think I may have figured out what was causing it. I had gone in to the Railcraft config and re-enabled the vanilla rail recipes, which normally are disabled to force you to go through the long Railcraft process to create rails. Apparently that one change stops Traincraft from loading. My guess is that it's somehow dependent on the Railcraft rail recipe for something.

**Comment by NitroxydeX** [comment]
`track {
            # 
            # change to 'useAltRecipes=true' to use track recipes more similar to vanilla minecraft
            # 
            B:useAltRecipes=false
        }`

you mean this? This works fine.

**Comment by NitroxydeX** [comment]
I also saw your forum post. you can use Mekanism to convert EU to RF

**Comment by TheDeinonychus** [comment]
Apparently, something with BTP means it doesn't work. Loaded up the mod with a new install of BTP, works fine. But if I change that one setting in the Railcraft config, it won't load.

**Comment by NitroxydeX** [comment]
@TheDeinonychus so if you change the useAltRecipes to true it doesent work? That means it wouldn't work when you use Vanilla Recipes for rails correct?

**Comment by TheDeinonychus** [comment]
Er, ok, your wording confuses me a bit XD
By default, Railcart (at least in the BTP pack) has useAltRecipes set to false, disabling Vanilla track recipes. 
Setting useAltRecipes to true disables the Railcart recipes (using rails and railbeds) and re-enables Vanilla track recipes, but prevents Traincraft from loading. 
It /may/ have something to do with Mekanism also having a recipe for tracks using Osmium ingots instead of Iron like in Vanilla.

**Comment by NitroxydeX** [comment]
I fixed this error now. If we push version 004 you won't crash into this problem anymore but you won't be able to use our additional rails then.

Mekanism was just because you told in the Forums you added a mod for EU/RF changing. Mekanism Cables can do every energy form.

**Comment by NitroxydeX** [comment]
And please notify the modpack guys that we solved this problem.

**Comment by TheDeinonychus** [comment]
Cool. 
Yeah, I found out about Mekanism (and Immersive Engineering) automatically converting between EU and RF, however Mekanism still include it's own recipe for tracks regardless of it Vanilla recipes are enabled or not in Railcraft
