### ISSUE TITLE
Customize recipes?

### ISSUE THREAD

**Issue by Sir-Chi** [EternalBlueFlame/Traincraft-5#167]
Hey I was just wondering if there is any way to customize recipes (for example for the distill or the hearth furnace) and if not is it planned/coming in the future?

Thanks ^^

**Comment by NitroxydeX** [comment]
You can do it with MineTweaker. We don't have the ability in our configs. The recipes are good how they are.

**Comment by canitzp** [comment]
minetweaker won't work, cause we haven't mt integration

**Comment by Sir-Chi** [comment]
Ah okay it's cool. Thanks anyway :)

Is there any plans for mt integration?

**Comment by NitroxydeX** [comment]
Not at this time.

Which recipes are your referring to and why?

**Comment by Sir-Chi** [comment]
Okay, thanks. I'm just making a modpack and was wondering if it was possible if i could add some things to the distill.

**Comment by canitzp** [comment]
I opened a issue for the minetweaker integration in the master repo Traincraft/Traincraft#29

**Comment by Sir-Chi** [comment]
Thank you, much appreciated!
