### ISSUE TITLE
Interesting Things Happen when Trains leave chunk Loading Radius TC 003

### ISSUE THREAD

**Issue by MggMuggins** [EternalBlueFlame/Traincraft-5#168]
Some strange stuff happened when the trains left my chunk loading radius. I am running some other mods (LOTR, NEI, Fastcraft). Here are a few screens. The first I got away from the train, because it was slow enough. The second got away from me and seemed to collide with the chunk loading radius, and is now a stack of cars. It started as an engine, tender, and four cars. V60 and JNR respectively. Both engines seem to have been turned around.
![2016-09-20_17 10 21](https://cloud.githubusercontent.com/assets/16041213/18691276/64971674-7f58-11e6-81f2-d7e51439f88b.png)
![2016-09-20_17 26 24](https://cloud.githubusercontent.com/assets/16041213/18691283/6fb88952-7f58-11e6-994a-4d10bf4ba211.png)
~Samwise

**Comment by NitroxydeX** [comment]
The first seems to be a render issue and shouldn't happen like that because the rollingstock (carts, freights, and so on) do have their calculation point in the middle. maybe this is caused by something else.

The second thing is strange too. We fixed this bug long ago before we had our first release. I will look into this later. Any other things? Like using KCauldron or Thermos?

**Comment by MggMuggins** [comment]
No, it's a LOTR SP world. I can post a list of everything in my mods folder (that is relevant). I also forgot to mention that both of these trains were stopped as soon as they left my loading radius. It worked fine in 002.
*LOTR Mod 29.6
*Damage Indicators 3.2.3
*CodeChickenCore 1.0.4.29
*fastcraft 1.21
*lotrNEIAlpha 0.1.1
*NotEnoughItems 1.0.3.74
*TC 003
*worldeditForge  beta 1

**Comment by NitroxydeX** [comment]
Did you PUSHED the wagons instead of PULLING them?

**Comment by MggMuggins** [comment]
No, all of the trains were only pulling carts.

**Comment by NitroxydeX** [comment]
Strange thing. I will look into the changes from 002 to 003

**Comment by Larky2k** [comment]
The First pick iv had that happen when the Train is moving very very slowly but fixes it self when you speed up.

**Comment by EternalBlueFlame** [comment]
I've been going over this again recently, i tried every build from a few days before 002 to the 003 release, and it didn't work in any of them. perhaps I'm missing one? Anyone have any clues on that?
