### ISSUE TITLE
Locomotive interface issue

### ISSUE THREAD

**Issue by melindaendv** [EternalBlueFlame/Traincraft-5#169]
Ok I cannot access the locomotive interface via the "R" key..

Is there something I need to do or did something change?

**Comment by MggMuggins** [comment]
Is your config set for a different key? That setting actually works now...
Using any other mods?

**Comment by melindaendv** [comment]
I have other mods but none of them use the "R" key.. Immersive engineering, railcraft, thermal dynamics, buildcraft...
As far as I can tell there is nothing set to the "R" key and I am not 100% sure how to bind it..

**Comment by MggMuggins** [comment]
Could you do it in the Controls section of your menu? Just click the button, and press R.

**Comment by melindaendv** [comment]
Yeah I literally just had someone mention that to me DERP!, I had some other mod with a bound key tp "R" I changed it to a button om my extended gamepad thing and VOLA!, I can drive my trains now xD

The simplest things that get overlooked or forgotten about can sometime create the biggest headaches..

Thanks for your help anyways though..

One more thing, If I can create some livery textures for some locomotives could I submit them here somehow or how would I go about doing that..

Some back story: I actually work for a railroad here in the US and I run a pair of Garry's Mod trainbuild servers, needless to say I know railroading xD.

**Comment by MggMuggins** [comment]
If it isn't closed, there should be issues giving info on those things down the board a bit.

**Comment by melindaendv** [comment]
alright thank you. Also do you know if the devs are aware that the railcraft switching lever does not work with the traincraft switching tracks?

**Comment by canitzp** [comment]
they should work, cause they are emmiting a redstone signal and our switches a changing if they get an redstone signal. Can you show a picture where it don't work?

**Comment by NitroxydeX** [comment]
@melindaendv we are aware of this because it's kinda difficult to implement them.

@canitzp no they don't emmit anything. you need to call the state from the switch every tick.

@melindaendv If you wanna create textures just link them here: https://github.com/EternalBlueFlame/Traincraft-5/issues/58
