### ISSUE TITLE
HUD Scaling

### ISSUE THREAD

**Issue by Czarified** [EternalBlueFlame/Traincraft-5#172]
When playing on 3440x1440 with large GUI size, the locomotive HUD disappears. By resizing the window, you can find it, but by default it is hidden and I don't see any way to move it around.

Could the mod automatically detect the window resolution and place it accordingly? It seems to be putting it at a certain absolute position (without taking a look at the actual code, that is...).

![2016-09-23_20 52 20](https://cloud.githubusercontent.com/assets/6953018/18805317/abe65a8e-81cf-11e6-8df9-7006f7e3d4be.png)
![2016-09-23_20 52 13](https://cloud.githubusercontent.com/assets/6953018/18805319/af3296da-81cf-11e6-9122-686bb8e4ccf5.png)

**Comment by NitroxydeX** [comment]
Yeah I noticed this during many many test that we are best compatible with 16:9 resolutions. I will look into the code how we place the thing.
