### ISSUE TITLE
Floating non removable trains...

### ISSUE THREAD

**Issue by melindaendv** [EternalBlueFlame/Traincraft-5#174]
Here is an image of it

http://i213.photobucket.com/albums/cc110/Adriel_G/Adriel_G032/bughopper1_zpsudv3yhhl.jpg

This has happened a couple of times and I cannot remove them

**Comment by NitroxydeX** [comment]
Hit F3+B and show the hitbox. you can upload images directly here.

**Comment by melindaendv** [comment]
I found it was a clientside thing that required me to restart my game to clear up.

**Comment by NitroxydeX** [comment]
okay. it was just stucked render. already thought that.
