### ISSUE TITLE
Armor bar glitched while mounted

### ISSUE THREAD

**Issue by EzerArch** [EternalBlueFlame/Traincraft-5#176]
Outside. Pay attention to the armor point bar, above the hotbar on the left:
![2016-09-20_22 31 19](https://cloud.githubusercontent.com/assets/6743303/18813261/9a02423c-82ca-11e6-9b21-186813d7e133.png)

Inside. Now it's glitched:
![2016-09-20_22 31 08](https://cloud.githubusercontent.com/assets/6743303/18813262/9a044f50-82ca-11e6-93da-2a5f7295514e.png)

**Comment by EternalBlueFlame** [comment]
fixed as of [https://github.com/EternalBlueFlame/Traincraft-5/commit/e71fbb874107e5f5221ad2b8247cd84808b9bc7c](https://github.com/EternalBlueFlame/Traincraft-5/commit/e71fbb874107e5f5221ad2b8247cd84808b9bc7c)
