### ISSUE TITLE
Graphic Bug in the new Slopes 1x12 & 1x18

### ISSUE THREAD

**Issue by MacTirom** [EternalBlueFlame/Traincraft-5#177]
![2016-09-25_12 56 28](https://cloud.githubusercontent.com/assets/16389466/18814859/9381efde-831f-11e6-874f-535601d97fec.png)
![2016-09-25_12 56 18](https://cloud.githubusercontent.com/assets/16389466/18814860/938c16bc-831f-11e6-84e4-6da33932ae3b.png)
![2016-09-25_12 56 23](https://cloud.githubusercontent.com/assets/16389466/18814861/93925572-831f-11e6-8949-767b19971281.png)

**Comment by Cronosus** [comment]
hmm
first and second maybe.. but whats on the third screen?

**Comment by NitroxydeX** [comment]
@Cronosus I think the third screen shows the correct 1x6

**Comment by MacTirom** [comment]
The third is to show how it is normal.
