### ISSUE TITLE
Composite Suit looks grey when placed in Armor Stand from Bibliocraft

### ISSUE THREAD

**Issue by Apot98** [EternalBlueFlame/Traincraft-5#180]
![2016-09-26_15 23 30](https://cloud.githubusercontent.com/assets/20492252/18825925/569ad34a-83fd-11e6-8864-0d73feb3282c.png)
Putting Composite Suit into Armor Stand from Bibliocraft makes them lose their colors

**Comment by NitroxydeX** [comment]
It loads our default texture to overlay. I think Bibliocraft cant handle how we "dye" the suit.

**Comment by EternalBlueFlame** [comment]
yeah this is likely due to the way we handle dyes, the same issue would have occurred in 1.6, its unlikely support for this sort of thing was planned.
