### ISSUE TITLE
A few issues regarding the VL10

### ISSUE THREAD

**Issue by Lanthan64** [EternalBlueFlame/Traincraft-5#182]
Hi Everyone,

I did some test drives with the VL10 and stumbled across a few problems You might want to have a look at. All observations were made in version 4.3.0_003.

First of, the distance between the locomotive and attached carts is quite large.
Which means essentially that there is a gap between their couplings.
When attaching two VL10 units for distributed power the gap gets almost half a block wide.
I guess this may have something to do with dimensions of hitboxes,
but since I am not familliar with programming mods that's really just a guess.

Secondly, I noticed a stuttering side-motion when driving along Traincraft's turns and -switches.
This effect is most noticable when having the camera-perspective set to the view of the driver.
This really bugs me, because I think the greatest strenght of the VL10 is that after having been repainted (I did that) it allows a great view on the line ahead.

Now, for the third thing I need you to bear with me for a short introduction to the context.
There are a few items in Minecraft (and other mods) that are interacted with through a GUI.
A vanilla example would be the book, a modded example are ComputerCraft's Pocket Computers, which can be used to set Traincraft's switches wirelessly from inside the train.
All these items are interacted with by a right-click.
The problem with the VL10 is, that after right-clicking inside the cab minecraft seems to try something like "use-item-with-locomotive" instead of "use-item", which fails and the item does not do anything.
This works nicely on the other locos I've tested so far, for example the V60.

**Comment by NitroxydeX** [comment]
I'm not quite sure if you are talking about the gap when you drive really fast with the train. We are already aware of this issue but can't do very much about it at the moment due to the inefficient code.
Your second thing is related to the first. We are aware that there is side-motion in turns.
For your third thing this could be related to the hitboxes but I'm not quite sure about this.  Try to look to the back but more in 150° instead of 180°

**Comment by Lanthan64** [comment]
The gap appears already when the train is standing still, so it does not seem to be caused only by speed or acceleration.

I am aware that there may appear gaps during accelerations, but that is a different effect from what I saw.
Also that would affect all trains and not only the VL10.

But if the problem lies in the inefficient code I understand that it cannot be fixed for now.
It just seemed strange to me that this stuff works smoothly with all but (at least) one locomotive.

About the third issue: Thanks, that does work. When I'm looking at the motor while clicking the item works as normal.
