### ISSUE TITLE
Missing link between generators and electric locomotives

### ISSUE THREAD

**Issue by Lanthan64** [EternalBlueFlame/Traincraft-5#183]
Hi Everyone,

I noticed that without the use of further mods there seems to be no way to get the electricity produced in Traincraft's RF generators to Traincraft's electric locomotives.

A simple solution to bridge this gap might be a block that produces redstone at a specific rate when it is placed next to a generator. I read that adding stuff is difficult at the moment so this is just an idea on how this can be solved as simply as possible.

Second solution I thought of, more sofisticated, just ignore if not possible:
The block mentioned above would not produce generic redstone, but charge Traincraft's batteries. 
This process of converting depleted batteries to charged batteries might be similar to the distill's process of  converting empty canisters into full canisters. 
Of course, the electric locos should be able to use charged batteries as fuel and return them depleted.

**Comment by NitroxydeX** [comment]
Traincraft was designed to interact with other mods. Before 1.7 it was IndustrialCraft 2 1.7+ it is every RF mod out there. The Diesel Generator, Windmill and Waterwheel are intend to be used with other mods to produce energy. So you will need an other mod to transport the energy from our generators to a battery or something like that. With Railcraft we add a track that can be powered. So you can transport energy to the electric locomotives through these tracks.
