### ISSUE TITLE
Crash on server and game. Direwolf pack. V1.7

### ISSUE THREAD

**Issue by bazarebro** [EternalBlueFlame/Traincraft-5#185]
Getting a crash on both the server and game when I add traincraft to them.

In the game a error appears saying traincraft needs to be version 9.11

Crash logs: 
[fml-server-latest.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/499898/fml-server-latest.txt)
[fml-client-latest.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/499900/fml-client-latest.txt)

**Comment by canitzp** [comment]
you need the latest version on railcraft 9.11 to use traincraft and railcraft together.

**Comment by bazarebro** [comment]
Thank you!

**Comment by NitroxydeX** [comment]
On the client there is a splash screen thats telling you what the problem is if there are wrong mod versions.
