### ISSUE TITLE
Fueling Diesel Locomotives does not work with e.g. Fluid Loader from Railcraft

### ISSUE THREAD

**Issue by dymondy2k** [EternalBlueFlame/Traincraft-5#188]
OK so I've got 2 questions. 
1. I notice you have some 'Traincraft' themed detector and utility tracks. Are they supposed to have the 3d rail look like the other tracks do? Mine don't and I'm not sure if they just don't or if I have a mod issue of some sort?
1. So is there a way to automate the fueling of Diesel Locomotives? I've been able to automate filling the Steam Engines using Fluid and Item Loaders but haven't had any success with Diesel. Hoping I'm just missing something.

**Comment by NitroxydeX** [comment]
1. They are supposed to be non 3D-Tracks because they only load up when Railcraft with non vanilla recipes is enabled.
2. yeah it seems that this is not working for Diesel Locomotives. We'll look into that

**Comment by Quackers29** [comment]
![2016-10-05_19 11 46](https://cloud.githubusercontent.com/assets/11053436/19125660/d3b6d746-8b2f-11e6-841c-53f2d3886a61.png)

I've tried all diesel engines and can't find any I can't load with RC loaders, you have to place the loader 2 or 3 block above the track depending on the engine. (I'm using Rev3)

As in it Does work

**Comment by NitroxydeX** [comment]
@Gazer29 Yeah we know. It's not working atm. We will look into that.

**Comment by dymondy2k** [comment]
Thanx for the answers guys.. I wasn't sure if the 3d track was something on my end or not? So any plans on making a Traincraft Rail compatible version of these in the future? Or even blocks you can set below them? 

I'll try putting the blocks up higher and see if that helps.. I tried both fluid loaders from the top and Advanced Item Loaders from below using Diesel Containers.. I realized I did forget my version of Minecraft.. I'm on 1.7.10

**Comment by NitroxydeX** [comment]
@dymondy2k what do you mean with the rails?

**Comment by dymondy2k** [comment]
Just a detector/specialty track with the nice 3D rail look that you guys created

and FYI putting the fluid loader up to 3 high did fix the fuel loading problem.. It seems 3 high works for the diesel and most of the tenders with the exception of the smaller ones..

**Comment by NitroxydeX** [comment]
mhh. strange. didn't worked for me.

**Comment by NitroxydeX** [comment]
well looked at it again. it works only at the back. this is due our hitbox design.

**Comment by dymondy2k** [comment]
Yeah not sure how I'm gonna get it to line up
