### ISSUE TITLE
Cart Hauler and Minecart(TC) can be crafted in train workbench too

### ISSUE THREAD

**Issue by MarioPL98** [EternalBlueFlame/Traincraft-5#189]
As title says.
Thanks.

**Comment by MggMuggins** [comment]
Bug reports that are all in titles are not of the greatest quality, because they don't include enough info. It's called a title for a reason.

**Comment by EternalBlueFlame** [comment]
Why, in hell, would you make the name so illegibly long?
Also this was likely intentional, this is not something that could have been designed accidentally, or be the result of a glitch.

**Comment by NitroxydeX** [comment]
This was indeed a mistake by someone. I think it was carried over from 1.6.4

**Comment by MggMuggins** [comment]
It was, I remember.
