### ISSUE TITLE
More bugs

### ISSUE THREAD

**Issue by BlesseNtumble** [EternalBlueFlame/Traincraft-5#19]
https://www.youtube.com/watch?v=r1pqBi3XmYs&feature=youtu.be

**Comment by 31trainman** [comment]
The new tc tracks aren't compatible with certain railcraft blocks

**Comment by EternalBlueFlame** [comment]
the issue with switch tracks not turning trains is already known. We're debating just removing/ignoring it for the time being because a completely different rail system, not based on the current, is planned.

**Comment by NitroxydeX** [comment]
We only have the Train Buffer and the Railcraft Buffer from this issue to fix. The rest works.

**Comment by CovertJaguar** [comment]
The Buffer seems like a minor issue that can probably be ignored.

**Comment by EternalBlueFlame** [comment]
The buffer is likely an ID issue. And I agree it is rather minor, but I'd prefer to stay above the dismal quality of ignored issues.

**Comment by EternalBlueFlame** [comment]
Well with the buffer fixed, all the issues in this pull are repaired.
