### ISSUE TITLE
[4.3.0_003] Electric Trains Battery

### ISSUE THREAD

**Issue by GregoriMarow** [EternalBlueFlame/Traincraft-5#190]
hi,
ic2 batteries in electric trains are no longer working. i think this is a essential function and wanted to report that.

---

Also found a report possibility on bitbucket, maybe you should close the old one. Found the link in the wiki under "known bugs"

**Comment by NitroxydeX** [comment]
IC2 functionality has been removed with 1.7.10 because it's extremely uncommonly used. We moved to RF-based Energy which is way better. Get a mod like Mekanism for energy in electric trains. :)

The BitBucket thing: We can't change that by ourselves. I will report that to MrBrutal and Spitfire
