### ISSUE TITLE
Passenger Cars can not be broken

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#191]
Passengers Cars , some other rolling stock such as caboose , can not be broken , when striking their hitboxes .Version Traincraft-4.3.0_004 . Commit 714b89571a97ea82cf4ac80fba1e9b5a50ed43aa broke this . Commit 140d779578de67b10ed7e6e0f8875ef09eea4be4 and earlier are OK !

**Comment by NitroxydeX** [comment]
Don't report bugs for not released versions!
