### ISSUE TITLE
Use oredict for dyes in recipes

### ISSUE THREAD

**Issue by KryptonCaptain** [EternalBlueFlame/Traincraft-5#193]
Ran into this issue on a server I'm on - since some vanilla dyes are annoying to produce, we tried substituting in Botania's floral powder, but train recipes call for the exact dye item, rather than asking for dyeRed, for example.
Could this be changed so recipes use the oredict instead?

**Comment by NitroxydeX** [comment]
Well. If I find where the heck we handle this in the code I can tell you if this is possible.

**Comment by KryptonCaptain** [comment]
https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/recipes/AssemblyTableRecipes.java
Looks like in here.

**Comment by NitroxydeX** [comment]
Not really. This is only for other things. And we have no recipe for the dyes. They are handled very different without an recipe.

**Comment by KryptonCaptain** [comment]
No [`this`](https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/recipes/AssemblyTableRecipes.java#L35) is exactly what I mean. 
e.g. :
`cm.addRecipe(1, null, new ItemStack(ItemIDs.ironBogie.item, 3), new ItemStack(ItemIDs.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), new ItemStack(ItemIDs.ironChimney.item, 1), new ItemStack(ItemIDs.ironCab.item, 1), new ItemStack(ItemIDs.ironBoiler.item, 2), new ItemStack(ItemIDs.ironFirebox.item, 1), new ItemStack(Items.water_bucket, 1), *****new ItemStack(Items.dye, 1, 2)*****, new ItemStack(ItemIDs.minecartLocoBR80_DB.item, 1), 1);`
It directly calls for a dye item here, rather than an oredict

**Comment by NitroxydeX** [comment]
ah well you are referring to recipes in general. they will be redone for the 004 release.

**Comment by EternalBlueFlame** [comment]
added with [https://github.com/EternalBlueFlame/Traincraft-5/commit/e71fbb874107e5f5221ad2b8247cd84808b9bc7c](https://github.com/EternalBlueFlame/Traincraft-5/commit/e71fbb874107e5f5221ad2b8247cd84808b9bc7c)
