### ISSUE TITLE
Red Screen in steam trains

### ISSUE THREAD

**Issue by earthspace1** [EternalBlueFlame/Traincraft-5#199]
i keep having a red screen when i try to run steam trains
the diesel trains are fine 

Steam Trains Red Screens is this bug known?

**Comment by NitroxydeX** [comment]
https://github.com/EternalBlueFlame/Traincraft-5/issues/21

**Comment by xenoswift** [comment]
You have to put water into the steam engine as well as fuel. They chew up water quite quickly, so having a tender will help create a water buffer between refills.
