### ISSUE TITLE
Launching Open Source Code

### ISSUE THREAD

**Issue by EternalStrikerFTW** [EternalBlueFlame/Traincraft-5#20]
I just wanted to know how to start mc with an open source mod 
Can u tell me pls ? :)

**Comment by HadesDurin** [comment]
well, there are 2 ways
first and hard one, you setup a develop enviroment on your pc and compile the code to get the jar file
or
second and easy, you wait for someone to do step one and publish it on the traincraft mod page

**Comment by canitzp** [comment]
A release is planned before the next weekend, but if we found bugs we can't release it

**Comment by HadesDurin** [comment]
from my point i appreciate your work (including all other programmer working on it) and have all the time to wait for traincraft to come to 1.7.10.
i guess you will always found some bugs, some during develeopment, some during gameplay and others during server/single player crashes.

at the end i think this can be closed

**Comment by EternalBlueFlame** [comment]
@EternalStrikerFTW you can't run an open source mod in minecraft without compiling a jar file first.
Because this mod is still being fixed, we do not have any jar files that are already compiled for use yet.
