### ISSUE TITLE
Traincraft crashing with older forge version

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [EternalBlueFlame/Traincraft-5#200]
traincraft crashes when it needs to use an older forge version. Already tried changing preference in the mcmod file but than it crashes again. I use forge 1.7.10-10.13.2.1291-universal in a edited version of madpack 2.1.6
[fml-client-latest.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/556271/fml-client-latest.txt)

**Comment by svhnl** [comment]
i use forge 1.7.10-10.13.2.1291-universal in a edited version of madpack 2.1.6

**Comment by MggMuggins** [comment]
They have said before that they are developing with 1614, and you have to be using that to use Traincraft.  No other option but to use 1614.

**Comment by NitroxydeX** [comment]
You have to use at least the RECOMMENDED Forge version of 1.7.10 -> 1558

**Comment by TeaDrinkingProgrammer** [comment]
ok than i guess i can't use it

**Comment by NitroxydeX** [comment]
you could just update the forge version in this modpack.
