### ISSUE TITLE
The smoke is at the wrong end of the Shay Engine

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#205]
Place Shay on track fuel with coal and water

**Comment by NitroxydeX** [comment]
yeah we know. It's bugged for every steam locomotive.

**Comment by Tsoccerguy3** [comment]
![2016-11-02_19 26 10](https://cloud.githubusercontent.com/assets/22108822/19951777/b63caade-a136-11e6-847d-46ca1ee7b46f.png)

**Comment by EternalBlueFlame** [comment]
This was an issue with all steam trains, and even some others, a mistake on my part while trying to improve the speed of some calculations. This is fixed via [https://github.com/EternalBlueFlame/Traincraft-5/commit/d321fdf83d3964c4d08b46123112784afa2bf160](https://github.com/EternalBlueFlame/Traincraft-5/commit/d321fdf83d3964c4d08b46123112784afa2bf160)
