### ISSUE TITLE
Placing freight cars behind Shay Engine tend to roll over top of the Engine 

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#206]
Just tried to place freight cars behind the Shay Engine , bump into a freight car and they rolled overlapping the Engine . have to break and start again .
![2016-11-02_19 38 08](https://cloud.githubusercontent.com/assets/22108822/19951799/cf9c5c68-a136-11e6-9c98-8e8c4ffe083c.png)

**Comment by NitroxydeX** [comment]
you need to wait till the picture is uploaded...

**Comment by EternalBlueFlame** [comment]
Trains and rollingstock still don't have full collisions with each other.
They can usually be pushed out with some effort, i'll take a look into getting it going tomorrow but i make no promises.

**Comment by Tsoccerguy3** [comment]
I found that this can happen on any on the Engines . I bumped a couple of random cars and they all , a total of 4 cars , ended up overlapping the engines . No way to couple , so had to break and start over . I did find a work around , by placing a block above the track  behind each engine and car provides a collision barrier until i couple everything . Then remove the blocks

**Comment by Tsoccerguy3** [comment]
![2016-11-03_17 31 56](https://cloud.githubusercontent.com/assets/22108822/19986778/69f2db68-a1ee-11e6-8621-5965c84d7d33.png)
When placing flat cars behind a , 4-4-0 Steam , or a Shay Steam , or a Forney Steam coupled to a 4-4-0 Tender or coupled with any tender , bumping into the flat car directly behind , causes it to roll overlapping the Forney Steam or any other Steams . Have to break Steam and Tender and flat car , then start over .

**Comment by EternalBlueFlame** [comment]
fixed in [https://github.com/EternalBlueFlame/Traincraft-5/commit/99330dd58df6b3434adfed7d0ab5e6cf20784046](https://github.com/EternalBlueFlame/Traincraft-5/commit/99330dd58df6b3434adfed7d0ab5e6cf20784046)
