### ISSUE TITLE
Railcraft / Vanillia minecart Compat?

### ISSUE THREAD

**Issue by mariodk** [EternalBlueFlame/Traincraft-5#211]
do so minecarts / railcraft stuff can work on traincraft´s track

and maybe A Traincraft 3d track version of Most of Railcraft´s special tracks & Switches(if railcraft installed)

**Comment by NitroxydeX** [comment]
No Minecarts and Railcraft Stuff don't work on our Tracks. This is something for 1.10 because it needs a whole rewrite for this.

3D Tracks for Railcraft parts? Well, ask Covert for that.

**Comment by mariodk** [comment]
i meant more what railcraft has of tracks but for Traincraft instead & signals  (for 1.7.10 still cant move to 1.10 just yet)

**Comment by NitroxydeX** [comment]
We won't add any new stuff unlike it is very easy to achieve. Anything else is pushed back to 1.10 where we are likely gonna using the signaling from Railcraft.

**Comment by mariodk** [comment]
ohh ok 
so i hope traincraft will be More of a Addon to Railcraft then instead of its own mod
like having bigger curves/slopes/Switches(with railcraft router stuff), works with anything in railcraft
maybe having animated wheels(kinda a thing traincraft needs)

**Comment by NitroxydeX** [comment]
Well no. Traincraft will still be its own mod. Not an addon to anything. But I know that Railcraft is changing its system for signaling so we can better hook into it.

**Comment by MggMuggins** [comment]
My hope is exactly the opposite. I would be much happier with a mod that is completely it's own, and has an addon that makes it compatible with other tech mods. But that is just my personal opinion. I'm happy with the way things are now.
