### ISSUE TITLE
Game Crashes bug

### ISSUE THREAD

**Issue by Elik39** [EternalBlueFlame/Traincraft-5#214]
When I place a train my game crashes. Idk if this is a glitch with the mod or if it's just with me.

**Comment by canitzp** [comment]
Please provide a crash-report file

**Comment by EternalBlueFlame** [comment]
Be sure you're on the latest revision (004) and send us a crash log so we can look further into this issue because I can't seem to replicate the error.

**Comment by Elik39** [comment]
I figured out what was wrong. It was the railcraft mod that I had installed with it. So now that I got rid of railcraft it is working.

**Comment by NitroxydeX** [comment]
Railcraft should be working fine with Traincraft. Could you please provide a crash log?

**Comment by EternalBlueFlame** [comment]
You're probably on an older version of railcraft, only the latest version of railcraft is supported.
The game shouldn't even let you start it with older versions but I've heard stories it randomly lets people through anyway.

Just gonna mark invalid unless you can give an actual crash report like we had asked.

**Comment by Cronosus** [comment]
No crashlog and details  - No fix

**Comment by NitroxydeX** [comment]
Would be nice if you, @Elik39, could still provide a crashlog for that. Just to check what was wrong. Until that we close this Issue.
