### ISSUE TITLE
TC Slopes have problems above specific height and after four in a row

### ISSUE THREAD

**Issue by NitroxydeX** [EternalBlueFlame/Traincraft-5#216]
This issue was reported in the forums because TerraFirmCraft raises the sealevel to 160. 

Checked if it is a bug with TerraFirmCraft but it is also happening in Vanilla Minecraft.

**Comment by EternalBlueFlame** [comment]
I can confirm this issue is specific to TC rails. Does not happen on vanilla or railcraft rails.

**Comment by ArgonTheConqueror** [comment]
Same here: The trains appear to derail after a 4-block increase in altitude. Applies to all 3 sizes of slope.

**Comment by TheSpareAce** [comment]
From what I've figured while making an underground railroad, the slopes do not work below 40 y either.

**Comment by EternalBlueFlame** [comment]
Nah, its just random. I'm _STILL_ getting reports it doesn't work, and the positions are all over the place.
