### ISSUE TITLE
Leave a moving Engine and the Train Stops

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#217]
If you leave a moving Train , Diesel or Steam , the Engine will slow to a stop . Will rapidly stop on a turn

**Comment by NitroxydeX** [comment]
The commit you linked doesn't even touch anything of our movement code.

**Comment by EternalBlueFlame** [comment]
Why do you link unrelated code in your issues? do you even read the modified code before linking it? Or at least check all the revisions?

I know trains and rollingstock have inherited minecart drag for when there is no player in the train. part of the sloppy movement code that needs reworking.
if you have a BUNCH of cars attached this will happen.

**Comment by Tsoccerguy3** [comment]
Sorry I was on the wrong page when I copied the commit version . I commented on this commit a couple of weeks ago 4904727337198c10bb4000e52bf8489e071d3dec .Glad you found the correct commit

**Comment by EternalBlueFlame** [comment]
Why put the comment on an unrelated commit though?

**Comment by Tsoccerguy3** [comment]
Traincraft-4.3.0_005 released December 10 with this game breaker of a bug . All trains on my map stopped running . You should take this build down until a fix is found. In this build the player has to be in the train or the train will stop . The only exception is a Engine with no cars attached

**Comment by NitroxydeX** [comment]
@Tsoccerguy3 if you would open your eyes you would see that it is labeled as "REWRITE". We don't care for this bug at the moment because it's not really gamebraking. The fun at Traincraft is to drive with the trains not let them drive alone.

**Comment by EternalBlueFlame** [comment]
Alright well i just double checked, and I can't replicate this glitch in 005 on TC, vanilla, or RC rails.
unless i drive over powered rails that dont have a redstone signal. but.. well.. duh, of course it happens there.
lets add to it that chunkloading is still broken until either the rewrite, or someone who actually has some experience with that stuff gets in there to fix the chunkloading.
So even if we _did_ fix this bug, assuming it's not either user error or a mod conflict, it won't matter anyway.

**Comment by Tsoccerguy3** [comment]
Maybe this can help to reproduce bug
I have removed all , but TC , mods. Test track is made up of TC rails only , it is 10 x 10 chunks square , flat land , with corner rails at corners. 

Train will run until it hits a corner , then slow to stop 
Running in reverse , train just slows to stop

Drag has something to do with corner rails

**Comment by MggMuggins** [comment]
Just shows that the whole physics of locomotives need to be re-written.

**Comment by EternalBlueFlame** [comment]
I ran that same test and did not get that result. Train runs until it's out of fuel.
It is also possible you are going too fast and you're derailing partially, but not enough to actually fall off the track, if the corner is small try to keep it under 90km, larger ones are usually fine around 160 to 180.

**Comment by Tsoccerguy3** [comment]
Played with it some more . I could not get the Steam Engines ,  to keep moving , forward or reverse .
I could get the Diesel Trains going in reverse with out stopping . There seems to be some misunderstanding which is the front and back of Diesels . Not that there is any difference , since Diesel Engines crank a generator to produce electricity to power the electric motors. No real front or Back , Just flip a switch to change current polarity . 
Its easy to see which is the front and back on a Steam Engine . If it helps this is Single player .

**Comment by NitroxydeX** [comment]
@Tsoccerguy3 how can it be difficult to not understand what is front and back? If you place a train on a straight the front is ALWAYS pointing to the direction you placed it on the track. If you have WAILA/WAWLA you cleary can see it's labeled as "Entity Bogie"

**Comment by Tsoccerguy3** [comment]
NitooxydeX , clearly there seems to be a language barrier I'm noticing , that either its the generation gap or the varying English vocabulary from country to country . I'm posting because my kids are just too young to covey the information and have asked for my help. Yes I know the front from back . I was pointing out that a Diesel Engine is a large generator on wheels and it functions the same in either direction by switching polarity . I was pointing out that that some of the models might be confusing for a younger (novice player) , after all I am repeating what my kids are telling me . Its better to consider this , than not . Functionality should be the same in any direction . This was just food for thought , to improve on a already great mod .  As for the bug  I was pointing out  that corner rails can stop trains among other things . I have set up GIT , to have the code pulled , compiled , logged and copied to the /mods/1.7.10/ dir , for my kids to test for you . Where you guys were tightening up collision fixes is where this bug happened . Yes the train stays together better , but the player has to stay in the train . Kids do say Thanks for the decked out Christmas cars and Merry Christmas , Seasons Greetings .

**Comment by EternalBlueFlame** [comment]
I agree there are some trains that are difficult to determine the front from the back visually, but there's really nothing that can be done for this since we have no artists. That said, this isn't the reason for the issue thread either, so I don't understand why its being brought up here.


On topic, if you're only having the movement issue with steam engines, then I am almost certain it's user error.
Put in a couple buckets of water, and some burnable fuel like coal. give it a minute or so to heat up to "hot", and it will work if you keep up the water and fuel levels.
Steam trains are not easy to drive, there is a lot of fuel management that is complicated to many children. And apparently some adults.
