### ISSUE TITLE
Detector rail can not work with carts from Traincraft

### ISSUE THREAD

**Issue by drzzm32** [EternalBlueFlame/Traincraft-5#218]
detector rail can't output redstone signal ‘HIGH’ while cart passing.
unless player ride this cart. 
but powered rail can drive cart. (onMinecartPass() is ok)
should I use onMinecartPass() to detect cart from TC?

**Comment by NitroxydeX** [comment]
Do you talk about the Minecraft Vanilla Detector Rail? That works fine here.

**Comment by drzzm32** [comment]
yeah... only loco can be directly detected
passenger car requires passenger
or feight car requires feight？

**Comment by EternalBlueFlame** [comment]
The trains and rollingstock are heavily modified minecarts, so some functionality does tend to be off.
Especially in the hitbox/collisionbox area, which is probably what's messing with it.

onMinecartPass() will be more reliable.

**Comment by drzzm32** [comment]
I see, thanks.

**Comment by EternalBlueFlame** [comment]
okay good news, it was kinda hacky, but this should be fixed as of [https://github.com/EternalBlueFlame/Traincraft-5/commit/94f725c8f461c75671c9d5cccf5c27e0b1e02ade](https://github.com/EternalBlueFlame/Traincraft-5/commit/94f725c8f461c75671c9d5cccf5c27e0b1e02ade)
