### ISSUE TITLE
[4.3.0_004] Breaking any tender cart will crash the game.

### ISSUE THREAD

**Issue by ccgfok** [EternalBlueFlame/Traincraft-5#219]
As of the title, if you break any type of tender, your client will be crashed.
To re-produce:
1. Create new world.
2. Give your own any type of tender.
3. Place tender, then break it.
4. Crash.
(P/S: if you re-open this crashed world, you will be able to break them.)
https://github.com/ccgfok/as/blob/master/crash-2016-12-04_15.30.14-client.txt

**Comment by NitroxydeX** [comment]
It's already fixed in the next release.
