### ISSUE TITLE
Train speed reseted in turns and train idling.

### ISSUE THREAD

**Issue by VonZeeple** [EternalBlueFlame/Traincraft-5#223]
I have two problems with train automation in my game. I don't know if these are features or bug:

1) when a train with no conductor encounter a turn (with vanilla rails), the locomotive speed is reseted to 0. This do not happen when i'm riding the locomotive.

2) When the train is idling, the fuel consumption is low but the water consumption stay consequent, so i have frequent explosion in my train depot. Since the fuel consumption is low, it takes a very long time to really stop the engine. Could we have a "cool down" option? By the way it would be cool to have an option in the config file to disable locomotive explosions.

Thanks!

**Comment by NitroxydeX** [comment]
1. we heard about this some things but related to our own rails. we will investigate this with the rewrite.

2. fuel and water consumption should always be the same. never mind if they are idling or not. just remove the coal from the steamtrain and let enough water in it so you are able to deal with the explosions.

**Comment by EternalBlueFlame** [comment]
You can also fill a tender with water to help this issue since steam trains have the ability to take water from tenders.

**Comment by VonZeeple** [comment]
>  just remove the coal from the steamtrain and let enough water in it so you are able to deal with the explosions

This is the point, when the train is full of fuel (20000 for the Shay), you need to wait a huge amount of time. (50 every 5 sec, so i have to wait half an hour in real time). A "shut down" option could emulate the possibility to stop the combustion of remaining coal. 

EDIT: It seems that the speed problem is due to wagon's collision with the locomotive. Maybe due to the new collision system. Since the problem do not appear with a loco alone.

**Comment by NitroxydeX** [comment]
We just can't implement a shut down option because it is highly unrealistic.

If you are aware of this problem don't fill the train with max coal.
