### ISSUE TITLE
Ticketing entity error with railcraft

### ISSUE THREAD

**Issue by BryceJulyCat** [EternalBlueFlame/Traincraft-5#225]
Want to know if the is anything I could do to fix this and to either make it possible for Railcraft to ticket Traincraft entities, or to be able to disable ticketing. (Preferably making it possible for Railcraft to ticket Traincraft entities) I'm not that experienced in coding, so it would be greatly appreciated if more experienced modders would help.
[crash-2016-12-20_20.09.37-server.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/666364/crash-2016-12-20_20.09.37-server.txt)

**Comment by NitroxydeX** [comment]
Update Traincraft and Railcraft to the latest version. This can't happen there.
