### ISSUE TITLE
Collision error with EntityLiving

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#228]
For whatever reason the outer bounding box isn't detecting collisions with the player entity, but the core entity bounding box for EntityRollingstock is. This means that a player or mob has to be halfway into the train to actually collide with it for taking damage. Well beyond the point where it actually starts pushing the entity away.

**Comment by Hagrud** [comment]
Rolling stock deal with collisions in two way:
first in applyEntityCollision() and then with their collision handler.

I think we should remove the first one or define the exact role of both of them.

In the collision handler when we apply collision on living entities we check if the entity at 0.7 blocks of the rolling stock. (variable d2 arround line 345 in collision handler.) 

I can try to fix it this week if I have time.
