### ISSUE TITLE
diesel in openblocks tanks has glitched name

### ISSUE THREAD

**Issue by Nocty201** [EternalBlueFlame/Traincraft-5#233]
Image here: [http://imgur.com/X5URvBA](http://imgur.com/X5URvBA)

The text is, as expected, doing the cycling glitchy thing. Latest version for 1.7.10

To reproduce:

Cook some sugar in the still, pipe it out with an Enderio Conduit into an openblocks tank. Look at the tank with NEI.

Am using US English (Minecraft default) as a language. Changing to an alternative language (in this case, Spanish, French, German, and Italian were checked) makes no difference.

**Comment by EternalBlueFlame** [comment]
Looks like the value is just missing from the language files. Should be an easy fix that we can do in 006.

**Comment by EternalBlueFlame** [comment]
There was an invalid URI in the language files for it. The issue has been fixed for all language files except french which never had an entry for it in the first place.
