### ISSUE TITLE
Water level in steam locomotive not visible

### ISSUE THREAD

**Issue by petulko8080** [EternalBlueFlame/Traincraft-5#235]
Don't know if it is bug or feature :) but when there is no fuel in steam loco, there is no visible level for water tank (normal hud or inventory).

**Comment by EternalBlueFlame** [comment]
it's a known bug from the networking systems, there isn't much that can be done at this point without adding a significant amount of overhead to servers.

**Comment by EternalBlueFlame** [comment]
Sometimes it's nice to find out I'm full of it.
There was actually a couple lines of code that messed up when it was sending the data in a number of ways, I had previously thought it was an issue with how the data was sent, it was a rather easy fix.
