### ISSUE TITLE
Coal dust recipe is too easy for modpacks

### ISSUE THREAD

**Issue by Skkubah** [EternalBlueFlame/Traincraft-5#236]
Greetings,

Recently I've decided to create a private modpack and I've found that the Coal dust recipe in the Train Workbench conflicts with recipes from others mods which have uses for Coal dust like Industrial Craft for example (by saying conflict, I actually mean that the recipes added by those tech mods, involving machines, become pretty much obsolete with the TrainCraft recipe, since the TC recipe don't require machines and in fact, are more efficient), so is it possible for the next versions to have an option in the config file to disable this recipe? (currently using version 4.3.0_005)

**Comment by NitroxydeX** [comment]
I disabled only Coaldust at the moment. Be free to suggest more Item/Block recipes to be disabled. :)
