### ISSUE TITLE
Collisions or reversing when underground

### ISSUE THREAD

**Issue by TheWerdOfRa** [EternalBlueFlame/Traincraft-5#237]
I tried to create a spiraling upward track to connect my mine (around 16) to the surface (around 76). I tried this out above ground and the spiral worked! However, when I built it below ground it stopped working. When I get to the top of the first slope (6 block long version) the train either reverses or stops. I recreated this in creative mode and I had the same problem.

I have been using an BR E69 with no cars attached. The track is placed on slabs, no full blocks were used in a 3x3 "tunnel" around the track.

![traincraft mineshaft](https://cloud.githubusercontent.com/assets/17488364/22405881/0c25280c-e617-11e6-8051-df35f8abeb0b.png)
![traincraft slope issue](https://cloud.githubusercontent.com/assets/17488364/22405918/8bcf3bec-e617-11e6-9af2-b21e0b7c8e35.png)

**Comment by EternalBlueFlame** [comment]
When using slopes you want at least a 3 wide and 4 tall tunnel. Slabs also count as full blocks with the collision system we use.
