### ISSUE TITLE
Composite Suit Durability

### ISSUE THREAD

**Issue by iou1name** [EternalBlueFlame/Traincraft-5#244]
Whenever one of the Composite Suit's effects activate, such as the legs Jump Boost or the helm's Night Vision, part of that armor piece's durability is used. For example, every time I jump 40 durability is taken from legs; 1 durability is taken from the helm when night vision activates, 5 for water breathing. Additionally, any time the durability reaches zero or below as a result of this phenomenon, the durability is reset to full (or almost full). If the durability reaches zero due to damage taken (rather easy to happen with the legs degrading as fast as they do), the armor piece is destroyed.

I assume this to be a bug since the book description makes no note of it but then again the book description is brief to begin with and I've found little documentation elsewhere. If it is intentional it seems like something that ought be mentioned somewhere since this really kind of makes the whole armor set useless.

I'm using:
Minecraft 1.7.10
Forge 1.7.10-10.13.4.1614
Traincraft 4.3.1_007 (though I've the same happen on earlier versions including 4.3.0_003)

**Comment by EternalBlueFlame** [comment]
Without question the durability reset has to be a bug, but the usage rates are more questionable.

Most likely this is a bug leftover from 1.6.4 since that section of the code hasn't been touched since.

**Comment by EternalBlueFlame** [comment]
Is this still an issue in 009+? I can't seem to replicate it anymore.

**Comment by iou1name** [comment]
Yeah, I just tested it and it's still there. I made a new instance of 1.7.10 in MultiMC, installed Forge 1.7.10-10.13.4.1614 with it and threw Traincraft-4.3.2_009 in. New creative map, gave myself full suit of the Composite Suit armor and jumped a couple times (while in survival mode) and watched the durability decrease as described.

**Comment by EternalBlueFlame** [comment]
i'll look into it some more tomorrow then. I've gotta be missing something here...
