### ISSUE TITLE
Honk to get animals out of way

### ISSUE THREAD

**Issue by EzerArch** [EternalBlueFlame/Traincraft-5#245]
Hey, firstly, thanks for Traincraft and all the fun. :)

Now that lots of dead animal remains started to pile up in my inventory as I conduct a train, I'd like to suggest a thing: how about using the horn to scare away those poor animals wandering on the track right in front of the loco?

Perhaps mobs too... well, although I started to enjoy the new (and expensive) way of killing those damn zombies. In this case, all I need to do is "_oopsy daisy_-forget" to honk at them.

Regards,

**Comment by EternalBlueFlame** [comment]
Probably something that will have to come in the rewrite, the main issue is that flat tile entities mess with the mob AI, they think that the block is air until they walk on it then they act as if they are stuck in a block. Even happens on vanilla rails.

The horn idea is nice, and it seems like a good way to fix the issue where it will work with all kinds of tracks.
Better than the plan i had which was just to modify the mob AI to avoid rails.

**Comment by EzerArch** [comment]
Thanks for replying.

I'm aware the glitch is on vanilla side. I've witnessed thousands of times mobs and entities dancing _ballet_ on any non-full block. In fact, being on the track isn't the problem, IMO, it's how they let you roll them over. :)

As last resort, what if the horn "shoot" invisible projectiles that don't deal damage, like snow balls, and that only affect those entities. Obviously, it won't scare the entities away, but will help them get "unstuck".

**Comment by EternalBlueFlame** [comment]
I already tried that fix a while ago, they will immediately run back to the rails, because they want to die, or something.
More realistically it's probably because when an entity is hit they attempt to go back where they were before they were hit (educated guess).

The entity would have to be pushed away, perhaps by changing the movement velocity at an angle relative to the train's rotation...

**Comment by detjensrobert** [comment]
Perhaps a cowcatcher item is in the future...
