### ISSUE TITLE
Railcraft Collision System Overridden

### ISSUE THREAD

**Issue by CaptainTransportation** [EternalBlueFlame/Traincraft-5#247]
Whenever Traincraft and Railcraft are installed together, the Railcraft collision system gets partially overridden.  What's so strange about this, is that all carts use the Railcraft collision system.  But, whenever a TC entity is loaded, the game freezes for about 3 seconds, then comes back to life, and the carts use the vanilla collision system.

I've started using Railcraft carts and trains, because TC trains are extremely hard to automate.  I still use the TC trains for personal use, which causes collision problems.  The trains constantly merge together, and whenever they go around corners, they accelerate to an unreasonable speed, and derail.

**Comment by NitroxydeX** [comment]
Are you using the latest version of Traincraft? None of the problems should happen.
The freezing is kinda strange and the collision bug too. Traincraft does not interact with the collision system of Railcraft.

**Comment by CaptainTransportation** [comment]
Using Railcraft 1.7.10-9.12.2.0 and Traincraft 4.3.1_007.

I have Real_Train_Speed set to true in the TC config, other than that, no config changes.

**Comment by EternalBlueFlame** [comment]
TC's collision system isn't designed to override that of railcraft except in the case of a traincraft entity colliding with a minecart. TC's linking system is also separate from RC's.
Are you using any specific kinds of rails or minecarts? Or are you trying to link the minecart to something from TC? And are there any other mods or plugins?

I can't replicate it, but maybe you're doing something different, so I have to ask.

**Comment by CaptainTransportation** [comment]
I am using vanilla/railcraft rails.  I also have Railcraft Cosmetic Additions and Steve's Carts installed, but I have been able to replicate this without Railcraft Cosmetic Additions or Steve's Carts installed.  Does the forge version matter?  I have 10.13.4.1566-1.7.10 installed.

TC trains + TC trains works fine,  Vanilla/RC carts + Vanilla/RC carts is where problems occur.
I am linking carts with a Railcraft Crowbar

I also made a brief video showing the problem: https://www.youtube.com/watch?v=iPQH9H_uiEA

**Comment by EternalBlueFlame** [comment]
The version might make a difference but it's rather unlikely.
That is a very strange error... oddly enough the minecarts on mine are never that difficult to push, even without TC.

we'll have to look into this further. If you get any more info on this stuff, let us know.

**Comment by CaptainTransportation** [comment]
Thanks, will post more info if I find anything else.
