### ISSUE TITLE
New train: Norfolk & Western 1218

### ISSUE THREAD

**Issue by TheSpareAce** [EternalBlueFlame/Traincraft-5#248]
Idea for a(nother) powerful steam engine: Norfolk & Western 1218 2-6-6-4 wheel configuration locomotive
![image](https://cloud.githubusercontent.com/assets/25802995/22993634/8648f9e2-f378-11e6-8d82-9d43f8073775.png)

112km/h 
83 buckets (Did the math (and seems unrealistic))
5,400 hp (real  life horsepower( don't know how to calculate Mhp))
This train would be nice train to have in the game. =)

https://en.wikipedia.org/wiki/Norfolk_%26_Western_1218 <-- Source.
NW 1218 for short.

**Comment by TheSpareAce** [comment]
NW 1218 for short.

**Comment by NitroxydeX** [comment]
please use #58 for that.
