### ISSUE TITLE
[Suggestion] Add config option to disable steel making in the hearth furnace

### ISSUE THREAD

**Issue by wormzjl** [EternalBlueFlame/Traincraft-5#251]
So modpacks can use other more complicated process to make steel

**Comment by EternalBlueFlame** [comment]
I have no idea how this issue got past me (I just now saw it), but the entire point of the hearth furnace is steel, so you can just disable it with an item ban mod or plugin.

**Comment by wormzjl** [comment]
hearth furnace can be made in train workbench, which recipe cannot be disabled

**Comment by NitroxydeX** [comment]
I don't know why I forgot this issue here. We will add it to an existing config flag.

**Comment by wormzjl** [comment]
ok thanks!

**Comment by EternalBlueFlame** [comment]
I meant like ban the item. There are a number of mods to ban items and prevent them from even being used.
But I guess nitro's fix works too.

**Comment by wormzjl** [comment]
thanks!
