### ISSUE TITLE
Passenger Cart do not cooperate with railcraft track

### ISSUE THREAD

**Issue by l89669** [EternalBlueFlame/Traincraft-5#254]
issue:
when I place a passenger cart(N.Y. Subway) on Railcraft Hi-Speed Booster track and move it, it's speed boost. But when the boosted passenger cart travel on a Railcraft Hi-Speed Transition Track, it doesn't speed down and finally end with explotion.
Both tested on redstone activated track and not activated track. I'm sure the Orientation of  the Transition Track is right.
Sorry for my bad English, hope you can understand what I'm saying.
Forge: 1.7.10 1614
Railcraft: 9.12.2.0
Traincraft: 4.3.1_007

**Comment by NitroxydeX** [comment]
why should it speed down? Where does it explode? Pictures/Videos?

**Comment by l89669** [comment]
the Hi-Speed Transition Track was designed to slow down the speed of a minecart to a normal speed so the cart can go back to non-hi-speed track. Because if the cart don't slow down and directly go to a normal track from a hi-speed track, it would explode. The slow down feature on the transition track don't work on the passenger cart.
Can you understand what I say?

**Comment by NitroxydeX** [comment]
Ah okay. Have you tried multiple of the Transition tracks? Could you provide a picture so I can check if you really have the right orientation?

If everything yes: It could be possible that it is just not working with out moveOnRail-code (we don't use the vanilla one)

**Comment by EternalBlueFlame** [comment]
That's a good point I didn't think of, the motion calculations are different from normal minecarts, so it would likely take more of the transition tracks than normal.

Another option as well is unpowered booster track, it has about the same effect for slowing the cart back down to normal rail speeds.

**Comment by l89669** [comment]
I'm sure I've put the track on right orientation because it can slow down the railcraft carts.
I think it's just something wrong with the code that controls the speed of the cart. Maybe you can add something like a cart speed limiter into the code.
If you guys can make the code more compatible with railcraft, I and many Minecraft railway lovers will be very grateful for this.

**Comment by EternalBlueFlame** [comment]
aside from orientation, we're also saying the number of slowdown tracks, because traincraft rollingstock are a lot harder to slow down than a minecart.

I have tested it myself a few times more recently in the IDE and in my own minecraft install and it works fine. Not exactly like a minecart, because its not a minecart, but it works fine.
That being said it is a rather limited test area, so it is possible there's something else going on here.

**Comment by l89669** [comment]
ok, so I found that too. It's likely that the traincraft cart boost to a unreasonable speed on railcraft hi-speed boost track. The speed of the cart is too high for the transation track to slow it down. Usually 8 tracks can slow down the railcraft carts, but I've put 100 tracks and it still can't slow down a traincraft cart. So I suggest a speed limiter for the traincraft cart. The speed limiter is usually implemented in railcraft locomotives and minecarts. So if you guys can write this, the traincraft carts may work better on railcraft track system.

**Comment by l89669** [comment]
I've found a ridiculous but useful solution. Make the hi-speed cart derail and use another track to hold it and the speed will slow down. It's just so strange in traveling passenger's eyes...

**Comment by EternalBlueFlame** [comment]
Odd... I guess the best option might be to make a fallback method for if the track is one of the slow down tracks, to cover the circumstance that vanilla minecart code doesn't kick in....
I'll have to look into it in the next couple days, things are kinda busy over here.

**Comment by l89669** [comment]
Confirmed that it has been fixed in build 009! Thank you very much!
