### ISSUE TITLE
Traincraft Composite Suit Pants Glitched

### ISSUE THREAD

**Issue by SuperKingJulian2** [EternalBlueFlame/Traincraft-5#256]
Since the first version of Traincraft 1.7.10 the Composite Suit Pants are NOT working anymore... well at least not how they should work !
The issue is pretty simple to explain:
The Pants (only part of the Armor which is NOT working) getting damage and break once you wear them in survival mode which makes them useless... 
it is like it gets permanent damage like somthing is hitting you permanently... but nothing is only walk around and it breaks itself... hopefully this gets fixed in one of the next updates!

SuperKingJulian2 (SKJ) a fan of Trains and TRaincraft!

**Comment by EternalBlueFlame** [comment]
Interesting.... It's probably an issue with the durability scaling against the armor provided. The 1.7 armor methods are still kinda weird to me. But should be an easy fix at least.
