### ISSUE TITLE
Lost items with Traincraft!

### ISSUE THREAD

**Issue by SuperKingJulian2** [EternalBlueFlame/Traincraft-5#258]
There are some isues losing items partly or complete with removing Crafting Tables (Tier1-3 (maybe also Traincraft Table, i dont tested the traincraft table)) OR Caboose Wagons!
What happens:
Removing Crafting Tables (Tier1-3) --> if items are in the different slots for crafting a train you will lose parts of the items you put in if you remove the Table (example: you have put in 20 items of each you need, you remove the table and get back a part drop of for example 14 items of the one item and 12 or 18 of another, it seems some items randomly disappear here!)
Removing a caboose --> Furnance inventory gets lost (doesnt drop)

Your SKJ !

**Comment by 31trainman** [comment]
Great way to not get help as you haven't said what other mods if any are installed and what tc version your on.

**Comment by EternalBlueFlame** [comment]
So, let me try and be clear on the issue you are stating, when you break a crafting table it doesn't drop the items it had in the slots.
Is that about right?
I think that was an old glitch from 1.6.4, don't remember if we ever dealt with it.

Off-topic: that's a good reminder though I need to deal with that in the rewrite...

**Comment by SuperKingJulian2** [comment]
It does lose items partly (not all items get lost) only few items get lost from the workbenches...
For the caboose carts yes it completly loses invetories (furnance)
