### ISSUE TITLE
Zora No Densha track issue 

### ISSUE THREAD

**Issue by whatsapp2** [EternalBlueFlame/Traincraft-5#259]
There's a bug with zora no densha tracks and traincraft engines. 
![2017-02-23_20 14 29](https://cloud.githubusercontent.com/assets/25994176/24128188/eb51924a-0d9f-11e7-9861-6b929367f575.png)

It would be awesome if EternalBlueFlame could work with leshuwa kaiheiwa.
(I apologize for my english. I cant speak english very well

**Comment by EternalBlueFlame** [comment]
A patch for this has been being talked about over the past couple days. we're seeing if we can make it happen.
There is an API for it, but it will be questionable if TC's path-finding code will accept it.

It won't be an issue in the rewrite, that much I am sure of.
