### ISSUE TITLE
"Fatally missing blocks and items" on server connect attempt.

### ISSUE THREAD

**Issue by Neko-Jess** [EternalBlueFlame/Traincraft-5#260]
So my friend in New Zealand has had this issue since the 1.6.4 version, and it still persists in the new 1.7.10 version. We are using the latest version of the mod and, while I can connect just fine, his attempts at joining my dedicated server throw up the aforementioned message and kicks him from the server before even getting in. I have looked at the console, and there are no error messages either. The following is the console log that comes up each time.

25.03 06:12:14 [Server] User Authenticator #2/INFO UUID of player warpath246 is 94a266be-2276-437f-a0eb-36e82db6fd28
25.03 06:12:15 [Server] Netty IO #6/INFO [FML]: Client protocol version 2
25.03 06:12:15 [Server] Netty IO #6/INFO [FML]: Client attempting to join with 175 mods : BuildCraft|Silicon@7.1.16,ProjRed|Expansion@4.7.0pre12.95,ForgeMicroblock@1.2.0.345,iChunUtil@4.2.2,rftools@4.23,ExtraBees@2.0-pre14,PortalGun@4.0.0-beta-6,ThaumicExploration@0.6.0,springboards@0.1,EnderZoo@1.7.10-1.0.15.32,MineFactoryReloaded|CompatTwilightForest@1.7.10R2.8.1,MagicBees@2.4.3,Botany@2.0-pre14,ProjRed|Integration@4.7.0pre12.95,endercore@1.7.10-0.2.0.36_beta,Mystcraft@0.12.3.02,MineFactoryReloaded|CompatProjRed@1.7.10R2.8.1,BuildCraft|Robotics@7.1.16,McMultipart@1.2.0.345,BiomesOPlenty@2.1.0,props@2.3.3,ExtraUtilities@1.2.12,Railcraft@9.12.2.0,guideapi@1.7.10-1.0.1-20,MineFactoryReloaded|CompatRailcraft@1.7.10R2.8.1,WR-CBE|Addons@1.4.1.9,MineFactoryReloaded|CompatForestry@1.7.10R2.8.1,IC2NuclearControl@2.4.1a,ThermalFoundation@1.7.10R1.2.5,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.1,ForgeMultipart@1.2.0.345,headcrumbs@1.7.4,StevesCarts@2.0.0.b18,BrandonsCore@1.0.0.12,RedstoneArsenal@1.7.10R1.1.2,MCFrames@1.0,CoFHCore@1.7.10R3.1.3,ResourceLoader@1.3,neresources@0.1.0.ManuallyBuilt,BiblioWoodsForestry@1.7,FastCraft@1.23,OpenPeripheral@0.5.1,Forge@10.13.4.1614,ExtraTrees@2.0-pre14,HatStand@4.0.0,StorageDrawers@1.7.10-1.10.1,gendustry@1.6.3.132,ThaumicTinkerer@unspecified,AdvancedSolarPanel@1.7.10-3.5.1,BuildCraft|Energy@7.1.16,modtweaker2@0.9.5,IC2@2.2.823-experimental,JABBA@1.2.2,ExtraTiC@1.4.6,MineFactoryReloaded|CompatIC2@1.7.10R2.8.1,ProjRed|Transportation@4.7.0pre12.95,FML@7.10.99.99,Natura@2.2.0,NEIAddons|Forestry@1.12.14.40,TiCTooltips@1.2.5,ThE-core@1.0.0.1,BiblioWoodsNatura@1.5,<CoFH ASM>@000,tc@4.3.1_008,NEIAddons|CraftingTables@1.12.14.40,NEIAddons|ExNihilo@1.12.14.40,WailaHarvestability@1.1.6,ThermalDynamics@1.7.10R1.2.0,ProjRed|Illumination@4.7.0pre12.95,TMechworks@0.2.15.106,fastleafdecay@1.4,Botania@r1.8-249,Hats@4.0.1,LogisticsPipes@0.9.3.126,Avaritia@1.11,FTBU@1.0.18.2,FTBT@1.0.2,NotEnoughItems@1.0.5.120,Thaumcraft@4.2.3.5,Waila@1.5.10,ProjRed|Compatibility@4.7.0pre12.95,ForgeRelocation@0.0.1.4,extracells@2.3.14,TConstruct@1.7.10-1.8.8.build988,simplyjetpacks@1.5.3,StevesFactoryManager@A93,appliedenergistics2-core@rv3-beta-6,NEIAddons@1.12.14.40,BinnieCore@2.0-pre14,inpure|core@1.7.10R1.0.0B9,StorageDrawersForestry@1.7.10-1.1.2,BiblioCraft@1.11.5,BuildCraft|Core@7.1.16,OpenModsCore@0.9.1,ImmersiveEngineering@0.7.7,SolarExpansion@1.6a,bdlib@1.9.4.109,NEIAddons|Developer@1.12.14.40,tcinventoryscan@1.0.11,wawla@1.3.1,RelocationFMP@0.0.1.2,Genetics@2.0-pre14,mcp@9.05,Mantle@1.7.10-0.3.2.jenkins191,ProjRed|Transmission@4.7.0pre12.95,journeymap@5.1.4p1,appliedenergistics2@rv3-beta-6,thaumcraftneiplugin@@VERSION@,WR-CBE|Logic@1.4.1.9,OpenPeripheralIntegration@0.5,MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.1,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.1,DraconicEvolution@1.0.2h,WR-CBE|Core@1.4.1.9,inventorytweaks@1.59-dev-152-cf6e263,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.1,StorageDrawersMisc@1.7.10-1.1.2,harvestcraft@1.7.10j,Morpheus@1.7.10-1.6.21,ThermalExpansion@1.7.10R4.1.3,TwilightForest@2.3.7,BuildCraft|Factory@7.1.16,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.1,GraviSuite@1.7.10-2.0.3,AgriCraft@1.7.10-1.5.0,OpenPeripheralCore@1.3,NEIAddons|AppEng@1.12.14.40,OpenBlocks@1.5.1,EnderStorage@1.4.7.37,ForbiddenMagic@1.7.10-0.575,EnderTech@1.7.10-0.3.2.405,FTBL@1.0.18.2,MineFactoryReloaded|CompatForgeMicroblock@1.7.10R2.8.1,CarpentersBlocks@3.3.8,MineFactoryReloaded@1.7.10R2.8.1,StevesWorkshop@0.5.1,EnderIO@1.7.10-2.3.0.428_beta,BuildCraft|Compat@7.1.5,Translocator@1.1.2.16,ComputerCraft@1.75,funkylocomotion@1.0,CustomMainMenu@1.9.2,neiintegration@1.1.2,AWWayofTime@v1.3.3,MrTJPCoreMod@1.1.0.33,immersiveintegration@0.6.8,IronChest@6.0.62.742,NEIAddons|Botany@1.12.14.40,MineFactoryReloaded|CompatThermalExpansion@1.7.10R2.8.1,thaumicenergistics@1.0.0.5,CodeChickenCore@1.0.7.47,BigReactors@0.4.3A,MineTweaker3@3.0.10,BinniePatcher@1.8.2,ThaumicTinkerer-preloader@0.1,aobd@2.9.2,NetherOres@1.7.10R2.3.1,debug@1.0,StorageDrawersNatura@1.7.10-1.1.1,BuildCraft|Transport@7.1.16,StorageDrawersBop@1.7.10-1.1.1,chisel@2.9.5.11,Baubles@1.0.1.10,StevesAddons@0.10.16,ProjRed|Core@4.7.0pre12.95,denseores@1.0,ProjRed|Exploration@4.7.0pre12.95,witchery@0.24.1,Forestry@4.2.15.63,OpenMods@0.9.1,BiblioWoodsBoP@1.9,PTRModelLib@1.0.0,BuildCraft|Builders@7.1.16,ChocoPatcher@1.1,runicdungeons@1.1.7b
25.03 06:12:15 [Server] Netty IO #6/INFO [journeymap]: CLIENT
25.03 06:12:15 [Server] Netty IO #6/INFO [FML]: Attempting connection with missing mods [] at CLIENT
25.03 06:12:16 [Disconnect] User warpath246 has disconnected, reason: Disconnected
25.03 06:12:16 [Server] Server thread/INFO warpath246 left the game

My server is running FTB Infinity Evolved on expert mode, and he was able to connect just fine before we added the mod. I should also mention that 2 other players, both in the UK, can join perfectly fine as well as my roommate and myself with the mod installed. Anny assistance on this matter would be apreciated. Thank you~ : 3

**Comment by EternalBlueFlame** [comment]
I can't really say anything from the information provided, the server sided logs are rather useless, can you get the client logs by chance? That would have the actual problem in it and from there I can probably assist you further.

**Comment by EternalBlueFlame** [comment]
It's been like 2 weeks, any update on this issue? I can't really do anything for it without more information (I'm still not even sure if this is a TC issue).

**Comment by NitroxydeX** [comment]
Check your config files and resync them with your buddy that has this weird problem. Should fix the issue.
