### ISSUE TITLE
Can I get a redo version for Forge 1.7.10 1448 (Poketech Request)

### ISSUE THREAD

**Issue by jaipersaga** [EternalBlueFlame/Traincraft-5#263]
Title is pretty clear. The only conflict in my private pack for adding this is requires forge 1558 and Poketech 1.3 has forge 1448. Please give me a break if you may. I would really appreciate the support I have been waiting for a 1.7.10 for possible poketech submission to my server for years now. I hope this can be done on the cheap. If not I guess I will wait for another future hopeful traincraft pixelmon server.

Thx,
Jaipersaga

**Comment by EternalBlueFlame** [comment]
Are you sure you can't run poketech on later versions of forge? (have you tried it?)
I mean it's still 1.7.10.... Zora No Densha (and a number of other mods) were built for the same version, and sometimes even earlier, I believe, but they work fine on 1558 and later (as long as you're not trying to run the game from inside an IDE).

**Comment by NitroxydeX** [comment]
I'm sure you can run the Modpack on a later version of Forge. Otherwise you could update all your mods to be compatible with the Recommended Forge version of Traincraft.
