### ISSUE TITLE
New vehicle

### ISSUE THREAD

**Issue by Oskiek** [EternalBlueFlame/Traincraft-5#265]
Here you are. New vehicles
[Konstal105Na.zip](https://github.com/EternalBlueFlame/Traincraft-5/files/949864/Konstal105Na.zip)
 
[KonstalN.zip](https://github.com/EternalBlueFlame/Traincraft-5/files/949873/KonstalN.zip)

sended as requested.

**Comment by EternalBlueFlame** [comment]
The 150N has some duplicate variable/shape names, and the syntax is messed up in both.
I have already fixed these issues, but it should be mentioned that I made changes to your code structure of the model files.
(still working on adding them in).
//EDIT: almost forgot, I will still need icons for them. (for the items).
//EDIT 2: they were also upside down. fixed that too.

**Comment by EternalBlueFlame** [comment]
looks like theres some model issues with the Konstal Na.
![java_2017-04-23_19-48-05](https://cloud.githubusercontent.com/assets/9969122/25318991/0703cb92-285e-11e7-8bd7-0f3af8aee809.png)
Also, they aren't quite center and a little wide, this is minor to the point I don't really care, but I thought it would be worth mentioning to you.
![java_2017-04-23_19-50-32](https://cloud.githubusercontent.com/assets/9969122/25319002/25756fc2-285e-11e7-8849-599c476b3a25.png)

**Comment by Oskiek** [comment]
[Trams.zip](https://github.com/EternalBlueFlame/Traincraft-5/files/951861/Trams.zip)
Here you are. New Models but in OBJ. I guess its good.

**Comment by EternalBlueFlame** [comment]
I can't render trains and rollingstock with obj, unless you want this to wait till the rewrite.
The port's render will only take .java.
