### ISSUE TITLE
[Enhancement] TC rails & TC gravel  - mob spawn prevention

### ISSUE THREAD

**Issue by HadesDurin** [EternalBlueFlame/Traincraft-5#279]
As title says to prevents mobs from spawning on the rails and on the TC gravel.
That way you can have a 3 wide tunnel and mobs dont spawn inside when you have TC gravel next to the rails.

Info:
Railcraft has Obsidiangravel to prevents mobs from spawning.

**Comment by NitroxydeX** [comment]
It acts like it should. Mobs spawning is detected by the block under the rail. If the light level is too low a mob will spawn. This is no enhancement it would just make it "peaceful" for our stuff.
