### ISSUE TITLE
Inefficient code

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#28]
Large amount of redundancies, and unused and/or inefficient code throughout the entire project.

**Comment by EternalBlueFlame** [comment]
There is a lag to rotation that is also caused by this, when the code is cleaned up more, the rotation can be updated more frequently, as it stands it's overly demanding to increase the update rate.

**Comment by MggMuggins** [comment]
Idk if this is the place to post this, but what is the plan regarding upcoming versions? Is this port going to stay 1.7 at least for the time being, and do a lot more work in that version, or continue to be ported up? I would like to see a supported 1.7 version as many modders (especially on bigger mods like LOTR) are staying with 1.7.

**Comment by EternalBlueFlame** [comment]
@MggMuggins We will retain support for 1.7 for a while because of all the other devs that are staying on 1.7. And of course we'll keep updating it, improving and fixing things.

Plans for versions beyond 1.7 are likely going to be rewrites because there's a lot of things that just need to be done again from scratch.
There are already rewrite projects in place for 1.10.2(canitzp via the main repo) and 1.7.10+ (me, via TiM).

However it is possible that we will port the 1.7.10 version to later versions depending on other mods and how long the rewrites take and how much progress the port ends up making.

**Comment by MggMuggins** [comment]
Cool, thanks. If I ever get anymore than mediocre coding knowledge/skill I may help. We'll see.

**Comment by EternalBlueFlame** [comment]
Just gonna close this one, the code isn't gonna get much more efficient at this point in the port.
