### ISSUE TITLE
Make AbstractZeppelin acceptable for OreDictionairy Coal

### ISSUE THREAD

**Issue by NitroxydeX** [EternalBlueFlame/Traincraft-5#280]

**Comment by EternalBlueFlame** [comment]
perhaps it would be better/easier to just get a burnable amount like the vanilla furnace does?

**Comment by NitroxydeX** [comment]
This issue was just to save the request from the forum. How we solve this is our thing.

**Comment by EternalBlueFlame** [comment]
fair enough, but it's still a question what would be preferable, vanilla furnace option is easier and gives user a lot more ability but is there something about the furnace (lore wise for lack of a better term) that merits it should be coals only?

**Comment by NitroxydeX** [comment]
well the zeppelins are coal only atm. some user requested wood too. But I think it would be better just to use coal

**Comment by EternalBlueFlame** [comment]
well stealing vanilla furnace code is just doing `TileEntityFurnace.getItemBurnTime(cart.getStackInSlot(SLOT)`
which returns an int value.
thats why i ask, should we use vanilla or is there a lore-esk reason to use just coal.
