### ISSUE TITLE
Hit Box issue in 009

### ISSUE THREAD

**Issue by HadesDurin** [EternalBlueFlame/Traincraft-5#281]
here you see how it looks like after i reload my world moments ago:
http://prntscr.com/f6mvnq
the locomotiv has only 1 of the 2 hitboxes....

after i pick up and replace the locomotiv it has the 2 normal hitboxes:
http://prntscr.com/f6n1n6

as you can see my hitbox is also offset, but that is maybe a seperat issue...

**Comment by NitroxydeX** [comment]
Are you sure that on the first picture the train isn't just derailed?

**Comment by HadesDurin** [comment]
if it happens again, that after reload a hitbox is missing i will take a new picture from it

**Comment by EternalBlueFlame** [comment]
In the first image, it seems as if the "missing" hitbox for the train is actually in the camera.

Improper hitbox offsets are a common error, not new to 009, I believe it's something to do with the yaw not saving to NBT, which isn't the only thing that has this issue.

**Comment by HadesDurin** [comment]
here is a new picture of the latest hitbox issue
http://prntscr.com/f6vyhb
http://prntscr.com/f6vz0n (same picture as above, but after pressing F5)

as seen the hitbox is offset from the train, also 2 freight carts are occupying the same space
normally the train looks like this:
http://prntscr.com/f6w14b

**Comment by NitroxydeX** [comment]
So you push the carts?
well. -> https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/client/gui/GuiRecipeBook.java#L248

**Comment by HadesDurin** [comment]
i only push carts only when the gap is to great between the cart and train i want to attach the cart to.
all pictures are taken right after i reload my savegame.

**Comment by HadesDurin** [comment]
i drive the locomotiv backwards, have problems to figure out, where the front is....
so either way i pull the carts with the locomotiv

**Comment by NitroxydeX** [comment]
On your first picture, the left side, where the train is missing the boogie: That is the front of the train. So attach it to the back. That is pulling (never mind if you go forward or backwards) but if you attach it to the front it is always pushing for the system which isn't working.

**Comment by HadesDurin** [comment]
ok here ends my english knowledge...
what is a boogie??
is the cabin where you take place to controll the train the front?

**Comment by NitroxydeX** [comment]
the boogie is just the second hitbox of the trains. If you look with WAILA at it you will see which is the boogie

**Comment by HadesDurin** [comment]
ah now i get the issue its bogie
and the translation is messed up

entity.tc.Entity Front Bogie.name=Radsatz <- thats is really odd translation

**Comment by NitroxydeX** [comment]
@HadesDurin well. It would be more like "Drehgestell" instead of Radsatz.

**Comment by HadesDurin** [comment]
i have the bogie now in front and will see if there is more hit box issues after turning the locomotive around

**Comment by HadesDurin** [comment]
at the moment i work around this, to take all carts from the track and leave just the locomotiv befor leaving and saving my game...

**Comment by NitroxydeX** [comment]
Is the glitch still happening for the attached carts that they are rotated 90°?

**Comment by HadesDurin** [comment]
as said, i put the carts befor a save inside a chest, to prevent any issues.
later in a few days when i have more evolved into traincraft, i can tell you more, maybe 010 is then aviable to test it with the latest build, but next update from me will need some more days maybe 1 or 2 weeks till next test and update. since then the pictures i provide speak mostly for themselves.

plans befor next updates: lay more tracks, build more locomotives and carts and some other stuff

**Comment by NitroxydeX** [comment]
Well if the attached carts are rotated by 90° this can happen. Just move the Train forward and they should rotate back.
