### ISSUE TITLE
IC4 ideas

### ISSUE THREAD

**Issue by SuperKingJulian2** [EternalBlueFlame/Traincraft-5#286]
I personally think that the IC4 and its wagons are defenetly too long for Traincraft, it should be shortened to the lenght of the other locos / hitboxes should be changed so the train doesnt seem to derail each turn you drive in... shorten it a little would help i guess
Also why does wagons recipes requires engines? (electronic?) normally they shouldnt have these parts in theire recipe..
since the loco anyways needs a recipe at all (it misses yet) it would for sure good to use electronic engines for the loco
also like i already said that for mallard, the train looks, in my personal opinion, a little too small (high)
Hope i am not making too much work for you by posting my ideas...

**Comment by NitroxydeX** [comment]
The Recipe issue is already resolved with the next update and the IC4 will get a new shorter model then now. We have a poll here about the Aspect Ratio of new trains: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2738593-traincraft
