### ISSUE TITLE
New Rail

### ISSUE THREAD

**Issue by JPLogics** [EternalBlueFlame/Traincraft-5#287]
Gents,
Not sure which "Issuel to add this too so please reference if required.
Would you accept the model and the written code for some new switches?
I'm using TrainCraft in a ComputerCraft project but running into "Asthetically pleasing" designs due to the "Parallel Switches" enormous size! My railways (usually) runs, track-gap(1x1)-track, so swinging out to add these makeshift crossovers is a pain,
I'm willing to design the switch model and make adjustments the the code to enable them to work f that's is aloud?

I'm thinking of
- Crossovers
- Level Crossing pieces
- 3D Track - Detector Rails!

Let me know.
Thanks
JPLogic

**Comment by NitroxydeX** [comment]
This belongs to #48. And contribution is very desired. If you wanna talk to us just join our Discord - The link is in the Repo Readme. Tracks need to be obj and json (basically obj for 1.7.10 and jsons for 1.10+) and both variants work different.  While in 1.7.10 the path-finding is written inside our train-base and bogie-base the path-finding for 1.10 works with waypoints that are calculated on the rail itself and the train just follows it (this is by far better for performance)

1.10 repo is here: https://github.com/Traincraft/Traincraft

If you are able to write down the java calculations there are plenty tracks already finished and they just wait to get into Traincraft. Maybe there are already the tracks you want. In general Tracks should use our main graphic-asset so we don't need to add another texture for it (besides special tracks)

**Comment by EternalBlueFlame** [comment]
> (this is by far better for performance)

Best joke 2017.

Seriously though, if you wanna contribute some new tracks we'd be glad to have it, I don't mess with it because the entire system is garbage and I have my hands full with the rewrite, but that doesn't mean we won't work with others on adding stuff.

**Comment by JPLogics** [comment]
Excellent!! I'll work on that soon then!
For clarification. The rewrite, is that going to be for JUST 1.10? Or 1.7.10 as well?

Also along the lines of diverging mods, is in TiM? The new one after a couple of stages of enhancements?
Will that work along side TC or be completely independent?

**Comment by NitroxydeX** [comment]
Well. Technically there are two rewrites. The "main" rewrite lead by canitzp starts with 1.10 while the second rewrite is a main platform for TiM and TC on 1.7.10. TiM is an independent project with its own way on doing things.

**Comment by EternalBlueFlame** [comment]
TiM will be on 1.7.10, 1.9.2/4, 1.10, and 1.11.
However TC is currently only planned for 1.7.10, 1.9.2/4, and canitzp's version for 1.10+

As nitro said, TiM and TC will be fully independent, very different, and able to run alongside eachother.
