### ISSUE TITLE
Traincraft Electric Track not working

### ISSUE THREAD

**Issue by FloofyPeachy** [EternalBlueFlame/Traincraft-5#290]
![image](https://cloud.githubusercontent.com/assets/20615551/26727128/2a971344-476b-11e7-82ab-f4635997270e.png)
Okay, so this track is not working. It does work in earlier versions, such as 009. I'n not sure what is going on.

**Comment by NitroxydeX** [comment]
That's correct. Energy-Tracks are supposed to receive RF Energy now. But it's not working like it should.

Hey, @TheBlueCrystal could you look into this? This was made by you.

![2017-06-02_18 04 54](https://cloud.githubusercontent.com/assets/9305576/26734414/300f4c58-47be-11e7-9808-3e7d8da76684.png)

Rails can't be placed on TileEntities like the cables from Mekanism and they only receive energy from a block directly underneath them. This isn't the best way to handle it. When you want to make a clean build this looks really ugly.

**Comment by EternalBlueFlame** [comment]
It appears to be two errors, one being the train's ability to receive power from the track, and two the rendering.
Try putting a railcraft electric train nearby.
Even though the track only turns red when one is under it, it will still feed a RC electric train nearly 2 chunks away, but it does nothing for TC trains.

**Comment by TheBlueCrystal** [comment]
On my own worlds I place Thernal-Expansion "Fluxducts" with a cable- facade or Mariculture "Custom RF-blocks" underneath the track - this way it integrates seamlessly with other blocks under the track. Theoretically the track should be placeable on any block that exposes a solid surface on top. With cable-facades resembling the actual surface of the blocks the track is layed out on.

I did not change anything in the logic / interface of the track towards locomotives. The only thing I've changed is that the track does not accumulate "energy" by a redstone-signal, but rather by drawing RF-power form the block beneath it. TC-locomotives in my worlds always only got powered if they stood directly on an electric track. (I haven't used Railcraft-locomitives at all, yet)

What would be the preferred solution? Shall I implement drawing RF-energy from any adjacent block? Or maybe add a config-option to choose the preferred method (RF-power or simple redstone signal)?

**Comment by NitroxydeX** [comment]
RF power is the better way but we shouldn't see cables facades as standard to go. what about spreading the power between the tracks? so you don't need to connect to every rail a cable?

Are TC trains loading while they go over the tracks?

**Comment by TheBlueCrystal** [comment]
Yes, they are loading while passing over the tracks, but only as long as the locomitive is above it with it's "hotspot". (I usually use a speed-limitier track in front of a couple of those so the loco goes slower over them and catches more energy while doing so.) It would be possible to spread the energy between the tracks. (I haven't implemented such a system, since that wasn't the way they originally work, so I wasn't sure, if that was something desireable)

**Comment by FloofyPeachy** [comment]
But I feel like they should make it redstone powered because that is the thing that is being used on my world(maybe become a server).

**Comment by TheBlueCrystal** [comment]
Perhaps a config-option to choose which "power-system" one desires would be a good idea, since it's really a drastic change in game-mechanics.

**Comment by FloofyPeachy** [comment]
Ya.

**Comment by NitroxydeX** [comment]
Well. These tracks are designed to only run with Railcraft and its mechanics enabled. So basically on the other hand you always have pipes ingame that are able to handle RF.

**Comment by FloofyPeachy** [comment]
Whatever, lol. I'll code my own electric track then.

**Comment by TheBlueCrystal** [comment]
I've finally gotten time to update the electric track. It now draws RF-power from adjacent RF-provider-blocks on the same level as the track and one level below. The electric track also propagates it's energy among other directly connected electric tracks with a "loss" of 1RF per track-block. (There is no "real" RF-loss - every single RF you put into the tracks gets propagated and can be drawn back out, but the tracks degrade in their maximum stored energy-level with greater distance from the main source if they are not directly powerd by an RF-provider. So after theoretical 2000 consecutive electric tracks where only the first one is directly powered by an RF-source you would have to place another RF-power-source.)

Finally there is also a config option now where you can select if you want the electric tracks get powered by a redstone signal or by "real" RF-power. RF-powered is the default.

Please see pull-request #303 for more informations.

**Comment by EternalBlueFlame** [comment]
request #303 has been merged for release with 010
