### ISSUE TITLE
train refuses to pass

### ISSUE THREAD

**Issue by traso56** [EternalBlueFlame/Traincraft-5#296]
so i was using the 002 version and decided to update to 009 (hehe a bit late)
but now my train refuses to cross this part

http://i.imgur.com/9qabQD2.png

it used to be able and no matter how fast i go it stops right there instantly (at least it doesn't derail)

**Comment by EternalBlueFlame** [comment]
If I remember correctly... The hitbox height of the train was raised to prevent a player suffocation bug due to the player's hitbox in 1.7.10.
<img width="400" alt="java_2017-07-05_00-16-40" src="https://user-images.githubusercontent.com/9969122/27850038-548d07a6-6117-11e7-9227-4ad45c3149b2.png">

**Comment by traso56** [comment]
well i don't remember if the SD40 did actually pass but my BR01 did it perfectly in 002

i guess i'll remake the gate  ¯\\_(ツ)_/¯
