### ISSUE TITLE
Trains reverse on sharp turns, still an issue

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#30]
The longer the train the worse it is, but train's can't go over certain speeds around corners without turning backwards, like in: [https://github.com/EternalBlueFlame/Traincraft-5/issues/23](https://github.com/EternalBlueFlame/Traincraft-5/issues/23)

Once it has turned backwards the first time, the error won't repeat.

This is very likely due to a degree of the rotation processing in EntityRollingStock.java
It is possible the above mentioned issue is also related to this.

Originally documented in:
[https://github.com/EternalBlueFlame/Traincraft-5/issues/19](https://github.com/EternalBlueFlame/Traincraft-5/issues/19)

**Comment by EternalBlueFlame** [comment]
Further experimenting has shown this is an issue with how EntityRollingStock.java's rotation and position interact with the render.

**Comment by EternalBlueFlame** [comment]
I'm working on a new system for rotating the train based on the motion vectors, which should solve this issue, but it will take some time, it's not working well.

**Comment by CovertJaguar** [comment]
Vanilla based rotation sucks, end of story.

I do a few hacks to make it work.

First, make sure the EntityMinecart.isInReverse boolean is written to the NBT, it is not by default. This will likely require some reflection.
https://github.com/CovertJaguar/Railcraft/blob/dev1.10/src/main/java/mods/railcraft/common/carts/EntityLocomotive.java#L563

Then you need some addition code in the renderer:

```
            yaw %= 360;
            if (yaw < 0)
                yaw += 360;
            yaw += 360;

            double serverYaw = cart.rotationYaw;
            serverYaw += 180;
            serverYaw %= 360;
            if (serverYaw < 0)
                serverYaw += 360;
            serverYaw += 360;

            if (Math.abs(yaw - serverYaw) > 90) {
                yaw += 180;
                pitch = -pitch;
            }

            ((IDirectionalCart) cart).setRenderYaw(yaw);
```

https://github.com/CovertJaguar/Railcraft/blob/dev1.10/src/main/java/mods/railcraft/client/render/carts/RenderCart.java#L87

And after all that, it will probably still be derpy at times unfortunately, but this is the best solution I could come with.

**Comment by EternalBlueFlame** [comment]
Thanks for the assistance, but I'm already working on a better system for this anyway that won't be derpy.
I'd be done already but I havn't had the chance to really code the past 2/3 days.

**Comment by EternalBlueFlame** [comment]
This, along with some use of isReverse, should fix the issue, after I figure out where to apply it in TC.
So much easier to test and build in a clean environment.
https://github.com/EternalBlueFlame/Trains-In-Motion/commit/ed2112cbb71e1391ca40ce6696522455a293f097
mostly line 366-370 of MinecartExtended.java

**Comment by EternalBlueFlame** [comment]
this seems to be far more of a problem than just base tracks or rendering, the entire train turns around, and on both normal and TC tracks, which have totally different systems of management.

for anyone who has any ideas, here's the improved code for the rotation and pitch:
rotationYaw = (float) (atan2((lastTickPosX - cartX), (lastTickPosZ - cartZ)) \* rotationPi)+90F;
                if (isClientReverse){
                                rotationYaw+=180F;
                }
                if ((motionX > almostNotMoving || motionX < -almostNotMoving) ^ (motionZ > almostNotMoving || motionZ < -almostNotMoving)) {
                    cartPitch = MathHelper.floor_double(Math.toDegrees(acos(lastTickPosY - cartY)) + 90D);
                }

**Comment by CovertJaguar** [comment]
The problem stems from the fact that Minecraft is only accurate +/- 180 degrees. You have to track the yaw changes to detect when Minecraft flips 180 and undo it. The code I posted earlier does this by comparing the last known yaw to the current requested yaw.

Here we normalize the yaw variables (make them between 360-720 for convenience):

```
            yaw %= 360;
            if (yaw < 0)
                yaw += 360;
            yaw += 360;

            double serverYaw = cart.rotationYaw;
            serverYaw += 180;
            serverYaw %= 360;
            if (serverYaw < 0)
                serverYaw += 360;
            serverYaw += 360;
```

Here we compare them and flip 180 if necessary:

```
            if (Math.abs(yaw - serverYaw) > 90) {
                yaw += 180;
                pitch = -pitch;
            }
```

**Comment by EternalBlueFlame** [comment]
The working code isn't the problem, I posted my own code that is more accurate to the yaw _and_ pitch movement without need to rely on any underlying MC code.
However, I should clarify the variable names a bit more, because I doubt anyone would read the link where I implemented it in my other project....

To the point: As I more recently stated, the problem now is _not_ how to fix it anymore, it's that _I don't know where it goes_ in the mess of code that is TC.

> rotationYaw = (float) (atan2((lastTickPosX - cartX), (lastTickPosZ - cartZ)) \* (180/Pi))+90F;
> if (isClientReverse){
> rotationYaw+=180F;
> }
> if ((motionX > 0.00138888888D || motionX < -0.00138888888D) ^ (motionZ > 0.00138888888D || motionZ < -0.00138888888D)) {
> cartPitch = MathHelper.floor_double(Math.toDegrees(acos(lastTickPosY - cartY)) + 90D);
> }

**Comment by CovertJaguar** [comment]
Heh, well I can't help there. I put mine in the renderer, as I only cared which direction the carts are rendered.

**Comment by EternalBlueFlame** [comment]
I did the same for my own project.
but in TC it's in far too many places at once.

**Comment by EternalBlueFlame** [comment]
well rotation works graphically, but the hitboxes aren't working with it.
And the slow update rate of the position is obnoxious when it's done this way, so that will have to be sped up.

**Comment by EternalBlueFlame** [comment]
Getting close to a working fix, oddly enough this wasn't a rotation issue at all, but rather an issue with trains not derailing.

**Comment by CovertJaguar** [comment]
Derailment in my experience is almost always caused by too much speed, but I have no idea if that applies to Traincraft.

**Comment by EternalBlueFlame** [comment]
Yeah the issue is that it's not derailing when it should.
Its partially fixed but needs a but more tuning, and its not fixed for TC rails.
put the last couple days into other projects, need to get back to TC soon.

**Comment by EternalBlueFlame** [comment]
Should be fixed as of [https://github.com/EternalBlueFlame/Traincraft-5/pull/59](https://github.com/EternalBlueFlame/Traincraft-5/pull/59)
