### ISSUE TITLE
"JAR file could not be launched" error message

### ISSUE THREAD

**Issue by jmfreedly** [EternalBlueFlame/Traincraft-5#301]
I'm trying to download and install Trancraft for 1.7.10 on a Mac. When I try to open the JAR file I get this message:

"The Java JAR file "Traincraft-4.3.2_009.jar" could not be launched. Check the Console for possible error messages."

Has anyone dealt with this issue? I'm not sure what to do next.

**Comment by EternalBlueFlame** [comment]
You put the jar file in your mods folder for forge.
they have instructions on how to use it on their website.
