### ISSUE TITLE
Diesel generator is not showing the correct fuel

### ISSUE THREAD

**Issue by traso56** [EternalBlueFlame/Traincraft-5#307]
After trying to setup some emergency diesel generators i noticed they accept BC fuel but not actual diesel
using 009

![Alt Text](http://i.imgur.com/HOaMR9K.png)

**Comment by NitroxydeX** [comment]
About which Diesel are you talking exactly?

**Comment by traso56** [comment]
traincraft native diesel

**Comment by traso56** [comment]
ok more testing showed that it actually accepts it but it had fuel so it is incompatible and removing the fuel then inserting diesel fixes it

i was confused because hovering the mouse in the tank said it was diesel and looked like diesel

**Comment by NitroxydeX** [comment]
ah well okay.
I think the gui doesn't care which fluid it's in it always shows Diesel. We should change that.
