### ISSUE TITLE
train position after server restart

### ISSUE THREAD

**Issue by quentfr21** [EternalBlueFlame/Traincraft-5#320]
hello
 
before : http://mat.fr21.free.fr/report/before.png

after : http://mat.fr21.free.fr/report/after.png

all train are locked by a railcraft rail and are "running" (wait redstone signal to start only one)
all train pointing the South of the map

after the restart cart don't get their link or get bad position (fixed loco by using oneway rail (railcraft))

thanks in advance

edit: same type of result with the latest version (011)

**Comment by EternalBlueFlame** [comment]
It's a bug with the NBT data from what I know. 1.7.10 doesn't allow for as much data as older versions so some things tend to get lost in saving. it's rather random too, in some cases the data lost is harmless, although in other cases its like this.

Far as I know, short of reworking the data-structures of trains and rollingstock (and probably corrupting worlds by doing so), there is no fix short of the rewrite...

**Comment by quentfr21** [comment]
hello

i make some try but i don(t get the requiered knowledge

but i found  methods that may help 

@Override
public void readFromNBT(NBTTagCompound data) {
super.readFromNBT(data);
}
@Override
 public void writeToNBT(NBTTagCompound data) {
super.writeToNBT(data);
}
i hope this help or it's already this methods you told me 

thanks again

**Comment by NitroxydeX** [comment]
as he told you: it's a bug with NBT as it's not able to store ALL data we provide to NBT

**Comment by EternalBlueFlame** [comment]
yeah, those are already the methods i was referring too, unfortunately.

**Comment by quentfr21** [comment]
hello
i just push a nbt fixe if you can take a look
thanks in advance

**Comment by EternalBlueFlame** [comment]
yeah, i already made a reply on it

**Comment by traso56** [comment]
I have to note that i notcied new worlds i made are unaffected by this, they load just fine that may help but i'll do more testing
