### ISSUE TITLE
I cannot see trains //CLOSE

### ISSUE THREAD

**Issue by ghost** [EternalBlueFlame/Traincraft-5#327]
Hey,

when I place a train I cannot see it. But its only at me and at my friends not.

http://prntscr.com/goumtg
There is a train but I cannot see it.

How can I fix? 

~ DekoLP #

**Comment by ghost** [comment]
And I tried F3 + A and I cannot see the trains but the rails I can see

**Comment by ghost** [comment]
![2017-09-23_22 33 52](https://user-images.githubusercontent.com/29925199/30776993-52e3df90-a0b1-11e7-848a-3aea5c0257b8.png)

**Comment by EternalBlueFlame** [comment]
I'm assuming by the "//CLOSE" you figured out the answer?
If so, what fixed it?

**Comment by ghost** [comment]
Restarting my PC

**Comment by EternalBlueFlame** [comment]
Weird, must have been some form of GPU cache error.
Well there's some extra compensation for that sorta stuff in 012 so it should be even less of a problem there.
Thanks for the heads up.
