### ISSUE TITLE
Idea for a new train

### ISSUE THREAD

**Issue by ghost** [EternalBlueFlame/Traincraft-5#328]
Hey dear developer of traincraft,

can you please add this train to your mod? https://www.google.at/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjp99D_vcPWAhXBvRQKHb-zAWsQjRwIBw&url=http%3A%2F%2Fwww.alamy.de%2Fstockfoto-ein-city-shuttle-zug-auf-der-osterreichischen-bundesbahnen-an-der-seite-eines-zuges-in-wien-osterreich-53168285.html&psig=AFQjCNF1o-mNRicRF9b44G-TCscyf11bNw&ust=1506537039692706
Its a train from Austria. And in the train carriage can seat two players. One player down and the other player up.

Sry for my bad english but Iam from Austria :D

**Comment by NitroxydeX** [comment]
post this in #58 and see how to request a new train
