### ISSUE TITLE
Mekanism support

### ISSUE THREAD

**Issue by EzerArch** [EternalBlueFlame/Traincraft-5#331]
**Suggestion:** Traincraft could support Mekanism, at least partially. Not essential.

Mekanism is an industrial mod with production lines and some fancy features.

Main mod's features that overlap or could co-operate with Traincraft (from the least to the most relevant):
* Plastics ([HDPE](https://en.wikipedia.org/wiki/High-density_polyethylene) type).  (I'd leave this alone because Mek plastics are made of biomass, not from petroleum).
* Copper, from ores to ingots.
* Steel, from ores to ingots.
* Pumps (input and output).
<details> 
  <summary>Fun: My attempt to use Mekanism pumps with TC wagons</summary>

![2017-09-24_22 26 22](https://user-images.githubusercontent.com/6743303/31161556-321d0fe8-a8ae-11e7-912d-b0bacc960964.png)
![2017-09-24_22 26 34](https://user-images.githubusercontent.com/6743303/31157723-51cde710-a893-11e7-95c0-29473c7c705b.png)
_Oopsie..._
</details>

<br />
That's all.

**Comment by EternalBlueFlame** [comment]
Copper and steel should be supported already in 011 from ore directory functionality.
As for pumps, theoretically they should work fine assuming they actually go through the entity fluids system of minecraft like railcraft.

**Comment by MggMuggins** [comment]
It looks like there is a block of space between the cart and your pump. Did you try getting it closer?

**Comment by EzerArch** [comment]
> It looks like there is a block of space between the cart and your pump. Did you try getting it closer?

I did, but the car's hit box is almost 3 blocks high. If I lower it [the pump], the car won't fit/pass through.

![2017-10-04_15 21 08](https://user-images.githubusercontent.com/6743303/31192552-f186070e-a917-11e7-8445-85efe504512c.png)

**Comment by MggMuggins** [comment]
Traincraft hitboxes are a bit of a mess, but that's known...

**Comment by EternalBlueFlame** [comment]
it should work fine if it's a block higher than the image, or at least railcraft has in my testing.
although if that is still a problem, check out this forum post:
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2738593-traincraft?comment=509

**Comment by MggMuggins** [comment]
Traincraft hitboxes are a bit of a mess, but that's known...

**Comment by NitroxydeX** [comment]
Railcraft is working cause it checks for an EntityMinecart while Mekanism just outputs with their pumps. No checks if there is anything below them. This is nothing we can fix on our side. Mekanism would need to add a check if there is an EntityMinecart below it and if it is acceptable to hold Fluids.

**Comment by EternalBlueFlame** [comment]
I would think it has to check for something though? Unless it works in reverse and the receiver has to do all the work, which would be stupid.

**Comment by NitroxydeX** [comment]
Well it's a simple pump to get all FluidDict registered liquids. But it can be used to reverse the process and putting liquid again into the world. It think it can be used to fill up a lake or something like that.
