### ISSUE TITLE
New Skins?

### ISSUE THREAD

**Issue by TrainsAndThings** [EternalBlueFlame/Traincraft-5#336]
So  the other day i was searching around online for some textures for the trains and i found this one which is pretty good! 
![workcaboose](https://user-images.githubusercontent.com/32917244/31749697-903ebc42-b449-11e7-9563-be439b15f442.png) i was wondering if it could be added in possibly.

**Comment by EternalBlueFlame** [comment]
Where exactly did you find it? (We'd need the author's permission to add it)

**Comment by TrainsAndThings** [comment]
I found it in a texture pack that said i was free to use it how i wanted

**Comment by EternalBlueFlame** [comment]
Well even so, in that case, I'd still need the license myself so I could document it (and also be sure it's properly interpreted).

**Comment by TrainsAndThings** [comment]
https://www.planetminecraft.com/texture_pack/tc-retextures/ Is the link i found it on.

**Comment by EternalBlueFlame** [comment]
Hm, shows the page is invalid... So either they are having issues with the website (not a first) or the creator took it down, in which case we can't use it (unless there's a source somewhere else that says we can).

**Comment by TrainsAndThings** [comment]
i got in contact with the creator of the pack, mazradi was his name i think but heres a updated link http://www.mediafire.com/file/2t2gs5fnj65wxz9/YThundermesa.zip

**Comment by EternalBlueFlame** [comment]
Oh yeah, I know maz.
From what I've heard he blocked me...
So I don't think that's gonna work out well, lol.

**Comment by TrainsAndThings** [comment]
i asked him about this and he said "do what ever ya want with it, if you want to get eternal to put it in then do as you want, i dont care"

**Comment by EternalBlueFlame** [comment]
Well enough then. I'll run it by the artists.

**Comment by TrainsAndThings** [comment]
@EternalBlueFlame any news on the skin?

**Comment by EternalBlueFlame** [comment]
Oh, my bad.
Checked again with the art team and it was denied because it wasin't quite up to par and the creator didnt wanna mess with it any further than it was (apparently i had inquired on this previously?).

**Comment by Mazaradie** [comment]
Yeah I might consider editing it to my newer specs but here is a sneak peak at what I have currently submitted. 
![image](https://user-images.githubusercontent.com/33501935/33316367-bb204c00-d401-11e7-9a22-92a7e1aa3e5f.png)

**Comment by TrainsAndThings** [comment]
Hey thats pretty good! maybe a little bright but its still pretty good none the less! Im hoping to see that in the mod soon!
