### ISSUE TITLE
Trains not rendering since 0.13

### ISSUE THREAD

**Issue by joe1587joe** [EternalBlueFlame/Traincraft-5#337]
Ever since i updated to 0.13, trains refuse to render. This results in the entity being there, but there being no visible train. I have tried reinstalling, restarting my pc, and using a fresh minecraft save. What can i do to fix this.

**Comment by Tsoccerguy3** [comment]
Steps to reproduce . pictures .

**Comment by EternalBlueFlame** [comment]
try changing the value of force texture binding in the config.
Also can you list the mods you're using? it might be a conflict issue.

**Comment by NitroxydeX** [comment]
So @joe1587joe you've closed the issue: this means the force texture binding helped?

**Comment by MggMuggins** [comment]
Would be good to know what you did so that people coming by later might have their problem solved.

**Comment by joe1587joe** [comment]
it has happened again. I did not change anything last time, it just worked
![2017-10-23_16 51 23](https://user-images.githubusercontent.com/32987665/31899111-b7a33f2a-b812-11e7-91b0-50b3592624a5.png)
![2017-10-23_16 51 30](https://user-images.githubusercontent.com/32987665/31899130-c282fdfe-b812-11e7-8558-b5d348a8db20.png)
in the first picture, you can see the train entity on the map, and in the second, the train has been broken to prove it was there

**Comment by EternalBlueFlame** [comment]
i'll ask again, what other mods do you have installed?
If it's happening regardless of the value of force texture binding, then it's likely a conflict with another mod.

**Comment by NitroxydeX** [comment]
we had this same problem in #327 but a restart solved it.

**Comment by EternalBlueFlame** [comment]
yeah but it should be deeper than just "did restarting fix it?"
you shouldn't have to restart in the first place, unless it's a caching error because you're on a 10 year old GPU and/or have significantly detailed mods/texturepacks.

**Comment by joe1587joe** [comment]
I use Sphax Pure BD Craft resource pack, whilst using these mods:
Buildcraft, Railcraft, Pam's Harvest Craft, Optifine, Inventory Tweaks, NEI Intergration & NEI

**Comment by EternalBlueFlame** [comment]
It could be optifine. I'm pretty sure there are things in there that could cause the issue, like threaded rendering options.

**Comment by joe1587joe** [comment]
I will try removing optifine to see if that works, although it has worked with optifine before

**Comment by joe1587joe** [comment]
Removing Optifine doesnt resolve the issue
Removing the texture pack makes no difference to it whatsoever

**Comment by joe1587joe** [comment]
Removing the texture pack makes no difference to it whatsoever

**Comment by MggMuggins** [comment]
What does NEI Integration do?

**Comment by EternalBlueFlame** [comment]
hm.. strange...
I'll probably have to rework the render more for the next version, some people have issues with it, and others don't. It's very weird.
