### ISSUE TITLE
Deltics and the bounding boxes

### ISSUE THREAD

**Issue by TrainsAndThings** [EternalBlueFlame/Traincraft-5#338]
So i have been messing with the "deltic" and i tryed putting two togther but when i fuled both and put the back into "can be pulled" mode it just started glitching back and fourth going from 0 to 500 km/h etc when i tryed to get out of it it murderd me.

**Comment by EternalBlueFlame** [comment]
This isn't specific to the deltic, it's a bug related to double-heading configurations.
Unfortunately there's nothing we can do for this until the rewrite (sometime this winter).
