### ISSUE TITLE
Exploding train cars

### ISSUE THREAD

**Issue by TrainsAndThings** [EternalBlueFlame/Traincraft-5#339]
so this just happend and i know of a few cases where this has happend before. it involves one or more train cars just exploding for no apperant reason leaving fire and holes in the track everywhere 
![2017-10-24_06 12 14](https://user-images.githubusercontent.com/32917244/31937443-62e4f5f8-b882-11e7-845c-79dd22605550.png) if any one knows why this happens feel free to comment but i feel like its a bug

**Comment by VioletWyvern** [comment]
Did you used steam loco?  Do you forgot to add water into loco?

If steam loco are running without any water, the steam loco's boiler will overheat and explode !

**Comment by NitroxydeX** [comment]
I think it's what @VioletWyvern mentioned. Our steam trains can overheat if you don't supply water to it which you can see if you sit in them because the whole screen is covered with a transparent red overlay.

**Comment by TrainsAndThings** [comment]
Yeah but from my questions the guy who owned the train had only cars in the consist and no engine, he was just pasing into a diffrent sideing when it blew up @NitroxydeX

**Comment by NitroxydeX** [comment]
well. cars can't explode on their own.
Shouldn't be anything with our mod. If it can't be replicated it's probably not a bug in TC

**Comment by TrainsAndThings** [comment]
So i just tested a thing in single player, exploded a steam engine and it dident create a crater or fire maybe it has something to do with lightning?

**Comment by NitroxydeX** [comment]
it should create a crater if I didn't changed that. Lightning?

**Comment by TrainsAndThings** [comment]
Well see in the photo it was raining so maybe lightning hit it? or a charged creeper? i dont know but i know that a steam engine was not involved

**Comment by EternalBlueFlame** [comment]
Guessing by the sinking into the ground and single tile lit on fire, I'd wanna say lightning as well...

**Comment by TrainsAndThings** [comment]
thing is theres normally more than one bit of fire which is odd. i dont know why it does this tho and its really weird but if someone could recreate it that might solve a lot of questions @EternalBlueFlame

**Comment by EternalBlueFlame** [comment]
I agree, but I also have a feeling someone recreating it is gonna be a while.

**Comment by quentfr21** [comment]
i can confirm it's due to ligtning

on my server with no population if the train is chunkloaded after i week all loco are broken by ligjting while i don't get another chunkloader mod

only chunk with train are loaded, so if it turn to thunder on server , ligtning are focused on chunk with train and finally break it

thanks

**Comment by EternalBlueFlame** [comment]
looking into the lightning code a bit more, it does seem very likely this is at least part of the cause, if not the entire cause.
I'll have a patch in 015 to prevent lightning from striking trains and rollingstock.
But I'll leave this thread open just in case it's more than that.
