### ISSUE TITLE
Problem of ICB

### ISSUE THREAD

**Issue by HydrogenC** [EternalBlueFlame/Traincraft-5#342]
I built a ICB train with only one cart.
It’s written in the GUI that the maximum speed is 278 km/h. 
However, I can only speed the train to 196 km/h. 
Is this a bug?

**Comment by HydrogenC** [comment]
But I can speed the train to the maximum speed if there are no carts.

**Comment by VioletWyvern** [comment]
The gui is only show the top speed when loco with no carts (The more carts you pulls, the more weight you gain, that mean more carts decrease your top speed)

**Comment by HydrogenC** [comment]
Nope. 
I mean the locomotive’s inventory. 
Once I drove a Shunter with several carts. 
And it displays that the max speed is 19 km/h instead of 32 km/h.

**Comment by EternalBlueFlame** [comment]
The gui shows what's supposed to be the max speed, but the additional calculation of the MHP changes the end-result. It's an old bug, and a really big one, but if nothing else at least it's only cosmetic. The calculation sin the rewrite are completely different so this isn't an issue.

**Comment by HydrogenC** [comment]
And is the rewrite for 1.7.10 or for 1.10+

**Comment by NitroxydeX** [comment]
it's for 1.7.10 & up
