### ISSUE TITLE
Trains speed does not hold

### ISSUE THREAD

**Issue by Birbs1** [EternalBlueFlame/Traincraft-5#343]
Apperantly when I drive a train (electric, diesel, steam) the speed does not hold and then it goes backwards. if I were to just sit there while in the train not touching the keyboard or mouse, the train will move by itself. This bug applys to Traincraft version 4.3.4_013. Also I have the following mods. Rival Rebels and Railcraft. Could anyone help me?

**Comment by HydrogenC** [comment]
Yeah. 
After I have stopped a train to 0 km/h, it will still move towards in a very low speed. 
Seems like a bug.

**Comment by EternalBlueFlame** [comment]
old bug, use the brake in the GUI to actually bring it to a full stop

**Comment by Birbs1** [comment]
yeah one more thing if I were to go to a random speed such as 30 Km/h the speed will not hold then the train will start to slow down to 0 Km/h. After it stops at 0 Km/h the train starts to go backwards. Ive noticed one thing that wherever the camera goes it will go the opposite way. (Here's an example. If I were to look forward while in the train, the train starts to go backwards and if I were to look backwards the train goes forward.) Sorry I had to put this at the last minute.

**Comment by EternalBlueFlame** [comment]
Yeah, that's an intentional function. TC never used to have a reverse key, so you would just go whatever way you were looking.

**Comment by TrainsAndThings** [comment]
all you have to do to fix this bug is A. hit escape or B. find what key is bugged out and press it again to hopefully fix the bug. for example if the W key is bugged it will act as if its still being pressed down so to fix it you would turn around and see if you start slowing down then if you do press the W key again to make the pc think you un pressed it, if that docent work press the escape key and that should work.

**Comment by NitroxydeX** [comment]
@TrainsAndThings well he can't join games and it's happening on placement. So the only solution would be remove the options.txt out of his main folder.

**Comment by TrainsAndThings** [comment]
@NitroxydeX  where does it say he can't join games?

**Comment by NitroxydeX** [comment]
@TrainsAndThings a well. ignore me. thought you were commenting an other issue :D

**Comment by Birbs1** [comment]
Well Thanks Guys but I already found out on what's going on. Apparently whenever I hit the key c, the "bug" happens. The Key c is used for the idle key which is used on the zeppelin. All I did was I changed the key to another key (ex. c = +) And that solved the problem.

**Comment by EternalBlueFlame** [comment]
Hm... I wonder if it's a type check then? perhaps we're letting key commands for the zeppelin go through to the train, and vice-versa?
