### ISSUE TITLE
Traincraft crash

### ISSUE THREAD

**Issue by Treeminer** [EternalBlueFlame/Traincraft-5#344]
Hello,

I got a problem with Traincraft 4.3.4_013. The game crashes if I want to place a new train. The game also crashes when I'm loading a world where trains are already placed in the world. I do use other mods, but even if I remove them the error still exists.

[crash-2017-10-30_12.02.26-client.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/1426920/crash-2017-10-30_12.02.26-client.txt)

**Comment by NitroxydeX** [comment]
The referenced error is a check if a specific key is pressed. Check which button is assigned to moving forward in Minecraft. Alternatively use Forges method to remove erroring entities. We didn't changed anything on that method in the last update. 

You could also try to update your java version

**Comment by Treeminer** [comment]
Okay, I will try that. By the way, I forgot to mention that this error started to appear starting from version 4.3.3_010. Version 4.3.2_009 works fine.

**Comment by NitroxydeX** [comment]
We changed a lot in 010. I think we changed the way we handle forward/backwards in that version. So you should replace all your trains.

**Comment by Treeminer** [comment]
Well, this also happens when creating a new world  and placing a train.

**Comment by NitroxydeX** [comment]
that's really strange. shouldn't happen. it just checks the forward key from minecraft.

**Comment by EternalBlueFlame** [comment]
It shows the key you pressed has the ID value of -100, which is not a valid key for the keyboard management functions in minecraft itself (nor is that a value any normal keyboard, in any language, would ever throw).
Why traincraft is the only thing crashing you, is something i will never understand. I can make a patch so it will only check valid entries, but it will go from crashing to just straight up ignoring that input.
Either way it's a problem that's more-or-less exclusive to you.

**Comment by Treeminer** [comment]
Okay, I checked the options.txt after resetting the controls. The ID value -100 is the left mouse button, normally used for attack...

**Comment by NitroxydeX** [comment]
Checked my options. Yes. negative values are mouse-buttons. 
Anyway: Is it working now or still crashing?

**Comment by Treeminer** [comment]
Unfortunately not, still crashing :(

**Comment by EternalBlueFlame** [comment]
hm, if left click was assigned to move forward that would do it. Theres no compensation for mouse inputs, it expects a keyboard one. In fact the entire system is designed like that.... I'll have to see about a way around that in the rewrite, as for the port that's significantly more complex.
