### ISSUE TITLE
Curved Slopes

### ISSUE THREAD

**Issue by TrainsAndThings** [EternalBlueFlame/Traincraft-5#345]
Would there be a way to add curved slopes to the game? like take the curves we already have and just add a slope to them.

**Comment by EternalBlueFlame** [comment]
They are already planned for the rewrite, and there is some code in place already for them (not fully working yet).
For the port we'd have to combine two different pathfinding methods, and neither of them work well from the get-go, so the end result can't possibly be good, lol

**Comment by rickborkhuis** [comment]
@EternalBlueFlame the last time there was something comitted in the traincraft rewrite was 6 months ago,
when is it finished?

**Comment by NitroxydeX** [comment]
@rickborkhuis https://github.com/EternalBlueFlame/Trains-In-Motion

**Comment by EternalBlueFlame** [comment]
nitro's link is right, but also i've been stuck on the code, so I havn't done a git push to it in a while (i've got like over 1k uncommitted lines of code, didn't wanna push till it worked, the new rails are a MASSIVE system). this is about how far they are. fully dynamic multiblock, but there's some bumps in the render where it's not quite right, trying to iron them out.
add to it, i moved last month, so there went an entire month of time.
![image](https://user-images.githubusercontent.com/9969122/32985530-20d1d626-cc83-11e7-8639-88686b417ac7.png)

**Comment by traso56** [comment]
oohhh these rails look absolutely sweet
