### ISSUE TITLE
dummy locomotives

### ISSUE THREAD

**Issue by minningguyteen2** [EternalBlueFlame/Traincraft-5#348]
it may sound crazy but how about making a dummy locomotive that can sit on the end of a train.
example: 
ICE engine- 1st class coach- 1st class coach- buffet coach-2nd class coach-2nd class coach- ICE dummy
(exactly the same model as the engine but it acts more like a coach.)
How it could be done:
clone loco and rename it with "dummy."
rip out the code for the engine and replace it with the code that the coaches have.
only difference: mass will be the same as the coaches.

**Comment by Mazaradie** [comment]
Do you mean the option to pull a locomotive dead in tow? because thats planned for the rewrite @minningguyteen2

**Comment by minningguyteen2** [comment]
sort of... the only thing that separates this idea from the one you've told me about is that these act more like coaches than actual locomotives... And these could be used temporarily if wanted.

**Comment by TrainsAndThings** [comment]
So like cab cars? also there is now a rolling stock request forum for trains you would like to see ask @EternalBlueFlame for the link

**Comment by minningguyteen2** [comment]
no....


have you ever looked at the way Hornby do there Diesel/Electric multiple units?
because thats where i got the idea from.


i never mentioned anything about cab cars... and yes i know about the rolling stock requests.

**Comment by EternalBlueFlame** [comment]
I'm a bit ahead of schedule for 014, so I may do a few for the new release, unless something goes wrong and I won't have time.
