### ISSUE TITLE
Updates And Patience

### ISSUE THREAD

**Issue by Mazaradie** [EternalBlueFlame/Traincraft-5#351]
So I would like to talk about updates to TC and patience. 
Even tho I am not part of the TC Dev team I would like to say that just because we try to get a update out once every month or so we make mistakes, and if we are forced to get a release out when we don't have everything fixed it can lead to problems such as with the Daylight in 014 and the F7 / F3 which were not finished in time to implement them fully into 014 again. (license problems with the creators kept us from using the old ones) But I guess what I'm trying to say is that, just because we get a update out when its expected that doesn't t make it a good one thats full of features that you, the player expects from us, plus if we release a version thats not fully complete it will make the situation worse for us and you because it will mean that, one we have to fix it and two, that means another update / release of the mod which you as players would have to install which could potentially lead to more problems, but overall it would delay development even more for the rewrite of TC which is already delayed to January, or so Eternal has said. so please just be patient with us while we try to bring you quality products that you guys expect.

~Sincerely

Mazaradie

**Comment by EternalBlueFlame** [comment]
2 things:
1. The rewrite has been planned for "late winter" for a while now, which would usually mean Q1 2018, or sometime around late February, so far it's still on schedule. (I seriously can't understand how no one knows the proper timeframe, unless all you guys read is rumors rather than official posts, in which case, stop it.)
2. Why is this in the issue requests?

**Comment by Fexcraft** [comment]
First time I read this, it seemt to me like an excuse to delay releases so his models can get in.

**Comment by Mazaradie** [comment]
Nah I put this here for no reason really, guess I just wanted some peeps to understand why updates take longer than expected, btw Ferds, good joke 11/10 love it.

And 2, no idea why its in requests xD

**Comment by Fexcraft** [comment]
It was hardly meant as joke, also the sentence/context structure is... rip.

**Comment by EternalBlueFlame** [comment]
closing thread at the request of the topic creator.
