### ISSUE TITLE
Switches bug

### ISSUE THREAD

**Issue by Reizzor** [EternalBlueFlame/Traincraft-5#352]
We have an issue that the switches sometimes get stuck when you have driven in a train in to the sidling, The switch stays in to the sidling even if you switch the lever back, and even if the switch visibly switches back the trains still goes in to the sidling.
This appears on all the switches but not every time we use them.

**Comment by NitroxydeX** [comment]
This is a known bug caused in specific situations. The system behind it isn't able to handle it correct anymore. This was the best possible fix. It shouldn't happen that often and switching it should help.
