### ISSUE TITLE
Daylite Train bug

### ISSUE THREAD

**Issue by Reizzor** [EternalBlueFlame/Traincraft-5#353]
Updated to Traincraft-4.3.5_014 today an now the Daylight Train-set looks like this:
![traincraft bug](https://user-images.githubusercontent.com/34731111/34240380-d036c56a-e60d-11e7-97d0-e68143663e8c.png)

**Comment by NitroxydeX** [comment]
This is intended. We had some problems with the author of them so we had to remove the models.

It's possible that there are new models with the next release.
