### ISSUE TITLE
Large error that freezes game when opening Tier 1 assembly table

### ISSUE THREAD

**Issue by dragonlife284** [EternalBlueFlame/Traincraft-5#355]
With the Traincraft-4.3.5_014 version of the mod, whenever I open a tier 1 assembly table, my game freezes for a long period of time but eventually unlocks and lets me close the table. if I do anything in the table at all it freezes and, in the log, it begins to regive the same error which is just a spam of this line:  [Server thread/INFO] [STDOUT]: [train.common.tile.TileCrafterTierI:func_70296_d:199]: 26tier 1            This line of code is dumped by the server I play on as well as in single player with this line: [Client thread/INFO]: [train.common.tile.TileCrafterTierI:func_70296_d:199]: 26tier 1              which is also just spammed rapidly enough to cause the program to freeze and potentially crash clients with weaker pc's on the private server I play on.

**Comment by dragonlife284** [comment]
this issue is caused by the line of code 			System.out.println(crafterInventory.length + "tier 1"); ,I made a request for removal of the line of code from https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/tile/TileCrafterTierI.java

**Comment by EternalBlueFlame** [comment]
whoops, that one is my bad, i'll deal with that asap.
