### ISSUE TITLE
Diesel train don't use fuel

### ISSUE THREAD

**Issue by bbosm** [EternalBlueFlame/Traincraft-5#362]
I'm sorry, it's bug from TC4 port. Could you check is it fixed in new version?
ChME3 has 5000 millibucket fuel tank (5 canisters). I put 11 canisters with fuel into it, and drive. When 5 canisters were used, another 6 canisters with fuel will never be used. Fuel just not decreasing by 80 mb every 5 seconds after 5 full canisters were used, I suppose it's bug with refueling on the go.
Sorry for English mistakes, Thank you very much for new life for this mod!

**Comment by EternalBlueFlame** [comment]
interesting, I'm not sure how no one caught wind of this bug till now. Seems that diesel trains aren't consuming fuel at all, i'll be sure to have this fixed in the next release, thanks for the heads up.

**Comment by NitroxydeX** [comment]
Fixed with https://github.com/EternalBlueFlame/Traincraft-5/commit/cb7700f3b971189de412b2506a41932d0821dba2
