### ISSUE TITLE
Traincraft-4.3.5_014 (1.7.10) Sprinting and Crouching problem

### ISSUE THREAD

**Issue by TeckWave** [EternalBlueFlame/Traincraft-5#363]
Sprinting: If I try to sprint it keeps swapping the speed at witch I travel making me swap between sprinting and walking constantly. 
(this also happens when I walk causing the same thing) 

Crouching: If I try to crouch it makes me rapidly swap between crouching and not crouching.
(this also affects creative flying stopping me from flying if I hold down space) 

other than this Thx for the Awesome mod :)

**Comment by Larky2k** [comment]
you need to ppdate to latest Version you are using outdated version

**Comment by NitroxydeX** [comment]
It shouldn't be related to Traincraft.

**Comment by EternalBlueFlame** [comment]
doublecheck your controls settings and be sure you don't have one of TC's keys bound to the sprint key.

Aside from that, it shouldn't be related to TC.
Could be another mod which would have the same potential binding issue, or it could be an issue with the key itself, so as a last resort, maybe try changing the sprint key?
