### ISSUE TITLE
My game crash when i get in a server or a world heres crash report

### ISSUE THREAD

**Issue by LeonMilk9** [EternalBlueFlame/Traincraft-5#364]
[crash-2018-02-03_17.18.20-client.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/1693209/crash-2018-02-03_17.18.20-client.txt)

**Comment by LeonMilk9** [comment]
help pls

**Comment by LeonMilk9** [comment]
anybody

**Comment by Larky2k** [comment]
your using an old version of TC update

**Comment by LeonMilk9** [comment]
btw if u see dat in the crash report there is the version of traincraft on 14

**Comment by LeonMilk9** [comment]
but i i have the lastest one

**Comment by LeonMilk9** [comment]
and still dont work

**Comment by Larky2k** [comment]
so using 015 TC and using latest Forge for 1.7.10

**Comment by LeonMilk9** [comment]
still dont work

**Comment by Larky2k** [comment]
you started a new world

**Comment by LeonMilk9** [comment]
im trying to get in a server that i created and it crash when i join

**Comment by Larky2k** [comment]
is it a fresh install of MC or a Downgrade?

**Comment by LeonMilk9** [comment]
a fresh install

**Comment by Larky2k** [comment]
what is your render distance set to?

**Comment by LeonMilk9** [comment]
its on 90

**Comment by Larky2k** [comment]
that's why drop it blow 12

**Comment by LeonMilk9** [comment]
what?

**Comment by LeonMilk9** [comment]
oh i get it now

**Comment by LeonMilk9** [comment]
let me try

**Comment by NitroxydeX** [comment]
Traincraft isn't even mentioned in the crash report itself

**Comment by LeonMilk9** [comment]
im going to send another crash report

**Comment by LeonMilk9** [comment]
nvm its working now

**Comment by LeonMilk9** [comment]
thx for help

**Comment by EternalBlueFlame** [comment]
Future reference if anyone lands on this bug, it's not TC related at all. 
It's a render buffer bug related to the vanilla render system, which we don't use at all, even before the new render we had a custom system.
It's likely a GPU bug related to minecraft itself, mods like optifine might fix it, or it could be related to a world and/or config file from other MC versions.
