### ISSUE TITLE
Does not show up in minecraft

### ISSUE THREAD

**Issue by TutorialMentor** [EternalBlueFlame/Traincraft-5#365]
I added the plugin it would rather say update it or it would not show up in the mincraft

**Comment by Tsoccerguy3** [comment]
Hmm ! , it looks like your Universal translator is broken . Please add more information

**Comment by NitroxydeX** [comment]
It seems like you don't know how to use Mods in Minecraft

**Comment by EternalBlueFlame** [comment]
This is a forge mod, it's not compatible with bukkit.
Assuming that's your issue, hard to say based on limited information provided.

**Comment by TutorialMentor** [comment]
I just installed the train craft and added it by watching a video that
shows it works. But at my game it does not shows up. The items are
completely gone. It looks like there is nothing called train craft to be
shown in mine craft. It's lost

**Comment by NitroxydeX** [comment]
Without more informations we can't help you.
Which Video did you watch? Link?

**Comment by TrainsAndThings** [comment]
Well for one you need to install minecraft forge for what ever version of traincraft you want, secondly you want to change your profile to launch the "forge" account in the minecraft launcher with traincraft in your "mods" folder then when you load up a world it should work

**Comment by NitroxydeX** [comment]
Closed due to missing user input
