### ISSUE TITLE
Train GUI does not seem to recieve some information after restart

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#37]
After restart the GUI does not seem to receive the state of the parkingBrake, or isLocoTurnedOn from Locomotive.java.

**Comment by 12345swordy** [comment]
Did you reload the values in the GUI after the restart? This is similar problem that I did back in collage.
Also, which java file are you referring to specifically?

**Comment by EternalBlueFlame** [comment]
src\main\java\train\common\api\locomotive.java
Probably relation to
src\main\java\train\client\gui\
GuiLoco2.java and GuiForney.java

Not sure about reloading the values.

Odd part is the rest of the GUI is proper, it's only for those two variables.

**Comment by 12345swordy** [comment]
"Not sure about reloading the values."
Reloading the variables of parkingBrake and isLocoTurnedOn. Anytime you changes the values that is display in the gui, you have to tell the GUI to reDisplay with the new information. I did this in C# program one time. Ether that, or the values of them got lost by the restart and resort to their default values.

**Comment by 12345swordy** [comment]
Can you go into details on reproducing the bug? I got a copy of the source and I have no idea on how to replicated, as you didn't go into details on what you did.

**Comment by Hagrud** [comment]
It's easy to reproduce this bug. You put a locomotive on your world, you go inside press R and put the brake and/or turn on the engine.
If you quit the game and reload the GUI will said "engine off" instead of "engine on".

**Comment by EternalBlueFlame** [comment]
I recently found a fix to this issue thanks to a problem in another project I have, so I'll be fixing this later today.

**Comment by EternalBlueFlame** [comment]
Fixed by [https://github.com/EternalBlueFlame/Traincraft-5/commit/2f70d4c94eb75b9c8f7f82556a218903e065f01e](https://github.com/EternalBlueFlame/Traincraft-5/commit/2f70d4c94eb75b9c8f7f82556a218903e065f01e)

Hopefully it doesn't respawn like some errors tend to....
