### ISSUE TITLE
New Skins Mark 2

### ISSUE THREAD

**Issue by TrainsAndThings** [EternalBlueFlame/Traincraft-5#371]
So i was looking thru my old submissions and such and came across a skin by mazaradie, so i  decided to remake it! i asked maz how he made his first one and he sugested i use gimp, so i did and heres a updated skin with his permission.
![workcaboose](https://user-images.githubusercontent.com/32917244/36646642-491bc66a-1a48-11e8-9e5d-7f912ad5f6dc.png)

**Comment by EternalBlueFlame** [comment]
mazaradie is banned from contributing, all content from him, by him, or made with his help, is denied.
