### ISSUE TITLE
crach on server side 

### ISSUE THREAD

**Issue by quentfr21** [EternalBlueFlame/Traincraft-5#376]
hello

after build the latest commint to see the new admin book the server crach because it try to launch guiscreen on server side (just for head up)

https://github.com/EternalBlueFlame/Traincraft-5/blob/6658b7442bfc57ace94fa44dd917a6b88fe9c444/src/main/java/train/common/adminbook/ItemAdminBook.java#L302

thanks

**Comment by EternalBlueFlame** [comment]
Awesome find, I should do more testing with separate server and client instances.

Funny enough the problem wasn't because it tried to load the screen itself on server, but rather that it tried to load it's _class_, which wouldn't exist on server.
