### ISSUE TITLE
server logger possible leak

### ISSUE THREAD

**Issue by quentfr21** [EternalBlueFlame/Traincraft-5#377]
hello 
i think fileoutputstream must be closed after write is complete (just for head up)

https://github.com/EternalBlueFlame/Traincraft-5/blob/6658b7442bfc57ace94fa44dd917a6b88fe9c444/src/main/java/train/common/adminbook/ServerLogger.java#L81

thanks in advance

**Comment by EternalBlueFlame** [comment]
great catch there.
