### ISSUE TITLE
Mallard speed?

### ISSUE THREAD

**Issue by PJXAndrews** [EternalBlueFlame/Traincraft-5#378]
I noticed that Mallard currently has a speed of 140 km/h but Coronation Scot has a speed of 183 km/h! Mallard is _the_ fastest steam locomotive ever built, so I was wondering if this is a bug or a mistake and is going to be fixed in a future version or what?

**Comment by EternalBlueFlame** [comment]
Good call.
from a couple sources the mallard was clocked at the staggering speed of 203km/h tops.
while as the coronation was 183, however they did make a modified version capable of actually hitting 202km/h.
