### ISSUE TITLE
Trains are not loading Chunks anymore

### ISSUE THREAD

**Issue by xNccPlay** [EternalBlueFlame/Traincraft-5#382]
![chunkbug](https://user-images.githubusercontent.com/1348874/39268416-305cbe48-48d0-11e8-99db-e8a1dc6dbeb7.png)

Since the 015 Update all Trains are not loading any Chunks around them anymore. In 014 this still worked for me and I saw the forced Chunks with the ChunkViewer on the right screen. I tried the disable and enable Chunkloading with the Activator tool, but this didnt helped.
The problem still exists in 016.

**Comment by NitroxydeX** [comment]
Are you sure? We lowered the actual radius to 3x3 so you might not see it.

**Comment by xNccPlay** [comment]
Yeah, I would see 9 green dots around me, like the other ones on the left side. Prior to the Updates I saw the 5x5 dots moving with the train.

**Comment by NitroxydeX** [comment]
Strange. We just changed from 5x5 to 3x3 and doing a check if a specified chunk is already loaded.

**Comment by xNccPlay** [comment]
If you need more infos, just tell me!

**Comment by xNccPlay** [comment]
![grafik](https://user-images.githubusercontent.com/1348874/39270246-c101dc9e-48d5-11e8-9549-0bd52fc506cb.png)

I've made another test.. I've placed a chunkloader on the right an set it to 4 Chunks. On the left side of the screen, you can see the red marker. Then I started a train driving around down there at 40 kmh and then ported away. 5 minutes later I ported back and the train lost connection/derailed exactly at the boarder of the chunk loader

**Comment by NitroxydeX** [comment]
We got more confirmation of that.

**Comment by Tsoccerguy3** [comment]
Read the issue i just closed 
https://github.com/EternalBlueFlame/Traincraft-5/issues/379

**Comment by whatsapp2** [comment]
I have the same problem... I made a train, then i walk outside the chunk rendering/loading, and when i came back to see my train... it derrailed and did strange things ._.

**Comment by EternalBlueFlame** [comment]
I doubled over some of the changes, and there was only one difference i found that might be doing it, so I reverted that. with any luck that should fix it, but we'll see. This mod has a bad habit of taking "should" and laughing in its face, alongside working for me but not other users.

**Comment by TrainsAndThings** [comment]
Could this have something to do with issue #379 where when you leave a chunk the train "crashes" or glitches out?

**Comment by NitroxydeX** [comment]
@TrainsAndThings I removed your first comment on purpose because it has nothing to do with eachother. The chunkloading was generally broken.
