### ISSUE TITLE
Idea!

### ISSUE THREAD

**Issue by TrainsAndThings** [EternalBlueFlame/Traincraft-5#388]
What if TC Classic was narrow gauge and TC Modern was Standard gauge? classic is small enough to be converted to narrow gauge trains while Modern is large enough to be standard gauge trains, all you need to do is make the tracks for classic a bit smaller, maybe 4 pixels less wide?

**Comment by EternalBlueFlame** [comment]
We won't be doing new gauges ourselves, but the rewrite's API will be open for 3rd party mods to add new gauges be extending our track block and tile entity.
