### ISSUE TITLE
Diesel Train keep runing on 18mB Diesel fuel from GregTech5U

### ISSUE THREAD

**Issue by Krysinski** [EternalBlueFlame/Traincraft-5#390]
Diesel Train keep runing infinity time on 18mB Diesel fuel from GregTech5U.
Traincraft 4.4.0_016

**Comment by Krysinski** [comment]
@NitroxydeX Can you public release with that fix?

**Comment by EternalBlueFlame** [comment]
We will be doing a public release of 017 generally soon, i just have one last bug I'm looking into before I send it nitro's way to look over and send out.
