### ISSUE TITLE
Issues on Airship maneuverability 

### ISSUE THREAD

**Issue by LeadKronos** [EternalBlueFlame/Traincraft-5#392]
I was using the airship on your mod and I seem to have trouble steering it. The A and D keys are unresponsive and the airship won't follow the direction of my recticle. Im curious if it a known bug or has it happened to anyone before

**Comment by EternalBlueFlame** [comment]
The A and D keys turn it slowly, assuming they havn't been mapped to something else in controls settings.
Additionally the velocity changes are relative, so one movement command more-so ads to the last rather than replacing it.
