### ISSUE TITLE
Railcraft signals still incompatible with Traincraft rails.

### ISSUE THREAD

**Issue by Urammar** [EternalBlueFlame/Traincraft-5#397]

**Comment by FloofyPeachy** [comment]
This will be the case for some time, but the #rewrite will fix this, because the track will be based off of vanilla track(which RC track supports), and the current track is not.

**Comment by NitroxydeX** [comment]
We are aware of this issue and we already had an issue about that (you could have used the search).

We don't need to let that issue open because Railcraft will use a brand new system in newer MC versions.
