### ISSUE TITLE
Train coupling bug (TC version 4.4.0_016)

### ISSUE THREAD

**Issue by TCCHS105** [EternalBlueFlame/Traincraft-5#405]
Whenever I create a link some rolling stock to a locomotive and then disconnect from my world (single player), the coupling for the locomotive and the rolling stock always comes apart upon re-logging in into my world. This only affects the first car that is directly coupled to the locomotive itself.

I also have railcraft and Buildcraft installed to compliment TC.

before (when i first create a train):
![2018-07-29_15 21 56](https://user-images.githubusercontent.com/41880305/43372645-f9b07e02-9370-11e8-8ae7-40209272678e.png)

After saving and quitting to the title and logging back in (notice the coupler.): 
![2018-07-29_15 34 49](https://user-images.githubusercontent.com/41880305/43372660-1361ac0e-9371-11e8-8219-2e7e41ad16fd.png)

another example: 
![2018-07-29_16 16 01](https://user-images.githubusercontent.com/41880305/43372667-2ebabfe0-9371-11e8-8ddd-ca833efd095c.png)

**Comment by EternalBlueFlame** [comment]
related to #250
