### ISSUE TITLE
Rails vanish and reapear while player turns and moves around , tested compile Aug 9

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#408]
Something has changed affecting graphics .While Moving or turning the rails vanish , they reappear when you look directly at them .

The problem starts in commit d6fdd5b2eeac2294bef3893f6499e7a5a09a1969

I will check later to see what code change caused this . unless someone beats me to it .lol

**Comment by EternalBlueFlame** [comment]
Should be an old bug, There's roughly a half block at each end where the track won't render because the game doesn't think it's on screen.
The alternative is to render whether or not it's on screen, which is very bad for FPS...

**Comment by Tsoccerguy3** [comment]
Eternal , If you want to look at commit d6fdd5b2eeac2294bef3893f6499e7a5a09a1969 to see what started causing this . I will look at it later to narrow it down if you haven't already fixed it . Its a really bad bug

**Comment by Tsoccerguy3** [comment]
I suspect its your edit here
 src/main/java/train/common/core/util/TraincraftUtil.java

**Comment by EternalBlueFlame** [comment]
That class has nothing to do with rendering or the hitbox of the rails that defines it's culling in the world render.

Are you sure you're not running any other mods that could potentially be messing up the render calls? There's already known issues of other mods making the rails render improperly, and the fixes thus far haven't worked fully.

**Comment by EternalBlueFlame** [comment]
okay, i can confirm the issue is worse than usual, but i can also confirm it has to do with the hitbox of the rail block, so i may be able to get a fix for this tonight.

**Comment by Tsoccerguy3** [comment]
Fixed it
src/main/java/train/common/blocks/BlockTCRail.java

revert back to
public AxisAlignedBB getCollisionBoundingBoxFromPool(World par1World, int par2, int par3, int par4) {
		return null;

**Comment by EternalBlueFlame** [comment]
That fixes that issue and adds back the crash related to the null hitbox.

**Comment by EternalBlueFlame** [comment]
with any luck that should be a more proper fix...

**Comment by Tsoccerguy3** [comment]
Fixed ! and a small FPS boost

Thanks Eternal

Closed !
