### ISSUE TITLE
Worldgen for pre-existing world that did not have TC

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#41]
most people already have modded Maps with some mods in it. We should think about using RetroGen the first time TC joins a already generated map and save somewhere the state so that we don't create the ores over and over again if the world loads up.
Requested by @NitroxideX

we can manage it via boolean in config file that way we can be sure it's only done once unless the user wants it to be done again.

**Comment by FirEmerald** [comment]
Added in my latest pull request

**Comment by NitroxydeX** [comment]
Closed via 9b934d6822bbee47adbbc0c3351703a72fbefee6
