### ISSUE TITLE
server crash after run disel loco

### ISSUE THREAD

**Issue by Krysinski** [EternalBlueFlame/Traincraft-5#410]
[crash-2018-08-12_01.32.37-server.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/2280599/crash-2018-08-12_01.32.37-server.txt)

**Comment by EternalBlueFlame** [comment]
fixed in commit https://github.com/EternalBlueFlame/Traincraft-5/commit/8ff03fa218b6cbf8b202135c7f98a35d3cf99630

**Comment by Krysinski** [comment]
OK. I need waiting fix in next release, right?

**Comment by EternalBlueFlame** [comment]
yes, it shouldn't be too long this time
