### ISSUE TITLE
Chat Issue from #402

### ISSUE THREAD

**Issue by xNccPlay** [EternalBlueFlame/Traincraft-5#413]
Since you fixed the permission issue with the stake in 017, everytime I place a loco or wagon and try to lock it with the wrench, it says "You are not the Owner" and in the next line then "locked". Its still locked and everything works fine, its just the irritating chat message.

Greetings
xNccPlay

**Comment by EternalBlueFlame** [comment]
already fixed for 018, the issue is primarily in singleplayer and some older server managers where the get player username function is different than normal.

**Comment by xNccPlay** [comment]
Okay I noticed this problem on my thermos server, but if you already fixed it, we can close this here :P

**Comment by xNccPlay** [comment]
Hey guys, today I updated to 019 and noticed, that this problem still exists..

**Comment by xNccPlay** [comment]
in 020-alpha now the wrong message is gone but instead now "locked" or "unlocked" is shown twice in chat.
