### ISSUE TITLE
Train Workbench bug

### ISSUE THREAD

**Issue by zennui-zz** [EternalBlueFlame/Traincraft-5#415]
I have looked in every repository and every thread I could find regarding Traincraft bugs and I could not find this issue. I am running 4.4.0, which was released on August 3, 2018. I just updated this today as I was running 4.3.2 from May, 2017 and thought that the newest version might have fixed this bug; however it has not. So, I thought I would bring it to your attention, especially because it involves the backbone of the whole mod losing its functionality completely. 
Whenever I attempt to craft anything- and i mean ANYTHING- that must be crafted in the Train Workbench, no product appears in the right slot. I place every piece of any recipe in the correct slots with the correct items and nothing appears. I've waited two hours while I went to the gym to see if it was just a latency issue, but when I came home, nothing was in the product slot still. I've tried steel frames, wheels, fireboxes, boilers, distillers, and any train part that I could build from parts that didn't require the Train Workbench. Nothing works. Also, the mod has never made my game crash.
A response would be most appreciated, and maybe I am just daft and doing something basic wrong, but I do not think so myself.
Thank you.

zennui

**Comment by NitroxydeX** [comment]
Hi zennui,

thanks for heading towards us. That's an interesting bug because the train workbench works fine for all other people.
To investigate this we need more information about your Minecraft setup, which other mods you use besides Traincraft, your Java version and so on.

**Comment by zennui-zz** [comment]
@NitroxydeX Hey, thanks for the quick reply; I just got home from work. I made a sort of custom modpack from the Unabridged pack on ATLauncher, so my Minecraft version is 1.7.10. I'm running jre1.8.0_161 for Java. Forge version is 10.13.4.1614, ostensibly for 1.7.10. Another thing I forgot to mention is that I had previously made some Santa Fe engines and passenger cars, and all the parts for them in the Train Workbench, before it stopped working; however, now nothing works.
I would post my entire pack or even just the list of mods, but GitHub doesn't seem to support .jar or .rar files, so unless you'd like me to type all the names out, could I possibly send the .rar file to an email? 
Personally, I think it might be some kind of conflict between Traincraft and one of Reika's mods, for I have RotaryCraft, ReactorCraft. ElectriCraft and Chromaticraft all in my pack and they've caused more conflicts than anything else for me in the past.

Thank you again.

**Comment by NitroxydeX** [comment]
@zennui Hey thanks for the information. Which one exactly do you mean? SD40/70? Or other ones? Did you changed anything after you made the Santa Fe engines, added mods or something? If so could you try in a fresh world with your modpack? If not: you could also post a screenshot of your modlist.

**Comment by EternalBlueFlame** [comment]
More likely than not its a recipe conflict related to a tweaking mod such as minetweaker, _OR_ a corrupt tile entity for the workbench that's being used, placing a new one in a different chunk may produce different results.
Far as I know there's no incompatibilities with Reika's mods, although they do have a good history of being a pain to work with.

Just to be sure you are running revision 016 or 017 of TC right?

also a nice little cheat for windows users, you can hold left shift and right click in a folder to open CMD/powershell then type `dir` and hit enter to get a text list of all the mods in the folder for copy-paste.

**Comment by zennui-zz** [comment]
Well here's a list of my mods, thanks @EternalBlueFlame. And sorry, I don't know how to insert a spoiler in GitHub. I do have MineTweaker, but is there anything else that could cause a conflict as well? And I'm running revision 017 of TC. And to @NitroxydeX , I made the SD40, and I added no mods nor did I change anything after I made them. I literally made the two engines, the two passenger cars and then tried to make a tank car but all the recipes stopped working. Again, thank you.

d-----         8/7/2018   4:22 PM                1.7.10
d-----         8/6/2018   6:37 PM                carpentersblocks
d-----         8/6/2018   7:17 PM                railcraft
d-----         8/6/2018   6:07 PM                Reika
-a----         8/3/2018  10:58 AM          77838 1.7.10-ExpandedIndustry-15.26.1a.jar
-a----         8/5/2018  11:31 AM       22037852 1.7.10_AM2-1.4.0.008.jar
-a----         8/3/2018   4:36 PM         979016 advancedgenetics-1.7.10-1.5.9.jar
-a----        8/11/2018   4:13 PM         501229 ae2stuff-0.5.0.56-mc1.7.10.jar
-a----         8/6/2018   5:42 PM         919554 AncientTrees-1.7.10-1.6.4.jar
-a----         8/5/2018  11:42 AM          14859 AnimationAPI-1.7.10-1.2.4.jar
-a----         8/1/2018  11:07 AM         211318 AOBD-2.9.2.jar
-a----        8/10/2018   1:49 AM         106587 AppleCore-mc1.7.10-3.1.1.jar
-a----         8/4/2018   6:45 PM        2526302 appliedenergistics2-rv2-stable-10.jar
-a----         8/6/2018   5:42 PM         680545 arcane_engineering-0.2.7.jar
-a----         8/5/2018  11:30 AM        1090188 AuraCascade-557.jar
-a----         8/6/2018   5:42 PM        1503184 bdlib-1.9.4.109-mc1.7.10.jar
-a----        1/16/2018   1:24 AM        5452316 BiblioCraft[v1.11.7][MC1.7.10].jar
-a----         8/3/2018   3:23 PM         265289 BiblioWoods[BiomesOPlenty][v1.9].jar
-a----         8/3/2018   3:23 PM         330607 BiblioWoods[Forestry][v1.7].jar
-a----         8/6/2018   5:42 PM         771107 BigReactors-0.4.3A.jar
-a----         8/6/2018   5:42 PM        4562769 binnie-mods-1.7.10-2.0.22.7.jar
-a----         8/1/2018  11:07 AM        5755198 BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
-a----        1/16/2018   1:24 AM         779930 BloodArsenal-1.7.10-1.2-5.jar
-a----         8/6/2018   5:42 PM        9198412 BloodMagic-1.7.10-1.3.3-17.jar
-a----         8/6/2018   5:42 PM       15977344 Botania r1.8-249.jar
-a----         8/3/2018  10:59 AM          92269 BrandonsCore-1.0.0.12.jar
-a----         8/6/2018   5:42 PM        2705733 buildcraft-7.1.23.jar
-a----         8/6/2018   5:42 PM         259292 buildcraft-compat-7.1.7.jar
-a----         8/4/2018   5:32 PM        1838200 Calculator-1.7.10-1.9.10.jar
-a----         8/6/2018   5:42 PM         510164 Carpenters Blocks v3.3.8.1 - MC 1.7.10.jar
-a----         8/6/2018   5:42 PM         522519 catwalks-2.0.4.jar
-a----         8/6/2018   5:42 PM         106701 ChickenChunks-1.7.10-1.3.4.19-universal.jar
-a----         8/6/2018   5:42 PM        6378920 Chisel-2.9.5.11.jar
-a----         8/3/2018  10:58 AM           7155 ChiselFacades-1.7.10-2.12-chiselteam.jar
-a----        1/16/2018   1:24 AM           5386 ChiselTones-1.7.10-1.0-3.jar
-a----        8/17/2018   9:14 PM      104228700 ChromatiCraft+1.7.10+V21b.jar
-a----         8/1/2018  11:08 AM         145782 CodeChickenCore-1.7.10-1.0.7.47-universal.jar
-a----        1/16/2018   1:24 AM        1230511 CoFHCore-[1.7.10]3.1.4-329.jar
-a----        6/30/2018   5:20 PM         305688 CoFHLib-[1.7.10]1.2.1-185.jar
-a----         8/6/2018   5:42 PM          91325 craftingtweaks-mc1.7.10-1.0.88.jar
-a----         8/6/2018   5:42 PM         112314 CustomThings-MC1.7.10-0.0.3-55.jar
-a----         8/6/2018   5:42 PM       13365882 Decocraft-2.4.2_1.7.10.jar
-a----         8/6/2018   5:42 PM          34518 defaultkeys-mc1.7.10-1.0.28.jar
-a----         8/3/2018  10:59 AM        4874507 Draconic-Evolution-1.7.10-1.0.2h.jar
-a----        8/17/2018   9:13 PM        3403283 DragonAPI+1.7.10+V21c.jar
-a----        8/17/2018   9:14 PM         472515 ElectriCraft+1.7.10+V21b.jar
-a----        6/30/2018   5:20 PM         732744 Enchiridion 2-1.7.10-2.0.2a.jar
-a----         8/1/2018  11:08 AM         467824 EnderCore-1.7.10-0.2.0.39_beta.jar
-a----         8/6/2018   5:42 PM        4756103 EnderIO-1.7.10-2.3.0.429_beta.jar
-a----         8/6/2018   5:42 PM        2467999 EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.13.56_beta.jar
-a----         8/6/2018   5:42 PM         145063 EnderStorage-1.7.10-1.4.7.37-universal.jar
-a----         8/6/2018   5:42 PM         724840 EnderTech-1.7.10-0.3.2.405.jar
-a----        6/30/2018   5:20 PM          16464 ExtendedPotions-MC1.7.10-1.2.jar
-a----         8/6/2018   5:42 PM        1481351 ExtraCells-1.7.10-2.3.14b200.jar
-a----         8/6/2018   5:42 PM       11557124 ExtraTiC-1.7.10-1.4.6.jar
-a----         8/6/2018   5:42 PM        2149827 extrautilities-1.2.12.jar
-a----         8/6/2018   5:42 PM         183482 fastcraft-1.25.jar
-a----         8/6/2018   5:42 PM          54238 fognerf-1.7.10-0.4.jar
-a----         8/6/2018   5:42 PM         647020 Forbidden Magic-1.7.10-0.575.jar
-a----         8/6/2018   5:42 PM        3322286 forestry_1.7.10-4.2.16.64.jar
-a----         8/6/2018   5:42 PM         776742 GardenStuff-1.7.10-1.7.0.jar
-a----         8/6/2018   5:42 PM        1976556 gendustry-1.6.4.135-mc1.7.10.jar
-a----        6/30/2018   5:20 PM        1453732 generators-0.9.20.123-mc1.7.10.jar
-a----         8/1/2018  11:08 AM        1685933 gilded-games-util-1.7.10-1.10.jar
-a----        1/16/2018   1:24 AM        2417353 growthcraft-1.7.10-2.7.2-complete.jar
-a----         8/1/2018  11:08 AM         200078 Guide-API-1.7.10-1.0.1-29.jar
-a----         8/6/2018   5:42 PM         283132 Hats-4.0.1.jar
-a----         8/6/2018   5:42 PM           6552 HelpFixer-1.0.7.jar
-a----        8/10/2018   1:46 AM         112389 HungerOverhaul-1.7.10-1.0.0.jenkins104.jar
-a----         8/6/2018   5:42 PM         213084 iChunUtil-4.2.3.jar
-a----         8/6/2018   5:42 PM           2649 IDCleaner-1.7.10-1.0.jar
-a----         8/6/2018   5:42 PM        3610468 ImmersiveEngineering-0.7.7.jar
-a----         8/6/2018   5:42 PM         302059 immersiveintegration-0.6.8.jar
-a----         8/1/2018  11:08 AM         126448 INpureCore-[1.7.10]1.0.0B9-62.jar
-a----         8/6/2018   5:42 PM         226485 InventoryTweaks-1.59j-dev.jar
-a----         8/6/2018   5:42 PM         354672 IronBackpacks-1.7.10-1.2.20.jar
-a----         8/6/2018   5:42 PM         158104 ironchest-1.7.10-6.0.62.742-universal.jar
-a----         8/6/2018   5:42 PM          25198 ItemSearch-1.4.0.jar
-a----         8/1/2018  11:08 AM         373500 IvToolkit-1.2.1.jar
-a----         8/6/2018   5:42 PM         445166 Jabba-1.2.2_1.7.10.jar
-a----         8/6/2018   5:42 PM        1717502 journeymap-1.7.10-5.1.4p1-unlimited.jar
-a----         8/1/2018  11:08 AM          60408 KoreSample-1.7.10-1.3.2.jar
-a----        8/17/2018   9:09 PM        2416646 magneticraft-0.6.1-final.jar
-a----        6/30/2018   5:20 PM         648081 malisiscore-1.7.10-0.14.3.jar
-a----         8/6/2018   5:42 PM        1645689 malisisdoors-1.7.10-1.13.2.jar
-a----        1/16/2018   1:24 AM         202458 Mantle-1.7.10-0.3.2b.jar
-a----         8/5/2018   3:05 PM        6847869 Mariculture-Deluxe-1.7.10-1.3.0-6.jar
-a----        1/16/2018   1:24 AM       15916456 MatterOverdrive-1.7.10-0.4.2.jar
-a----         8/1/2018  11:08 AM         187881 mcjtylib-1.8.1.jar
-a----         8/6/2018   5:42 PM       15392975 Mekanism-1.7.10-9.1.1.1031.jar
-a----         8/6/2018   5:42 PM         253388 MekanismGenerators-1.7.10-9.1.1.1031.jar
-a----         8/6/2018   5:42 PM          31520 MekanismTools-1.7.10-9.1.1.1031.jar
-a----        1/16/2018   1:24 AM        1102002 Minechem-1.7.10-5.0.5.406.jar
-a----         8/6/2018   5:42 PM        1767447 MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar
-a----         8/6/2018   5:42 PM         927376 MineTweaker3-1.7.10-3.0.10B.jar
-a----        6/30/2018   5:20 PM        1642057 ModularPowersuits-1.7.10-0.11.1.114.jar
-a----         8/6/2018   5:42 PM          69848 MoreChisels-1.7.10-1.0-28.jar
-a----         8/6/2018   5:42 PM          18767 Morpheus-1.7.10-1.6.21.jar
-a----         8/6/2018   5:42 PM          51898 MouseTweaks-2.4.4-mc1.7.10.jar
-a----         8/6/2018   5:42 PM         154694 movingworld-1.7.10-1.8.1.jar
-a----         8/6/2018   5:42 PM        1728686 MrCrayfishFurnitureModv3.4.7(1.7.10).jar
-a----         8/6/2018   5:42 PM         103007 neiaddons-1.12.15.41-mc1.7.10.jar
-a----         8/6/2018   5:42 PM         197046 NEIIntegration-MC1.7.10-1.1.2.jar
-a----        1/16/2018   1:24 AM          80825 NetherOres-[1.7.10]2.3.2B1-25.jar
-a----         8/6/2018   5:42 PM           9433 NoNausea-MC1.7.10-1.0.jar
-a----         8/5/2018   1:35 PM          55390 NotEnoughIDs-1.4.3.4.jar
-a----        1/16/2018   1:24 AM         513136 NotEnoughItems-1.7.10-1.0.5.120-universal.jar
-a----         8/6/2018   5:42 PM          29473 NotEnoughKeys-1.7.10-3.0.0b45-dev-universal.jar
-a----         8/6/2018   5:42 PM         226574 NotEnoughResources-1.7.10-0.1.0-128.jar
-a----        8/17/2018   9:09 PM        4139801 NuclearCraft-1.9g--1.7.10.jar
-a----         8/3/2018  10:59 AM          93964 Numina-0.4.1.105.jar
-a----         8/6/2018   5:42 PM        2799187 OpenBlocks-1.7.10-1.6.jar
-a----         8/1/2018  11:08 AM        2259572 OpenModsLib-1.7.10-0.10.jar
-a----         8/6/2018   5:42 PM         894904 OptiFine_1.7.10_HD_U_C1.jar
-a----         8/1/2018  11:08 AM          23853 p455w0rdslib-1.7.10-1.0.4.jar
-a----        6/30/2018   5:20 PM        2482753 Pam's HarvestCraft 1.7.10Lb.jar
-a----         8/6/2018   5:42 PM         107504 PlanetguyLib-1.9.2.jar
-a----         8/6/2018   5:42 PM        1748703 plantmegapack-4.33-1.7.10-1492.jar
-a----         8/6/2018   5:42 PM        6464732 PneumaticCraft-1.7.10-1.12.7-152-universal.jar
-a----         8/6/2018   5:42 PM        3742396 Railcraft_1.7.10-9.12.2.1.jar
-a----         8/6/2018   5:42 PM        2818840 RandomThings-2.2.4.jar
-a----        8/17/2018   9:14 PM        3649784 ReactorCraft+1.7.10+V21b.jar
-a----         8/6/2018   5:42 PM          23838 ReAuth-3.5.0.jar
-a----         8/6/2018   5:42 PM         490073 RedstoneArmory-1.7.10-1.2.0-41.jar
-a----         8/6/2018   5:42 PM         317048 RedstoneArsenal-[1.7.10]1.1.3B1-94.jar
-a----         8/6/2018   5:42 PM        1380083 RefinedRelocation-mc1.7.10-1.1.34.jar
-a----         8/6/2018   5:42 PM         609732 RemainInMotion-2.8.9.jar
-a----         8/6/2018   5:42 PM          13037 ResourceLoader-MC1.7.10-1.3.jar
-a----         7/1/2018  12:16 AM         102872 RFExpansion-2.3.26.jar
-a----         8/6/2018   5:42 PM        3393513 rftools-4.23.jar
-a----         8/6/2018   5:42 PM         233851 Roadblocks-1.7.10-2.1.8.jar
-a----        8/17/2018   9:14 PM        8351250 RotaryCraft+1.7.10+V21b.jar
-a----         8/6/2018   5:42 PM        1503535 Sanguimancy-1.7.10-1.1.9-35.jar
-a----         8/6/2018   5:42 PM         608053 SimplyJetpacks-MC1.7.10-1.5.3.jar
-a----         8/4/2018   5:33 PM         321931 SonarCore-1.7.10-1.1.3.jar
-a----         8/6/2018   5:42 PM        3800566 Tainted-Magic-r7.82.jar
-a----         8/6/2018   5:42 PM          17202 tcinventoryscan-mc1.7.10-1.0.11.jar
-a----         8/6/2018   5:42 PM         116878 tcnodetracker-1.7.10-1.1.2.jar
-a----         8/6/2018   5:42 PM        5606642 TConstruct-1.7.10-1.8.8.build991.jar
-a----        1/16/2018   1:24 AM        1273799 Technomancy - 0.12.5 - 1.7.10.jar
-a----         8/6/2018   5:42 PM       12565807 Thaumcraft-1.7.10-4.2.3.5.jar
-a----         8/6/2018   5:42 PM          68794 thaumcraftneiplugin-1.7.10-1.7a.jar
-a----         8/3/2018  10:58 AM        1982603 ThaumicExploration-1.7.10-1.1-53.jar
-a----        6/30/2018   5:20 PM        2456405 thaumichorizons-1.7.10-1.1.9.jar
-a----        1/16/2018   1:24 AM        2141043 ThaumicTinkerer-2.5-1.7.10-164.jar
-a----         8/5/2018   3:35 PM       74812411 TheBetweenlands-1.0.6-alpha-universal.jar
-a----        1/16/2018   1:24 AM         632485 ThermalDynamics-[1.7.10]1.2.1-172.jar
-a----        1/16/2018   1:24 AM        2614932 ThermalExpansion-[1.7.10]4.1.5-248.jar
-a----        1/16/2018   1:24 AM        2316321 ThermalFoundation-[1.7.10]1.2.6-118.jar
-a----         8/2/2018   5:05 PM          13910 ThermalSmeltery-2.0.2.jar
-a----         8/6/2018   5:42 PM          52002 TiCTooltips-mc1.7.10-1.2.5.jar
-a----         8/6/2018   5:42 PM        5667113 tinker_io-1.7.10-release 1.5.0.jar
-a----         8/6/2018   5:42 PM         221769 TMechworks-1.7.10-0.2.15.106.jar
-a----        8/19/2018  10:52 PM       15611005 Traincraft-4.4.0_017.jar
-a----         8/1/2018  11:08 AM         312717 TravellersGear-1.7.10-1.16.6.jar
-a----         8/6/2018   5:42 PM        3682125 twilightforest-1.7.10-2.3.7.jar
-a----        1/16/2018   1:24 AM         119475 VeinMiner-1.7.10-0.36.0.49628a7f13.jar
-a----        6/30/2018   5:20 PM        2090259 VoltzEngine-1.7.10-1.10.4b436.jar
-a----         8/6/2018   5:42 PM         544821 Waila-1.5.10_1.7.10.jar
-a----         8/6/2018   5:42 PM          28800 WailaHarvestability-mc1.7.10-1.1.6.jar
-a----         8/6/2018   5:42 PM          77506 WAILAPlugins-MC1.7.10-0.2.0-25.jar
-a----         8/6/2018   5:42 PM        7009956 witchery-1.7.10-0.24.1.jar
-a----         8/6/2018   5:42 PM        4217711 WitchingGadgets-1.7.10-1.1.10.jar
-a----         8/6/2018   5:42 PM        1361162 YeGamolChattels-1.1.2.jar
-a----         8/6/2018   5:42 PM         556982 Ztones-1.7.10-2.2.1.jar
-a----        1/16/2018   1:23 AM          27281 [1.7.10]ArmorStatusHUD-client-1.28.jar
-a----         8/6/2018   5:42 PM          48756 [1.7.10]BugfixMod-universal-2.5.0.jar
-a----         8/6/2018   5:42 PM          16873 [1.7.10]StartingInventory-universal-1.7.10.r03.jar
-a----         8/3/2018  10:58 AM          94792 [1.7.10]Treecapitator-universal-2.0.4.jar

**Comment by NitroxydeX** [comment]
Please try placing an other workbench some chunks away and check if recipes still not working - make sure you have the right Tier of workbench for your recipes.

If this is still not working please try a new world and check if the problem still persists.

**Comment by EternalBlueFlame** [comment]
Nitro brings up a good point that I forget. The NEI recipes system is broken, and disabled by default now, so be sure to use the Traincraft Guide to find the recipes.

as for reasons other than your minetweaker settings, it could be the IDCleaner mod, our registration systems and crafters aren't exactly standardized methods so that _could_ be throwing it off and making it clean our systems.

That said, I'd try the other two options (making a new workbench a good distance away, and using the TC book instead of NEI), before tossing out mods.

**Comment by zennui-zz** [comment]
Moving it to a different chunk seemed to fix the recipes, such as a Lantern, that didn't use any Traincraft specific material, such as Steel or Graphite. However, when I tried to make a part using Steel, it still didn't work. So I tried using Traincraft steel by transmuting a Mekanism steel ingot to a Traincraft steel ingot in Mekanism's Oredictionificator, and that seemed to work, so now I should be able to craft anything, I just have to use TC steel now. Thank you guys.

**Comment by NitroxydeX** [comment]
So something is conflicting with the OreDictionairy of Forge. That's the way how we get Steel (Strange enough it's working with our own steel ingots)

**Comment by EternalBlueFlame** [comment]
It looks like the hearth furnace doesn't use the ore directory for steel.
and the crafting table doesn't use the ore directory for iron. (I still find it retarded beyond reason that other mods implement a vanilla item).

I'll make a push later today to fix these two (I'm already half done but now i gotta run an errand and for some reason it can't just wait 20 minutes).
