### ISSUE TITLE
Make Lantern acceptable for Dye

### ISSUE THREAD

**Issue by NitroxydeX** [EternalBlueFlame/Traincraft-5#42]
Nothing left to say. Why can't we dye it?

**Comment by EternalBlueFlame** [comment]
Wasin't this supposed to be a feature by default?
![53807959](https://cloud.githubusercontent.com/assets/9969122/16851063/6f8b325c-49c7-11e6-8ef9-7ac0870aab58.jpg)

**Comment by NitroxydeX** [comment]
hahaha. Well It spawns random colors and cant be dyed and It worked that way in 1.6.4 but its... stupid? :D

**Comment by EternalBlueFlame** [comment]
okay, if it was that way in 1.6.4 then this would be an enhancement.

**Comment by NitroxydeX** [comment]
So this was actually in the Game with the Wrench because it uses Hex-Color-Code instead of normal vanilla color codes. This is now fixed.
