### ISSUE TITLE
Removing Cars with Plugins doesnt remove the chunkloading entry

### ISSUE THREAD

**Issue by xNccPlay** [EternalBlueFlame/Traincraft-5#421]
Today I recognized, that after I use the essentials command /killall minecarts, the carts were successfully removed, but the chunks are still kept loading, as if the carts were still there. If I destroy the carts manually by hand, the chunkloading stops normal.

Greetings

**Comment by EternalBlueFlame** [comment]
This is a bug on forge essential's end, as the killall command bypasses normal entity removal methods and thus doesn't tell forge to unload the entity's bound chunks.

However, if I'm not mistaken chunkloading isn't saved, so rebooting the game/server should fix it.

**Comment by EternalBlueFlame** [comment]
another thought on the topic, one of our more popular servers uses the command ` /remove minecart <radius>` and doesn't have any noticible chunkloading issues, so that may be another option worth looking into, maybe that method has more proper entity removal methods.

**Comment by xNccPlay** [comment]
Thanks for the info, I'll try that command later and tell you, if that worked better :)

**Comment by xNccPlay** [comment]
Okay, even with the remove command, it doesn't work instantly, but you are right, after a server restart, the chunkloading from already removed carts stops, thank you :) (and /remove is way better than /killall cause of the radius)
