### ISSUE TITLE
Freight Gondola DB only accepting Woodstuff

### ISSUE THREAD

**Issue by xNccPlay** [EternalBlueFlame/Traincraft-5#423]
Hey guys, today I noticed, that the Freight Gondola DB is only accepting Woodstuff.
I tested many different items and blocks like iron ingots, diamonds, aswell as sand, gravel or dirt and stone, but nothing exept wood is working
![2018-08-31_16 08 02](https://user-images.githubusercontent.com/1348874/44917329-617a9f00-ad38-11e8-8891-9d9e1aa484f2.png)
![2018-08-31_16 08 13](https://user-images.githubusercontent.com/1348874/44917332-617a9f00-ad38-11e8-9667-c8bd8d3fb7ae.png)
TC version 4.4.0_017

greetings xNccPlay

**Comment by EternalBlueFlame** [comment]
this was fixed in commit https://github.com/EternalBlueFlame/Traincraft-5/commit/5f61bfeecdb5be7d31e0f212fc3c64a9d4946207 for the upcoming 018 release

**Comment by xNccPlay** [comment]
Okay thanks, than sorry for th duplicated post :)
