### ISSUE TITLE
Train GUI for 4-4-0

### ISSUE THREAD

**Issue by LivelyTheEpicLizard** [EternalBlueFlame/Traincraft-5#430]
When I go in the locomotive and I press R the GUI won't open.

**Comment by EternalBlueFlame** [comment]
Check your key mappings in the controls options menu.
You may have another mod bound to the R key that's conflicting with it, or you may have unknowingly re-mapped it to another key.
If there is a conflict it will be red like my idle keybind.

![screenshot from 2018-09-21 15-05-42](https://user-images.githubusercontent.com/9969122/45903607-ea24b200-bdaf-11e8-9fbd-406be1308496.png)

**Comment by LivelyTheEpicLizard** [comment]
thanks it worked
