### ISSUE TITLE
Traincraft Guide crashes

### ISSUE THREAD

**Issue by xNccPlay** [EternalBlueFlame/Traincraft-5#443]
Hey guys,

today I was looking for any tutorial for these new MTC Blocks. I had the idea to look in your "Traincraft Guide" item. While I was going throw the pages my game crashed two times while trying to change to page 52.
I've added the corresponding crashlogs to this post.

greetings,
xNccPlay

[crash-2019-01-11_00.41.40-client.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/2747502/crash-2019-01-11_00.41.40-client.txt)
[crash-2019-01-11_00.52.34-client.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/2747503/crash-2019-01-11_00.52.34-client.txt)

**Comment by NitroxydeX** [comment]
We still don't know why this happens. It got already reported in the bugtracker on discord but I couldn't reproduce it. So it has to be some sort of mod conflict.

**Comment by xNccPlay** [comment]
Any hint, which type of mod could cause the problem? We don't have many mods in our modpack. Maybe its Optifine? I'll try a bit later and let you know :)

**Comment by NitroxydeX** [comment]
Look into the discord. I've pinged you about it. It's not Optifine. I already tried that.

**Comment by NitroxydeX** [comment]
possible cause: Computercraft

**Comment by NitroxydeX** [comment]
For whatever reason it fails here:
`at train.client.gui.GuiRecipeBook.drawWorkBenchRecipe(GuiRecipeBook.java:620)
at train.client.gui.GuiRecipeBook.func_73863_a(GuiRecipeBook.java:536)`

It's failing to display the output Item Stack which is tile.rail it this case (Minecrafts normal rail).
It doesn't fail without Computercraft. Somehow it seems like they are messing up something in the renderer.

**Comment by EternalBlueFlame** [comment]
It seems like a bug with the MTC blocks, the blocks didn't register items.
can confirm for sure it's an issue on our end, I should be able to have it fixed tomorrow.
