### ISSUE TITLE
can't make coal dust in train workbench

### ISSUE THREAD

**Issue by catbryce** [EternalBlueFlame/Traincraft-5#445]
i have been trying to make coal dust the way i always have is it crafted differently now

**Comment by NitroxydeX** [comment]
have u looked into the guide?

**Comment by catbryce** [comment]
the book dose not say 
![image](https://user-images.githubusercontent.com/45723498/51076282-c41f6800-1653-11e9-88a5-fc077e6b8d12.png)
this worked before the update

**Comment by NitroxydeX** [comment]
It's disabled by the config file change "MAKE_MODPACKS_GREAT_AGAIN" to false. and the recipe will work again. This was changed versions ago.

**Comment by catbryce** [comment]
it is set set to false and i still cant. its set to false by default

**Comment by NitroxydeX** [comment]
There is a mistake in the recipe call regarding the coal dust
