### ISSUE TITLE
Train Buffer

### ISSUE THREAD

**Issue by maehschaf** [EternalBlueFlame/Traincraft-5#45]
Hi,
It seems like you are not abled to place Train Buffers which, I think, has to do something with the canPlaceBlockAt method inside BlockStopper. It always returns false and since I am TOTALLY new to forge I couldn't find out how to fix it... By the way, what is this isSideSolid method supposed to check? I hope I was abled to help (sry for my english...), I think I will leave a post at meansoft so people know that something is moving. Good luck!

**Comment by NitroxydeX** [comment]
This Issue can be closed since it's already fixed in the next Pull Request. It's also mentioned in #19

**Comment by maehschaf** [comment]
Oh sry

**Comment by NitroxydeX** [comment]
yes. so just press the close issue button ^^
And about Meansoft: Brutal knows about this. We have contact to him. So you don't need to post to him.
