### ISSUE TITLE
Train derailment in curves

### ISSUE THREAD

**Issue by xNccPlay** [EternalBlueFlame/Traincraft-5#451]
Hey guys,

I have another problem with the traincraft tracks. I didn't know since which version, but we noticed, that trains are derailing in curves, if the last block before the curve is a vanilla track. If we replace the last track before the curve, all went fine. This doesn't happens with switches or slopes, but with all 3 curves.

![2019-01-13_19 47 29](https://user-images.githubusercontent.com/1348874/51089367-3b481f80-176c-11e9-86df-1188a527ad9e.png)
![2019-01-13_19 47 36](https://user-images.githubusercontent.com/1348874/51089368-3be0b600-176c-11e9-9916-2fe0918d6eb4.png)

greetings, xNccPlay

**Comment by NitroxydeX** [comment]
We do recommend this anyway. I would recommend placing at least a medium or long straight from us before going into a curve.

even if switching between the tracks is working there is no gurantee it will always work

**Comment by xNccPlay** [comment]
Okay. I'm just wondering, because in an earlier version that worked fine. We are using as minor TC tracks as possible to prevent to many FPS drops :x

**Comment by EternalBlueFlame** [comment]
Nitro's method is correct, it's just an issue with these rails as a whole. if it does work, it's more or less luck.

Now there are also some rare cases where the rails lose part of the NBT data, so replacing them might help, or it might not.

Unfortunately there's nothing we can do about this stuff until the rewrite.

**Comment by xNccPlay** [comment]
Hm okay, then I have to deal with it :D

Thank you anyway! :)
