### ISSUE TITLE
Solution - Immersive Engineering Diesel

### ISSUE THREAD

**Issue by agonija** [EternalBlueFlame/Traincraft-5#459]
Hey there, 

Sorry that I didn't write that earlier.
Traincraft isn't compatible with the Biodiesel from Immersive Engineering. I change that on my own every update, but all you have to do is an entry in /src/main/java/train/common/api/LiquidManager.java.

Greetings Agonija

**Comment by NitroxydeX** [comment]
Thanks for the headsup.

Placing this here to remember it
`biodiesel = FluidRegistry.getFluid("biodiesel");`
