### ISSUE TITLE
High Star Switch Stand recipe?

### ISSUE THREAD

**Issue by Ghost1138** [EternalBlueFlame/Traincraft-5#460]
I was playing in survival mode and I noticed that the Guide doesn't have the High Star Switch Stand recipe anywhere. Is there any recipe for this switch? If there's one, could you tell me how to craft it? Thanks in advance.

By the way, I think the "Steel: Something harder!" achievement is bugged because I've made a lot of Steel ingots already and the achievement is still incomplete, and I'm not confusing them with Iron ingots. I also tried dropping the steel ingots and taking them back. I'm not sure if I'm doing something wrong. And excuse my english.

**Comment by EternalBlueFlame** [comment]
The steel achievement requires crafting it from our hearth furnace, it's more aimed at crafting it using our stuff, and less at having it.
But setup dependant there's a lot more efficient ways to get it than ours.

And the switch stand recipe is:
[empty] | [lever] | [empty]
[empty] | [iron ingot] | [empty]
[empty] | [stick] | [empty]

According to the registry system it should show up right before the stopper block.

**Comment by Ghost1138** [comment]
Thanks for answering, I tried the recipe and it worked, thanks! (It worked in the normal Crafting Table, not in the Train Workbench, just in case it's intended to work in both tables)

Just looked carefully at every page of the book again and the recipe it's not there. If the stopper block is the "Train Buffer", then this is how it looks in my screen:

Page 52 of 153: Iron Cab / Iron Frame
Page 53 of 153: Slope Track (Wood) / Train Buffer
Page 54 of 153: Rail / Windmill

About the achievement, I used the Heart Furnace from TC to get the steel ingot, I tried a few times and I didn't get the achievement. It's not an important issue but just to let you know.

I made sure I have the lastest version of the mod before posting this issue. Is 4.4.1_020 alpha the latest version? Because I couldn't find a newer one anywhere. Also, Traincraft is the only mod I have installed at the moment.

**Comment by EternalBlueFlame** [comment]
Well I fixed the recipe error, but honestly I'm not fully sure what's going on with the achievement.
I gave it ore directory support in case that was the issue, but aside from that, everything looks right.

and yes, 020 is the latest.

**Comment by Ghost1138** [comment]
Thanks, I'll let you know if I manage to complete the achievement. Thanks again!

**Comment by Ghost1138** [comment]
I've been trying to get the Steel achievement but I couldn't complete it until I've started a super flat creative world. I completed the achievement in the creative world by doing exactly the same I did in the survival world. Then I tried one last time in the survival world and it worked now. Seriously, I'm not sure what's going on, but at least it's fixed now.
