### ISSUE TITLE
Make TrackBuilder acceptable for Traincraft-Tracks [Original Idea]

### ISSUE THREAD

**Issue by NitroxydeX** [EternalBlueFlame/Traincraft-5#47]
The GUI says "Support for new rails will be added later" - This is an enhancement. But when you place our rails in it it will crash. We should avoid that.

**Comment by EternalBlueFlame** [comment]
Weird that support isn't there for that yet, maybe because the track builder is built for mimicking a normal minecart still, that might be a pain to update, although we should eventually.
the crash at least needs fixing.

**Comment by Hagrud** [comment]
I quickly look at the trackbuilder, it only crash because PluginRailcraft.RailcraftParts.INGOT_STEEL.stack is null, it will be easy to fix.
But after that he will not place tracks.

**Comment by EternalBlueFlame** [comment]
crash fix as of:
[https://github.com/EternalBlueFlame/Traincraft-5/pull/54](https://github.com/EternalBlueFlame/Traincraft-5/pull/54)
Still wont actually run on TC track.

**Comment by Hagrud** [comment]
I will try to work on this part, 

but I have some open questions:
- Do we only deal with SMALL_STRAIGHT tracks ? (this part should be easy)
- I guess we can also deal with slopes ( for example if we had +6 tracks and wood we allow to place a wooden slope) 
- I don't think we can deal with turn/switches.

So in a first time I will only allow small tracks.

**Comment by EternalBlueFlame** [comment]
Yeah I think the only option would be small straight tracks.
The main issue is getting it to actually run on small straight tracks, because right now it's a glorified minecart.
