### ISSUE TITLE
Trains won't slow down 1.6.4

### ISSUE THREAD

**Issue by SithTunaFish** [EternalBlueFlame/Traincraft-5#471]
None of the trains in the traincraft 1.6.4 version will slow down when pressing the s key I think it might be conflicting with other mods but I've tried to change key binds and nothing appears to be working I'm playing with the tekkit main pack and Flan's.

**Comment by NitroxydeX** [comment]
1.6.4 isn't supported by us. We can't provide any help for it. The version should work. Make sure it's not conflicting with anything else.
