### ISSUE TITLE
[1.7.10]crash when right clicking to a high star switch stand

### ISSUE THREAD

**Issue by tonimark** [EternalBlueFlame/Traincraft-5#474]
when I right click on high star switch stand the game crashes 
crash log:https://pastebin.com/4LDbPF1D

**Comment by chiel1112** [comment]
You do have the latest version correct?

**Comment by tonimark** [comment]
of course, I have installed Traincraft-4.4.1_020

**Comment by tonimark** [comment]
@chiel1112   by the way another bug occurred #475 game crashes every time I remove a locomotive
