### ISSUE TITLE
1.7.10 Textures From The Rails Bugged

### ISSUE THREAD

**Issue by TheKatherineManiac** [EternalBlueFlame/Traincraft-5#489]
![2019-10-05_15 13 45](https://user-images.githubusercontent.com/56195509/66255384-0f018280-e783-11e9-9dc7-d18e32f7cf31.png)

**Comment by member102250** [comment]
![image](https://user-images.githubusercontent.com/56566558/66788858-85238900-eee9-11e9-9b66-24b997c9cf0f.png)
got the problem with the bridge pillar and the high star switch stand and also signs.
![image](https://user-images.githubusercontent.com/56566558/66789098-696cb280-eeea-11e9-9c0a-0cf648b63305.png)

**Comment by EzerArch** [comment]
I have the same issue. It seems every time I start up Minecraft TrainCraft randomly picks a texture from any mod and swaps. Once I saw rail slopes rendering a texture from an Armourer's Workshop block while the said block was rendering the rail texture. My guess is there's a miscount of the slots in the texture atlas.

**Comment by EternalBlueFlame** [comment]
the issue for textures is related to how the textures are cached.
an attempted optimization for block geometry in 021 accidentally cached textures in the model vector array, which naturally, makes textures not show outside the frame that the cache is created.

a fix has already been made, however we're waiting on an unrelated fix from one of our contributors, before we push out the new version.

**Comment by SorenKyojin** [comment]
Got the similar issue with rail and vanilla chest only. Nothing on another mod is affected
The chest has gravel texture ? And rails takes particle texture, I really don't know why
![2022-07-22_21 00 21](https://user-images.githubusercontent.com/64634251/180507123-258f3143-fc04-45f2-9de9-3079083873d8.png)
![2022-07-22_21 05 10](https://user-images.githubusercontent.com/64634251/180507148-a7e73cb8-b6b8-463a-bfa6-7b4dc4699760.png)
Edit: Only railroad crossing haven't this bug

**Comment by EternalBlueFlame** [comment]
Just to be sure, which version was this on?
Looking at the image the geometry is right, and the texture is horribly wrong, not just positioned wrong but never bound in the first place, which would mean displaylist interference from something like optifine

**Comment by SorenKyojin** [comment]
> Just to be sure, which version was this on? Looking at the image the geometry is right, and the texture is horribly wrong, not just positioned wrong but never bound in the first place, which would mean displaylist interference from something like optifine

My mods: 
![image](https://user-images.githubusercontent.com/64634251/180620267-a30c89df-5ac7-4a4a-b9e3-983fa3123942.png)
Got this on 4.4.1_021
I'm not sure this is the last version
But this bug is random, I restarted the game, rails became normal but a freight became pink and black (missing texture)
I can't really explain precisely, this bug is strange and occurs randomly

**Comment by EternalBlueFlame** [comment]
4.4.1_021 is very outdated, the latest is currently TCCE 5, it's currently available on curseforge. I think the texture binding has been changed since, so maybe it's fixed...?
