### ISSUE TITLE
Trains on slopes

### ISSUE THREAD

**Issue by MacTirom** [EternalBlueFlame/Traincraft-5#492]
Some Pictures. It happens with many trains. 
TC 4.4.1_021
![2019-10-22_15 02 35](https://user-images.githubusercontent.com/16389466/67289267-a0d8f180-f4de-11e9-9f03-46b1da138260.png)
![2019-10-22_15 02 58](https://user-images.githubusercontent.com/16389466/67289268-a1718800-f4de-11e9-8f24-5de1f35004a2.png)
![2019-10-22_15 03 49](https://user-images.githubusercontent.com/16389466/67289272-a20a1e80-f4de-11e9-8050-d120d2acc21a.png)

**Comment by EternalBlueFlame** [comment]
This bug was intentional to prevent a block collision that would often reverse the train at full speed.
Nothing can be done until the rewrite.
