### ISSUE TITLE
Can not place diesel or steam engines on rails

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#496]
Just did a compile to test and noticed that you can not place any Steam or diesel trains on the rails . I tested a few cars and they place ok . there is no error

**Comment by Tsoccerguy3** [comment]
I pulled commit ae2b848e255bbb329fa1a3759fb5deadaacefc6c and placing engines works .Use this as a starting point . if i have time ill narrow it down to the actual code

**Comment by EternalBlueFlame** [comment]
thanks for pointing this issue out, i tried a few different trains and the forney of all things threw the error, got me a full stacktrace, I'll see about having this, and a few other issues i needed to handle, ~~done within a few hours.~~
scratch that timeframe, this is related to a git push by one of the contributors, I'm gonna have to get their help fixing this mess.

**Comment by Tsoccerguy3** [comment]
![2019-12-02_17 23 24](https://user-images.githubusercontent.com/22108822/70000308-c4a14580-1528-11ea-853c-b89b8ff69280.png)
![2019-12-02_17 22 13](https://user-images.githubusercontent.com/22108822/70000309-c4a14580-1528-11ea-80ee-2a6eee0abdd3.png)
![2019-12-02_17 21 51](https://user-images.githubusercontent.com/22108822/70000310-c4a14580-1528-11ea-82a5-d4698198b125.png)

Compiled with fixes , a new issue any engine or car rides up into the air when it encounters a barrier as seen in the images

**Comment by EternalBlueFlame** [comment]
shouldn't be a new issue, nothing in regards to those systems has changed in quite some time.

**Comment by Tsoccerguy3** [comment]
Eternal should I open a new issue with the cars riding up on the barriers and close this ?

**Comment by EternalBlueFlame** [comment]
you can, but it won't be receiving a fix until the rewrite anyway. Far as I know it's been around since 1.6, and I have no clue where the issue stems so i couldn't even begin to try and fix it.
