### ISSUE TITLE
Putting Traincraft in a Modpack

### ISSUE THREAD

**Issue by Omuck3** [EternalBlueFlame/Traincraft-5#50]
I'm currently trying to compile the mod.  If I'm successful, am I allowed to put the finished product in my modpack?

**Comment by NitroxydeX** [comment]
No you are not allowed to put it in your modpack. You only can put it in your modpack if it's an original provided jar-file by us. Every compiled version is not for distribution.

Read http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287038-traincraft-4-2-1?page=168#c3463 for more Information about the development status.

**Comment by Omuck3** [comment]
Ok, that's what I thought.  Thanks.
