### ISSUE TITLE
Windmills and the Diesel Generator don't work on Industrial Craft 2 machines.

### ISSUE THREAD

**Issue by DanielAntony201** [EternalBlueFlame/Traincraft-5#504]
![2020-02-10_11 28 17](https://user-images.githubusercontent.com/60870366/74129533-3ec10b00-4bf9-11ea-8b97-f8bf3c9c7847.png)
Am I missing something? When did you stop supporting IC2 compatibility? Did you really stop and delete the compatibility or is it some kind of an issue? If so then can you please fix it on the current version, before converting into 1.12.2? You would have my gratitude.

**Comment by EternalBlueFlame** [comment]
IC2 compatibility was dropped with the transition to 1.7.10. (something like 3 years ago now).

Our old 1.6.4 API implementation and their 1.7.10 API were completely incompatible, and we have yet to get anyone who is well versed in IC2's functionality.
That's only made more difficult by the sheer lack of documentation for anything older than 1.12, and the development community's bias against anything newer than the latest MC.
Similar issues exist for NEI.

Currently one fix is to use a 3rd party mod that supports both the CoFH API for RF, to work as an adaptor for TC to IC2.
But I can't say for certain when or even if IC2 support can be added back.

**Comment by DanielAntony201** [comment]
Ok, thank you for the answer. I hope you one day get the compatibility working again.

**Comment by DanielAntony201** [comment]
Is CoFH Lib the third party mod you mentioned?

**Comment by EternalBlueFlame** [comment]
No, there are a number of 3rd party mods that can do it. Thermal dyanmics, Ender IO, galacticraft, and mekanism just to name a few.
Usually Ender IO is the go-to for converting between EU/RF/MJ/etc due to the convenience of the pipes. Mekanism is usually the second choice due to the vast feature set.

**Comment by DanielAntony201** [comment]
Thank you for the help.
