### ISSUE TITLE
Crash when I try to open it

### ISSUE THREAD

**Issue by AndyNS1701** [EternalBlueFlame/Traincraft-5#507]
There is no Crash file but it crashes as soon as i open Forge 1.7.10 It just opens the launcher again. I switched to 3 versions and it wont work can i have help?

**Comment by EternalBlueFlame** [comment]
It may be an issue with either java or the memory allocation. 
- Most stock java versions are 32-bit even on 64-bit machines, so they are limited to 4gb of ram, be sure your settings don't exceed that.
- Alternatively you may be running java 9 or newer which is fully incompatible with 1.7.10. you can check this by opening CMD and typing `java -version` alternativley it should also be listed under the advanced settings of the launcher.
Unfortunately oracle took down JDK builds of 1.9 and older, so the only way i can offer you a link for 1.8 is from my personal cloud.
[https://mega.nz/#F!1o1TTCRS!NB_GSehRW5iJ-R6ntrhgkA](https://mega.nz/#F!1o1TTCRS!NB_GSehRW5iJ-R6ntrhgkA)

if all else fails, not every crash produces a crash log, and instead prints it to the normal logs, so try sending your latest log in that case.


Also to answer the question before it's asked, if you start the game but it crashes when loading world, boot back up your newer minecraft instance and lower the view distance to 16 or less, the versions share a config but 1.7 cant handle the larger view distances.

**Comment by AndyNS1701** [comment]
Ive done the "Also to answer the question before it's asked, if you start the game but it crashes when loading world, boot back up your newer minecraft instance and lower the view distance to 16 or less, the versions share a config but 1.7 cant handle the larger view distances."
thing multiple tines and the cmd prompt says i have java "1.8.0_251"

**Comment by EternalBlueFlame** [comment]
and you're sure and there's nothing in the crash reports or logs folder?
