### ISSUE TITLE
problem during mod loading

### ISSUE THREAD

**Issue by msorenp** [EternalBlueFlame/Traincraft-5#513]
So I'm trying to start a forge server with my friends and traincraft was one of the mods. I'd open the server console and it would just close after about 5 seconds. Alternatively, I tried to load the mod in single player and this error comes up: Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: train/common/api/EntityRollingStock

I'm not sure exactly what to do or if there is a prior remedy.

**Comment by EternalBlueFlame** [comment]
I'd need a lot more of the error log than that.

But first thing I would say is be sure you are getting the mod from curseforge, and that you are using a forge compatible 1.7.10 server.
Also be sure you don't have multiple copies of the mod in your mods folder.
