### ISSUE TITLE
Traincraft Glitch

### ISSUE THREAD

**Issue by SkytechStreams** [EternalBlueFlame/Traincraft-5#514]
Good Morning. I would like to report a bug that i saw a few days ago in my Minecraft word. 
Pratically, sometimes I step away from a track, because I want to modify a station or a track. When I return to continue the building of the new track, some parts of it disappears. But the strangest thing is that they don't completely disappear, but become invisible and, keep on tight, they still work. 
I did this report because i would like to do a video about this mod (Traincraft, I mean) and I don't want to see this bug. 
So, can you resolve this issue in the next update, please?
Thanks very much for the reply.
P.s Sorry for my bad english, but I'm not from USA or UK.

**Comment by chiel1112** [comment]
Do you have optifine installed? This is mainly what’s causing this. The other solution is using the compile from the github (it has an installer so it’s quite easy) or look in the server pack of The Lost Rails for a public beta.

**Comment by EternalBlueFlame** [comment]
Aside from the optifine note, this is a known bug in 020 with other mods, and 021 even without mods.

A number of related issues have been fixed already for the next release, there are a few less issues with optifine and other mods that still remain because we have not been able to track them down, but the worst of the issues were due to some rendering changes in 021 which have been fixed.

**Comment by SkytechStreams** [comment]
So, in a few words, the problem is not at 100% caused by Optifine?
Ok, i will wait for the next version.

**Comment by chiel1112** [comment]
It should be out soon!

**Comment by chiel1112** [comment]
here is the changelog for the new version by the way (can be found on the discord)
[022_changelog.txt](https://github.com/EternalBlueFlame/Traincraft-5/files/4639877/022_changelog.txt)

**Comment by SkytechStreams** [comment]
Ok. Thanks very much.

**Comment by SkytechStreams** [comment]
Uh, I found another bug: the texture of the rails doesn't load in some parts of the track. I tried to create another world, but it didn't resolve this issue. 
Will you resolve it for the next release? Thanks for the reply.
P.S. Here's the screen of the glitch:
![2020-05-18_11 29 56](https://user-images.githubusercontent.com/65443645/82197794-b212a100-98fb-11ea-9d53-8b2c363318da.png)

**Comment by chiel1112** [comment]
Hmmm, that is a new one. Your best bet would be waiting for @EternalBlueFlame xD

**Comment by SkytechStreams** [comment]
And another question: did you delete the page of Traincraft mod in Curseforge? Because when I go to your sites it gives me an error.

**Comment by chiel1112** [comment]
There has been an _issue_

Best not to talk about it; although for the time being until CurseForge gets back again the files are hosted on discord ( https://discord.gg/SgpnCnK )

**Comment by SkytechStreams** [comment]
Ah. Ok. Thanks for the reply

**Comment by EternalBlueFlame** [comment]
The issue with the faulty textures is related to the bug with invisible textures. It's already been dealt with for the next release.
