### ISSUE TITLE
banning players from using your mod??

### ISSUE THREAD

**Issue by FinnT730** [EternalBlueFlame/Traincraft-5#517]
Why the fuck would you ban players from using your mod? This will 1. Give you an bad name, and a bad name to the mod.
If you hate copyright so much, you should file a DMCA request on 9minecraft `http://www.9minecraft.net/traincraft-mod/`

You made me never want to play with this crap mod, banning players..... jesus...... this is minecraft, FOR KIDS. You are NOT Ubisoft or EA.

**Comment by frqnny** [comment]
i agree pls don't ban people because it doesn't accomplish anything, we can just remove that event easily.

**Comment by FinnT730** [comment]
Then please do.

**Comment by Commentius** [comment]
Consider, the people banned have not been normal users, but people who harmed both the mod and the community, go and defend griefers who destroy your railway if you may.
You are playing into their hands and being manipulated.

This is also a GitHub repository, please do issue reports the proper way.

**Comment by FinnT730** [comment]
> This is also a GitHub repository, please do issue reports the proper way.
That might be where?

I mean, sure, let's go of by that logic. I will blacklist everyone I hate, that might have griefed in MY server.
Does this mean they grief on another server? They may. Is this a perfect and good reason to blacklist them from using the mod AT ALL? No.
The reason they were blacklisted was because of copyright. It is right there in the code. It has an online check for that account. 

What if I blacklisted this mod to use AT all? Would that be nice? No. 

If the owner really cared about copyright, he should sue 9minecraft for reposting and reuploading and making money from his port. Do also note, this is AN PORT from the original mod. This is added code by him, since this was not there before.

**Comment by bigFISH496** [comment]
> You made me never want to play with this crap mod

Don’t let the door hit you on the ass on the way out

**Comment by FinnT730** [comment]
> Don’t let the door hit you on the ass on the way out

Don't worry I won't, I just blacklisted this as the worst mod out there.

**Comment by Commentius** [comment]
Consider, it's the people who griefed many servers, verbally abused many, raided many chat rooms (with 18+ rated stuff reports say) and more.
It is indeed people you would ban on first sight as they committed illegal deeds.
You're defending what could be called criminals.

The ban function is solely intended for such people.
If you want it away do it a civilized way, joining their raid is not.

**Comment by Green-PC** [comment]
Although yes, one person has been banned for redistributing content without permission and then denying he did so, other people have been banned for spreading heavy toxicity in several discord servers/MC servers connected with TC in any way. Going as far as raiding the different discords with pornographic content.

**Comment by Messicrafter** [comment]
Which is Fully within the rights of the Mod to do.

**Comment by FinnT730** [comment]
Even when they are blacklisted, they can still do that, so that does not change a thing really. 
And then, if they are blacklisted, they can just use a cracked version of the game, or buy a new account, so how would that work out?
I guess what I more tried to say is this: This does not solve to problem, this is making it worse. If you want people gone, ban them in the server, be that in Minecraft, be that on Discord. If it was on the forums, ban their IP address, or delete their account. Stopping them from using the mod is not a secure way of getting them to stop. If I knew people were this toxic and spread 18+ things, I would have worded it different from the get-go, but I did not.

**Comment by CuzImDestroyer** [comment]
It is pretty unusual that a person buys a new Minecraft Account only because of 1 Mod, that is rediculous. Also, if you intended that, why then start a discussion like that it is not human to do that but only intend to say that this doesn't solve the problem?

**Comment by Green-PC** [comment]
>  If I knew people were this toxic and spread 18+ things, I would have worded it different from the get-go, but I did not.

Thanks for understanding.
We will try working on this issue and maybe change this.

**Comment by Green-PC** [comment]
> Also, if you intended that, why then start a discussion like that it is not human to do that but only intend to say that this doesn't solve the problem?

He has explained what he meant, might not have known all the details (as he also stated in his recent comment "If I knew people were this toxic and spread 18+ things, I would have worded it different from the get-go, but I did not"). Don't continue this please.

**Comment by CuzImDestroyer** [comment]
I didn't read that whole thing, mistake on my part.
But it doesn't justify to start a conversation that rude, that was my point if you missunderstood me. Opinions and suggestions for improvement are always welcome, but that made it really go into the wrong way because it was not polite, doesn't matter if knowing the circumstances or not. But yeah, let us wait till Eternal posts his comment on this whole topic and just stop getting spicy and all rude against each others.

**Comment by infiniteblock** [comment]
This is a violation of Cf and the EULA.

You banned me because im toxic for pointing this out.. check out the last guy who did this and was banned from CF
https://www.reddit.com/r/feedthebeast/comments/g3fekk/looks_like_plus_tic_and_all_of_landmasters_mods/

Now check out the verbal abuse to me and about my children from eternal... seriously what is this developer upto this is disgusting!
https://media.discordapp.net/attachments/619077509320933386/711496530678251540/eternal1.png?width=887&height=501

https://media.discordapp.net/attachments/619077509320933386/711496522486775818/tc.png?width=887&height=501

**Comment by Green-PC** [comment]
I'm sorry that you feel that way, but you indeed were toxic towards the community. I am not surprised that eternal snapped as you indeed did not give any proper proof of any of your claims yet continued.

**Comment by infiniteblock** [comment]
because i didnt state the line of the eula/tos does not equate to me being "toxic"

**Comment by EternalBlueFlame** [comment]
This issue will be dealt with as it seems the CF community is attempting to strongarm us, rather than pointing out what part of the TOS we're breaking.

The code was not made to be nice, it was made to punish users who have maliciously attacked staff and the community. But i guess if you hate us so much we'll just have to leave those people unpunished.

**Comment by infiniteblock** [comment]
Technic are also reviewing all the modpacks that are listed on your server list over this as well as its a violation for them too....

**Comment by EternalBlueFlame** [comment]
so, me updating to remove the feature literally isnt enough for you?
i hate you.
like, more than anyone.

**Comment by infiniteblock** [comment]
remove it... and it fixes everything but i also think we should talk in a week once stuff calms down... we had no issues before i pointed this out... it was never about getting u banned untill the stuff about my kids and me was said.... someone could have reported this without you known and ended everything in one hit... i was attempting to bring this to your attention but people got out of hand....

**Comment by broscolotos** [comment]
It doesn't help that you did this "bringing to attention" in a public chat, where people could freely comment on it and make it worse.

**Comment by Commentius** [comment]
Congratulations, you're about to ruin it for everyone, by causing a take down _everywhere_.

**Comment by EternalBlueFlame** [comment]
We wont talk infinite, not in a week, not ever. you were out to destroy me before i said a single thing about your kids, or even to you at all, and you know it.
The only thing I said about them was I feel bad for them having to grow up in an environment where you are an influence. Given the fact you have the reading comprehension of a gradeschooler let me elaborate, that was an insult to you. specifically.
I will still see to it that every mod and server knows about you and what you have done.

**Comment by infiniteblock** [comment]
your one very toxic man..... i have no respect for you and the fact your community is trying to defend you and your actions speaks for its self... other community's have seen what u have typed and what i have typed.. my dm's are flooded with support, people willing to stand up for me in other discords as well. What i did was right for the modding community in the long run right for traincraft not its current developer.

**Comment by EternalBlueFlame** [comment]
I really cant be bothered to care.
at the end of my day, i do a job maintaining three different mods. and you do a job of sitting around whining like a tumblerina, you, and your support, are less than meaningless.

the problem banning code will be removed in the next git push later today. consider that a win, and never return. EVER.

**Comment by FinnT730** [comment]
@EternalBlueFlame Sorry that this escalated this much. All I wanted was more info on this matter. As I stated as well. I did not know there was so much more behind all of it. I am happy that you are removing the code. So thanks for that. I hope all the people stop hating so much.

**Comment by EternalBlueFlame** [comment]
so why did you smear and slander as your first post?
that sounds like a load of it.

**Comment by FinnT730** [comment]
Since I mostly hate the way it was done. And from what I have seen it was because of copyright problems. Like I also said, if I knew there was a lot more going on, I would have worded it differently. My excuses in that.

**Comment by EternalBlueFlame** [comment]
think before you act.
saves you a lot of trouble in life.

**Comment by FinnT730** [comment]
eh, true

**Comment by Green-PC** [comment]
But thank you for understanding why such code was added in the first place.
