### ISSUE TITLE
Tier2 and Tier3 workbench can't craft any reciple

### ISSUE THREAD

**Issue by glebqip** [EternalBlueFlame/Traincraft-5#52]
Reciple:
![image](https://cloud.githubusercontent.com/assets/6125008/17084804/4a2f357e-51d0-11e6-8bf6-0c06e06f10c2.png)
Placed:
![image](https://cloud.githubusercontent.com/assets/6125008/17084808/68de917c-51d0-11e6-8d84-6cdeaae7eb28.png)
Also can't place to this red slot wooden planks and iron.
Checked Tier1 workbench - i can place in this red slot wooden planks and iron.

**Comment by NitroxydeX** [comment]
Wood is buggy for all our Crafting-Tables (this is something related to the handler)
Copper only seems to be buggy for TCs own Copper. Thats weird. But IC2 Copper gets detected before our copper. That could be a reason but shouldnt happen.

**Comment by Hagrud** [comment]
Well, this ugly orange ingot seems to be replace by steel ingot now.

**Comment by glebqip** [comment]
@Hagrud steel ignot also not working(lights red).
About copper - in first slot it working fine, but in last it's not working

**Comment by EternalBlueFlame** [comment]
should be fixed as of
[https://github.com/EternalBlueFlame/Traincraft-5/pull/53](https://github.com/EternalBlueFlame/Traincraft-5/pull/53)
