### ISSUE TITLE
Traincraft Glitch #2

### ISSUE THREAD

**Issue by SkytechStreams** [EternalBlueFlame/Traincraft-5#523]
I know, I had already mentioned it to Chiel1112 in the last report, but I would like Eternalblue to also see this new issue: pratically, this morning, when I went to my MC world, I saw this problem:
In some parts of the track, the texture doesn't load. So, I tried to create an another world, but same problem, this glitch doesn't disappear.
Will you resolve it for the next update? Thanks for the reply.
P.s. Here's the foto of the problem:
![2020-05-18_11 29 56](https://user-images.githubusercontent.com/65443645/82231755-e99a4100-992d-11ea-92d7-ccf3a82cdda3.png)

**Comment by EternalBlueFlame** [comment]
Answered in the other thread. Closing this one to clean duplicates.

**Comment by SkytechStreams** [comment]
Ah. Ok. Thanks
