### ISSUE TITLE
Does anyone know when the next release for Traincraft is coming out?

### ISSUE THREAD

**Issue by vinnyg0621** [EternalBlueFlame/Traincraft-5#528]
does anyone know when the next release is coming out? cuz the last time Traincraft updated was in May, right before summer, and it's not summer anymore

**Comment by EternalBlueFlame** [comment]
The next release is ready, however I'm waiting on word from the original owners before the update is pushed to CF.
I have no idea how long that's gonna take.

It also doesn't exactly help the project has never run on a release schedule of any from, kinda hard to do that with such a small development team.
