### ISSUE TITLE
oh yeah

### ISSUE THREAD

**Issue by gabbie777** [EternalBlueFlame/Traincraft-5#542]
noone's asking to be unbanned lol your staff is out of control so we commented on it and they decided to be a dick
we're trolling now because we completely bypassed the ban and we've been trolling on the IRC and your staff made the big boy move of calling us niggers through discord because of it

**Comment by Green-PC** [comment]
I'm very confused to what you're even talking about, especially the part where you stated TC staff was using racial slurs against others.

**Comment by chiel1112** [comment]
So am I, what are you talking about? Can you send some proof via discord to chielmeiberg1112#5821?

**Comment by gabbie777** [comment]
this is an alternate email and the spambots targetted the complete wrong
thread(So sorry!) the racist staff was actually on CreeperHost. My
sincerest apologies in the disturbance it caused.
