### ISSUE TITLE
ownership doesn't work on anything, prevents locking.

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#56]
Probably due to reliance on railcraft API based ownership, which doesn't work in 1.7 for the way we are using it.
Honestly it doesn't work well even when it is used right due to inability to properly transfer a GameProfile over NBT. We should be on a system that uses the player's UUID.
Display Name would be an option too, but creates issues with mods like Minecraft Comes Alive.

**Comment by MacTirom** [comment]
I can make a Youtube Video for Helpers. Can i?

**Comment by EternalBlueFlame** [comment]
@MacTirom this should have been in a new issue thread because it is unrelated.
And no, we will only allow for youtube videos on release versions of the mod, for a number of reasons.
We have not yet reached release stage because there are still some bugs that are game breaking.

**Comment by EternalBlueFlame** [comment]
fixed as of [https://github.com/EternalBlueFlame/Traincraft-5/commit/581b7f058773d3578208bae333b345f7e340f4d7](https://github.com/EternalBlueFlame/Traincraft-5/commit/581b7f058773d3578208bae333b345f7e340f4d7)
