### ISSUE TITLE
(021) world crash by Forney(US)

### ISSUE THREAD

**Issue by sPixture** [EternalBlueFlame/Traincraft-5#576]
So I was working on a project using predominantly Traincraft when I decided to try out some of the locomotives the mod had to offer and see which I liked most on the track. One of these was the Forney (US) steam engine, which I had noticed before would spawn tilted on the rails when placed under a 3-block high ceiling, cabin pointing up at a 45 degree angle. After placing it on a large straight piece of track, my world crashed and now I can't spawn back into it. One thing to note is that on the last frame the game rendered before crashing the loco was floating 1 block above the tracks it should've been on. Hopefully this can be fixed and I can enter the world again once the mod is updated and has fixed this issue.

**Comment by chiel1112** [comment]
Hi! There is a fix for this, which is to enable remove erroring entities and remove erroring tile entities in the forge.cfg (in your config folder). This will remove the train but allow you to keep playing in the world! (Also the forney hates the tc tracks

**Comment by sPixture** [comment]
Ah, I see, thanks for the response!

**Comment by chiel1112** [comment]
If it doesnt work feel free to give another shout!

**Comment by sPixture** [comment]
I followed your advice and I'm in the world again without anything lost (other than the broken Forney loco), it's a shame that it hates the TC track so much when its model looks stunning.
