### ISSUE TITLE
Jenkins Build

### ISSUE THREAD

**Issue by SeaLife** [EternalBlueFlame/Traincraft-5#60]
Hello,

i've setted up a Jenkins-Build on my Jenkins instance.

//ETERNAL EDIT -LINK REMOVED-

Every new push to the **1.7** branch will be built by this instance!

Greets
SeaLife

**Comment by EternalBlueFlame** [comment]
how about asking us BEFORE setting up a jenkins build?
there are reasons that we are not publicly releasing builds and we have asked people time and time again, do not distribute builds, our license forbids us from releasing anywhere other than github and curse.
Plus we don't need/want to deal with the backlash of people getting builds that aren't stable.

Please remove the jenkens immediately.

**Comment by SeaLife** [comment]
Hi,

as of the custom usage license im allowed to build projects of TC in Jenkins.

I just renamed this to "Minecraft Train Mod for 1.7.10 (nightly-build)" and added references to the description and i should be fine with the license terms.

This is just for these users who wanna try this Mod and properly report bugs but they dont need to compile this on their own.

The average MC Player is about 15-17 years old and do not know how to use gradle or something like that. I'm just helping the community.

As of Official Usage License (found here: https://github.com/Mrbrutal/Traincraft-164/blob/master/LICENSE.md) the Jenkins Job will persist!

Greets
SeaLife

**Comment by 31trainman** [comment]
No the license is a jumbled mess, Jenkins is only allowed if brutal or spitfire says it's allowed, either you take it down or we will take legal action against you to get it removed by force if needed.

**Comment by SeaLife** [comment]
Fix the License.

Revoked Public-Permissions on Jenkins.

**Comment by SeaLife** [comment]
Reported to MrBrutal, Closed.

**Comment by NitroxydeX** [comment]
The License prohibits the distribution of Traincraft on any site if you do not have the permission from MrBrutal.

**Comment by EternalBlueFlame** [comment]
Don't get irritated at us for the license that the actual owners of the mod wrote. Which you didn't read all the way.

After all @SeaLife this is YOUR fault for not ASKING us before you tried to do something like this.

Look at the terms of DISTRIBUTION, in the license you linked. That's where these builds are prohibited.

On top of it, the entire reason that we aren't giving builds out right now, or at least a big part, is that when we change ownership code, it will corrupt everyone's save files and servers.
WE'RE HOLDING BACK BUILDS FOR YOUR OWN GOOD.
of course you would know this if you actually bothered to get off your lazy but and ask or try and communicate before doing things.

Maybe you should learn to read and communicate before trying to get into the modding scene.

And I'm leaving this issue open to be an example for future kids who can't read.

**Comment by Cronosus** [comment]
better than jenkins is just forge environment, if you want just to make build.
