### ISSUE TITLE
Dummy Alert

### ISSUE THREAD

**Issue by GlacierPark19** [EternalBlueFlame/Traincraft-5#607]
Hey guys!

First off, Traincraft 5 is AWESOME. I love it even with the instabilities. However, I am not the brightest bulb on the tree. In Traincraft 5.0.2 how do we create switches? Thanks!

**Comment by GrahamGee** [comment]
You want to create the patterns of stuff using the rails itself, they should automatically snap into the shape you are trying to make, a switch would be a diagonal going into a straight

**Comment by GlacierPark19** [comment]
This is using the rail "blocks" in world right?

**Comment by GrahamGee** [comment]
yes, if you place them in patterns they should form different shapes, for example making a diagonal line should also create a straight diagonal track.

**Comment by GlacierPark19** [comment]
Okay thanks! Do  The high star switch stands work like before?

**Comment by GrahamGee** [comment]
I'm not sure, but I do know levers work, you can try both and see if it works.

**Comment by GlacierPark19** [comment]
Okay thanks!
