### ISSUE TITLE
Train/rollingstock/zepplin controls still active while typing in chat.

### ISSUE THREAD

**Issue by RevoSucks** [EternalBlueFlame/Traincraft-5#62]
Known issue since 1.6.4 I think, but I think the fix is relatively minor. Could be wrong though.

**Comment by EternalBlueFlame** [comment]
I'm renaming this issue because this issue could persist in other areas due to how these systems are managed.

Theoretically this could be fixed through the packets or the packet manager, to check if the player's chat window is active before trying to process the packet.

**Comment by NitroxydeX** [comment]
This only happens to Zeppelins. Fixed it.
