### ISSUE TITLE
incompatibility issues with forge

### ISSUE THREAD

**Issue by thefoxywriter** [EternalBlueFlame/Traincraft-5#631]
ok.... i downloaded all the newest versions of everything since everything said it was compatible with everything. now when i open forge in minecraft it says that the traincraft mod isnt compatible and is only for an older version of forge. im REALLY confused and frustrated. someone please help

**Comment by EternalBlueFlame** [comment]
the mod is currently only available for 1.7.10.

**Comment by thefoxywriter** [comment]
right so why am i getting that message? im running on 1.7.10

**Comment by EternalBlueFlame** [comment]
Okay thats a weird one.
Do you mind having it error like that again and then sending the latest log for it?
Its not a crash so hopefully the logs will say why, because thats not normal behavior.

**Comment by thefoxywriter** [comment]
Alright

**Comment by thefoxywriter** [comment]
heres that latest log

**Comment by thefoxywriter** [comment]
Nevermind I got it working. I think I sent you the wrong log that's for a
different mod

**Comment by EternalBlueFlame** [comment]
The messages also did not include logs.
Possibly a limitation of replying via e-mail. Good to hear that it's working at least.
This is the thread link if you want to try again: [https://github.com/EternalBlueFlame/Traincraft-5/issues/631](https://github.com/EternalBlueFlame/Traincraft-5/issues/631)
