### ISSUE TITLE
Mod not appear in mods menu

### ISSUE THREAD

**Issue by SolidFEAR** [EternalBlueFlame/Traincraft-5#640]
I have 1.17.10 version of game and mod. Already put traincraft in mods folder but mod not appear in game. Tried Xaeros minimap and this mod works perectly. Please help. 
Maybe traincraft needs another companion mod?

**Comment by broscolotos** [comment]
1.17.1 or 1.7.10? There is a massive difference. We support 1.7.10, not 1.17. And no, traincraft does not have any core mods.

**Comment by SolidFEAR** [comment]
1.17.1. I can't find 1.7.10 in Installations menu

**Comment by EternalBlueFlame** [comment]
1.17 is not supported at this time. only 1.7.10, which is 10 major releases of the game older.

If the official launcher doesn't give an option for it, try manually installing forge 1.7.10 from their website.
or alternativley, try technic, the new mojank launcher is trashy anyway.

**Comment by SolidFEAR** [comment]
> 
> 
> 1.17 is not supported at this time. only 1.7.10, which is 10 major releases of the game older.
> 
> If the official launcher doesn't give an option for it, try manually installing forge 1.7.10 from their website. or alternativley, try technic, the new mojank launcher is trashy anyway.

Is 1.17.1 and 1.17.10 same? I'm not use 1.17. I'm using 1.17.1

**Comment by EternalBlueFlame** [comment]
We currently only support, One point seven point ten.

I would advise reading slower, and/or taking a reading comprehension class.
