### ISSUE TITLE
glitched out

### ISSUE THREAD

**Issue by bigdaddypots** [EternalBlueFlame/Traincraft-5#657]
idk why but chunks are not loading, I cannot hold anything in my hand or the screen goes one color. using windows, java edition.

**Comment by frogking123** [comment]
me to

**Comment by EternalBlueFlame** [comment]
This is a known issue with intel graphics drivers.
You may need to update drivers from the official intel website, or potentially roll them back to an older version.
It's possible that reinstalling with Display Driver Uninstaller may fix it too, but careful with that one it can cause more harm than good if you don't do it right.

I don't have a development workspace with this problem, so it's not something i expect to fix anytime soon.
