### ISSUE TITLE
[suggestion] Sunken Rail

### ISSUE THREAD

**Issue by canVuild** [EternalBlueFlame/Traincraft-5#663]
You _probably_ already know what I'm talking about but I will clarify;  instead of the rail sitting on a block as a tile, the rail is the block, and the top of the rail is flush with the surface of a block that you put next to it.

What i specifically have in mind is the ground of the rail-block would be at the same height as the top of the rail as well, preferably. 

Naturally you'd need a block or two to slope down to the lower block, a couple "sixteenths."

The reason I would like to see this implemented is it pairs VERY nicely with the [big doors mod](https://minecraftmodspc.com/big-doors-forge/) for shed doors. I've already tried the multi part mod (allowing multiple blocks in a space) where it seems it was only designed for redstone torches. 🙄 

—————

I know I can just destroy the rail blocking me from placing the door, and replace it when the door is open, but who wants to do that?

I've even managed to place the doors sideways so that when they're open, and there's two pairs of them, the shed appears closed from the outside without mods or deleting the rail or having Sunken Rails. But there's two extra doors inside the shed in the way. I could add an entrance chamber and just extend the shed.

Yes this will take years to get around to considering everything here is always being rewritten but I'm just voicing myself. I really love this mod no matter what. All you need is a little sunken rails in your life. Maybe I could try to add them myself...? Would I be able to dig myself out of that hole

**Comment by EternalBlueFlame** [comment]
The issue with a sunken rail design is that you can't have the height negative of a block, the block will just render over it and "eat" it, so your "rail is the block" idea is the only way to do it.

Now the problem with that design is that the block height detection would have to be vastly offset, and the check for rail blocks would now have to cover two separate block positions per movement (the current block position where track would normally be, and the lower block position where sunken track would be).

For TCCE that's up to the community, so whoever wants to take the task and put it in, if they're willing to do the work i'm up for publishing it.

For TC5 there are similar plans that can be modified to accommodate this use case, but the focus right now is fixing the many bugs listed on it's section of the project trello, track improvements are the step after, but at the current speed things have been going, we'll be lucky if that's by the end of the year.

for reference, the current issue tracker trello: https://trello.com/b/cqaw1T3R/traincraft

**Comment by canVuild** [comment]
Thank you very much for your in-depth reply. I later realized it is very similar to the top of a slope block. I was actually able to put a big door over the rails while not letting the door look like its hovering too far above the rails. This is only really practical for more open areas instead of sheds since it only works on slopes, not to mention I only like using 1x18 slopes.

I really love the dynamic slope concept! Can't wait to see it be implemented.
