### ISSUE TITLE
Can't access locomotive GUI with R

### ISSUE THREAD

**Issue by Pringles-E** [EternalBlueFlame/Traincraft-5#666]
Used to play off the old launcher, but I've recently re-installed, currently using the new curseforge install with all the other modpacks. I can't seem to access the engine GUI by pressing R, and can't seem to find a work around.

**Comment by chiel1112** [comment]
Do you per chance have trains in motion or experimental traincraft 5 mod installed alongside TCCE? Is this about TC5 or TCCE?

**Comment by Pringles-E** [comment]
I apologize, I think I downloaded the wrong modpack. I thought I downloaded the actual release but it looks like it was a modpack directly off curseforge that was bundled with a bunch of other mods.

**Comment by EternalBlueFlame** [comment]
the GUI can also be rebound in the game controls settings, so with a modpack it's worth checking what button it's bound to, or if there's any conflicting keybinds.

**Comment by Pringles-E** [comment]
I'll have to root around for the rebind, thank you very much!
