### ISSUE TITLE
graphics bug

### ISSUE THREAD

**Issue by trainguy7** [EternalBlueFlame/Traincraft-5#672]
hello dear development team, i wanted to play a traincraft today but when i create world entities are black and i can't see some trains. When i place track the chunk becomes unloaded and i would really like to recive more info about it, thank you for reading this maybe you can help me out.

**Comment by EternalBlueFlame** [comment]
This is a known issue with some versions of Intel and Nvidia graphics drivers.

Be sure to update them from the official website, 3rd party tools and windows update can often leave out optional libraries or create conflicts from older driver installs.

In some rare cases you may need to do a clean reinstall of the drivers using a tool like Display Driver Uninstaller, 3D guru still has a free installer for it.
However if you use that tool be sure to read the instructions CAREFULLY, if you do it wrong you can break a lot of stuff.

This affects all versions of the mod, and I don't have a machine that can replicate the issue, so I have yet to find a fix for it.
