### ISSUE TITLE
Graphics Bug, Black Tracks 

### ISSUE THREAD

**Issue by Blutwurst1998** [EternalBlueFlame/Traincraft-5#674]
Hi,

I have a Bug where Tracks appear Black depending on the direction the Player is looking.

When holding some Blocks Like Grass Block the following appears:
The Menu is with White Background and new Blocks appear Black when in Players Hand, not when Build.
Also the center Cross of the Player is missing.
Also  Journeymaps Minimap will not be Displayed corrcectly.

When laying new tracks, the map gets some kind of transparency

![Bild1](https://github.com/EternalBlueFlame/Traincraft-5/assets/142173966/db208c72-2886-4cbc-9d77-0af522a09d05)
![Bild2](https://github.com/EternalBlueFlame/Traincraft-5/assets/142173966/8b240fdb-71d3-4086-a7ac-e0cbee5ad91a)
![Bild3](https://github.com/EternalBlueFlame/Traincraft-5/assets/142173966/3ca244fa-b16f-42fc-9cd1-cf1d51a81a60)

What could be the Problem?

Thanks for your Help.

**Comment by EternalBlueFlame** [comment]
gonna close this one, with the note this is being worked on for a future update, but right now optifine is known to cause this bug, deleting the optifine config usually fixes it. Neodymium is also known to fix it alongside just making the game run better.
[https://github.com/makamys/Neodymium](https://github.com/makamys/Neodymium)
