### ISSUE TITLE
S100 Proportions

### ISSUE THREAD

**Issue by Trainz2221** [EternalBlueFlame/Traincraft-5#675]
the proportions are WAY off. it's way too short to even count as a standard gauge engine

**Comment by EternalBlueFlame** [comment]
Fun fact, it's not standard gauge. It's 750mm!
Google searching "Minecraft track gauge" could have told you that.

**Comment by Trainz2221** [comment]
still too small. the head of player clips through roof

**Comment by happyburger23** [comment]
> still too small. the head of player clips through roof

still an extremely minor issue

**Comment by bidahochi** [comment]
> still too small. the head of player clips through roof

_hows this for height?_

![image](https://github.com/EternalBlueFlame/Traincraft-5/assets/47529075/9fde05a2-24d7-4859-8f10-99f03d629e07)

**Comment by EternalBlueFlame** [comment]
The player clipping is more of a rider position issue than a scale issue, the train is normally short, that doesn't play well when it's scaled down to 750 mm.

That is a valid issue though, so I'll see if I can fix the rider position for the next update.
