### ISSUE TITLE
cracked traincraft servers

### ISSUE THREAD

**Issue by canVuild** [EternalBlueFlame/Traincraft-5#691]
i would like to know if there are any. thank you and have a nice day.

**Comment by RealTBEA** [comment]
This is not precisely the place to ask this question as this is for issues with the mod itself. Please refer to the Offical TC Discord for trying to find tc servers

**Comment by EternalBlueFlame** [comment]
Questions relating to pirating software is really walking the line of the GitHub TOS, I'm gonna have to close this one.
