### ISSUE TITLE
Train Buffer y=NaN issue only affecting certain train cars.

### ISSUE THREAD

**Issue by RevoSucks** [EternalBlueFlame/Traincraft-5#74]
This is a fairly weird bug I found last night: Driving specific train cars into a train buffer facing south or east directions until it wont go any further and then attempting to get out of the train results in the player being flung into a NaN dimension. (y: NaN)

The following trains are affected:

```
No steam trains are affected.

Diesel:
SD40
SD70
GP40
GP7Red

Electric:
TramNY
VL10
High-Speed Car
```

**Comment by NitroxydeX** [comment]
Not even related to derailing. Related to updateRiderPosition. We're preventing the NaN now.
