### ISSUE TITLE
tracks remove tall grass

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#75]
The tracks can remove grass, they should also be able to get rid of any tall grass in the way when placing.

**Comment by NitroxydeX** [comment]
Tall Grass is handled like Flowers which aren't auto-removable

**Comment by EternalBlueFlame** [comment]
its possible to programmatically remove blocks, and we already check the area for blocks that would stop us, soooo, why not detect if one of the blocks is the tall grass and remove it before placement?

**Comment by Hagrud** [comment]
I made a commit that allow rail to replace double tall grass in the way and also to replace the grass when we click on it.
Did we need more (for example replace flower, sugar canne...) and if yes did we need to keep the drop of the destroyed block ?
