### ISSUE TITLE
Add support for other water containers accepted in trains/tenders

### ISSUE THREAD

**Issue by InuYasha86000** [EternalBlueFlame/Traincraft-5#78]
I noticed that only buckets could be drained into the water tanks within trains and tenders, if it's at all possible, I would like to see at least compatibility for drums from the mod Extra Utilities to be added, what could happen is if a drum is placed in the water filling slot in the train/tender GUI, if you hovered over the drum you would see a tool tip appear showing what the fill level of the drum is (eg. 121,000 of 610,000). hopefully that makes sense.

**Comment by EternalBlueFlame** [comment]
this is actually a bug due to the initialization of the tank not being some form of null fluid. the lava tanker is the only cart that's supposed to only be a specific liquid.

**Comment by NitroxydeX** [comment]
We can't support Extra Utils. No API and they fail on register their Containers the correct way. IC2 & Forestry working and tested.
