### ISSUE TITLE
Pulled carts reverse pitch on slopes when going reverse on MC based tracks

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#92]
http://i.imgur.com/TWtItUg.png
It's not every cart though, it's a bit random, as if they don't always turn the way they are being pulled.

**Comment by MacTirom** [comment]
Is this only at the "Vanilla" Tracks? Or at the TC Tracks too?

**Comment by NitroxydeX** [comment]
partly Vanilla/Railcraft because we handle render position on TC-Tracks different. But it fails on TC Track with placing too.

**Comment by NitroxydeX** [comment]
The bug happens here: https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/EntityRollingStock.java#L937 
It's how we detect if the EntityRollingStock is in Reverse-Mode

It's over 180 if we place down the EntityRollingStock

**Comment by EternalBlueFlame** [comment]
finally fixed in [#226](https://github.com/EternalBlueFlame/Traincraft-5/commit/9d31c2f15d4d5fc3005f3367933760662a72a0ed)

**Comment by NitroxydeX** [comment]
Well. This is something like two problems now. We fixed the placement but not the reverse on slopes if we are going reverse.
Part fix in #99

**Comment by NitroxydeX** [comment]
Fixed https://github.com/EternalBlueFlame/Traincraft-5/commit/02cd95ce398f512c37453edb60eb13f757988ad2#diff-0ad983561e97c53441dd9cf00de1f388R154
