### ISSUE TITLE
Train Buffer Bug

### ISSUE THREAD

**Issue by MacTirom** [EternalBlueFlame/Traincraft-5#95]
I'm not sure whether you already fix this. I simply times shown.

![2016-08-17_23 06 41](https://cloud.githubusercontent.com/assets/16389466/17788681/33336a84-658f-11e6-9411-694d157b4e3e.png)

**Comment by EternalBlueFlame** [comment]
I can also confirm.
seems to be some form of texture defect on the model.

**Comment by NitroxydeX** [comment]
Should be an enhancement. when do you look under items in your hand?

**Comment by EternalBlueFlame** [comment]
True, and it is only minor cosmetics. not to mention something I'm sure carried over from 1.6.4.
It's really not worth fixing on initial release because it doesn't effect gameplay.

**Comment by amerem3** [comment]
It bothers me though so maybe ill take a look at it lol by the looks of it it might be a model issue I say this because it doesn't show the track underneath it until its placed but it does show what appears to be a miniature vanilla track under it so it might be simple to fix idk yet

**Comment by EternalBlueFlame** [comment]
Go for it. It's either a texture or a model issue. Probably model scaling.. While it is possible, I find it unlikely it's code related, although it could probably be fixed in code.

We don't have to wait till RC2 to do enhancements. Nitro sure hasn't waited, haha!

**Comment by NitroxydeX** [comment]
Don't hate me @EternalBlueFlame :(((((( :D

**Comment by NitroxydeX** [comment]
texture wasnt loaded for the item model. derpy anyone who did this render..
